/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1000_deviceType = 0x00000000,
    .x1001_errorRegister = 0x00,
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identityObject = {
        .numberOfEntries = 0x04
    },
    .x1400_receivePDO_CommunicationParameter1 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000200,
        .transmissionType = 0xFE
    },
    .x1401_receivePDO_CommunicationParameter2 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000300,
        .transmissionType = 0xFE
    },
    .x1600_receivePDO_MappingParameter1 = {
        .numberOfEntries = 0x00
    },
    .x1601_receivePDO_MappingParameter2 = {
        .numberOfEntries = 0x00
    },
    .x1800_transmitPDO_CommunicationParameter1 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000
    },
    .x1801_transmitPDO_CommunicationParameter2 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000
    },
    .x1A00_TPDO_MappingParameter1 = {
        .numberOfEntries = 0x00,
        .mappingEntry1 = 0x00000000,
        .mappingEntry2 = 0x00000000,
        .mappingEntry3 = 0x00000000,
        .mappingEntry4 = 0x00000000,
        .mappingEntry5 = 0x00000000,
        .mappingEntry6 = 0x00000000,
        .mappingEntry7 = 0x00000000,
        .mappingEntry8 = 0x00000000
    },
    .x1A01_TPDO_MappingParameter2 = {
        .numberOfEntries = 0x00,
        .mappingEntry1 = 0x00000000,
        .mappingEntry2 = 0x00000000,
        .mappingEntry3 = 0x00000000,
        .mappingEntry4 = 0x00000000,
        .mappingEntry5 = 0x00000000,
        .mappingEntry6 = 0x00000000,
        .mappingEntry7 = 0x00000000,
        .mappingEntry8 = 0x00000000
    },
    .x6007_abortConnectionOptionCode = 0,
    .x603F_errorCode = 0x0000,
    .x6042_vlTargetVelocity = 0,
    .x6045_vlManipulatedVelocity = 0,
    .x6046_vlVelocityMinMaxAmount_sub0 = 0x02,
    .x6047_vlVelocityMinMax_sub0 = 0x04,
    .x6048_vlVelocityAcceleration = {
        .numberOfEntries = 0x02
    },
    .x6049_vlVelocityDeceleration = {
        .numberOfEntries = 0x02
    },
    .x604A_vlVelocityQuickStop = {
        .numberOfEntries = 0x02,
        .deltaTime = 0x0000
    },
    .x604B_vlSetpointFactor_sub0 = 0x02,
    .x604B_vlSetpointFactor = {1, 1},
    .x604C_vlDimensionFactor_sub0 = 0x02,
    .x604C_vlDimensionFactor = {1, 1},
    .x6056_vlVelocityMotorMinMaxAmount_sub0 = 0x02,
    .x6057_vlVelocityMotorMinMax_sub0 = 0x04,
    .x6058_vlFrequencyMotorMinMaxAmount_sub0 = 0x02,
    .x6059_vlFrequencyMotorMinMax_sub0 = 0x04,
    .x605A_quickStopOptionCode = 2,
    .x605B_shutdownOptionCode = 0,
    .x605C_disableOperationOptionCode = 1,
    .x605D_haltOptionCode = 1,
    .x605E_faultReactionOptionCode = 2,
    .x606E_velocityWindowTime = 0x0000,
    .x6071_targetTorque = 0,
    .x6072_maxTorque = 0x0000,
    .x6073_maxCurrent = 0x0000,
    .x6074_torqueDemandValue = 0,
    .x6075_motorRatedCurrent = 0x00000000,
    .x6076_motorRatedTorque = 0x00000000,
    .x6077_torqueActualValue = 0,
    .x6078_currentActualValue = 0,
    .x6079_DC_LinkCircuitVoltage = 0x00000000,
    .x607B_positionRangeLimit_sub0 = 0x02,
    .x607B_positionRangeLimit = {-2147483648, 2147483647},
    .x607C_homeOffset = 0,
    .x607D_softwarePositionLimit_sub0 = 0x02,
    .x607D_softwarePositionLimit = {-2147483648, 2147483647},
    .x607E_polarity = 0x00,
    .x6082_endVelocity = 0x00000000,
    .x6086_motionProfileType = 0,
    .x6087_torqueSlope = 0x00000000,
    .x6088_torqueProfileType = 0,
    .x6089_positionNotationIndex = 0,
    .x608B_velocityNotationIndex = 0,
    .x608F_positionEncoderResolution_sub0 = 0x02,
    .x608F_positionEncoderResolution = {0x00000001, 0x00000001},
    .x6090_velocityEncoderResolution_sub0 = 0x02,
    .x6090_velocityEncoderResolution = {0x00000001, 0x00000001},
    .x6091_gearRatio_sub0 = 0x02,
    .x6091_gearRatio = {0x00000001, 0x00000001},
    .x6092_feedConstant_sub0 = 0x02,
    .x6092_feedConstant = {0x00000001, 0x00000001},
    .x6093_positionFactor_sub0 = 0x02,
    .x6093_positionFactor = {0x00000001, 0x00000001},
    .x6094_velocityEncoderFactor_sub0 = 0x02,
    .x6094_velocityEncoderFactor = {0x00000001, 0x00000001},
    .x6095_velocityFactor1_sub0 = 0x02,
    .x6095_velocityFactor1 = {0x00000001, 0x00000001},
    .x6096_velocityFactor2_sub0 = 0x02,
    .x6096_velocityFactor2 = {0x00000001, 0x00000001},
    .x6097_accelerationFactor_sub0 = 0x02,
    .x6097_accelerationFactor = {0x00000001, 0x00000001},
    .x6098_homingMethod = 0,
    .x6099_homingSpeeds_sub0 = 0x02,
    .x6099_homingSpeeds = {0x00000000, 0x00000000},
    .x60C0_interpolationSubModeSelect = 0,
    .x60C1_interpolationDataRecord_sub0 = 0x01,
    .x60C1_interpolationDataRecord = {0},
    .x60C2_interpolationTimePeriod = {
        .numberOfElements = 0x02,
        .interpolationTimeUnits = 0x01,
        .interpolationTimeIndex = -3
    },
    .x60C3_interpolationSyncDefinition_sub0 = 0x02,
    .x60C3_interpolationSyncDefinition = {0x00, 0x01},
    .x60C4_interpolationDataConfiguration = {
        .numberOfEntries = 0x06,
        .maximumBufferSize = 0x00000001,
        .actualBufferSize = 0x00000000,
        .bufferOrganization = 0x00,
        .bufferPosition = 0x0000,
        .sizeOfDataRecord = 0x01,
        .bufferClear = 0x00
    },
    .x60F6_torqueControlParameters = {
        .numberOfEntries = 0x01
    },
    .x60F7_powerStageParameters = {
        .numberOfEntries = 0x01,
        ._manufacturer_specific_ = 0x00
    },
    .x60F9_velocityControlParameterSet_sub0 = 0x02,
    .x60FD_digitalInputs = 0x00000000,
    .x60FE_digitalOutputs = {0x00000000, 0x00000000},
    .x6403_motorCatalogueNumber = {'0', 'x', '0', 0},
    .x6404_motorManufacturer = {'0', 'x', '0', 0},
    .x6405_httpMotorCatalogAddress = {'0', 'x', '0', 0},
    .x6505_httpDriveCatalogAddress = {'0', 'x', '0', 0}
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identityObject[5];
    OD_obj_record_t o_1400_receivePDO_CommunicationParameter1[3];
    OD_obj_record_t o_1401_receivePDO_CommunicationParameter2[3];
    OD_obj_record_t o_1600_receivePDO_MappingParameter1[9];
    OD_obj_record_t o_1601_receivePDO_MappingParameter2[9];
    OD_obj_record_t o_1800_transmitPDO_CommunicationParameter1[6];
    OD_obj_record_t o_1801_transmitPDO_CommunicationParameter2[6];
    OD_obj_record_t o_1A00_TPDO_MappingParameter1[9];
    OD_obj_record_t o_1A01_TPDO_MappingParameter2[9];
    OD_obj_var_t o_6007_abortConnectionOptionCode;
    OD_obj_var_t o_603F_errorCode;
    OD_obj_var_t o_6040_controlword;
    OD_obj_var_t o_6041_statusword;
    OD_obj_var_t o_6042_vlTargetVelocity;
    OD_obj_var_t o_6043_vlVelocityDemand;
    OD_obj_var_t o_6044_vlControlEffort;
    OD_obj_var_t o_6045_vlManipulatedVelocity;
    OD_obj_array_t o_6046_vlVelocityMinMaxAmount;
    OD_obj_array_t o_6047_vlVelocityMinMax;
    OD_obj_record_t o_6048_vlVelocityAcceleration[3];
    OD_obj_record_t o_6049_vlVelocityDeceleration[3];
    OD_obj_record_t o_604A_vlVelocityQuickStop[3];
    OD_obj_array_t o_604B_vlSetpointFactor;
    OD_obj_array_t o_604C_vlDimensionFactor;
    OD_obj_var_t o_604D_vlPoleNumber;
    OD_obj_var_t o_604E_vlVelocityReference;
    OD_obj_var_t o_604F_vlRampFunctionTime;
    OD_obj_var_t o_6050_vlSlowDownTime;
    OD_obj_var_t o_6051_vlQuickStopTime;
    OD_obj_var_t o_6052_vlNominalPercentage;
    OD_obj_var_t o_6053_vlPercentageDemand;
    OD_obj_var_t o_6054_vlActualPercentage;
    OD_obj_var_t o_6055_vlManipulatedPercentage;
    OD_obj_array_t o_6056_vlVelocityMotorMinMaxAmount;
    OD_obj_array_t o_6057_vlVelocityMotorMinMax;
    OD_obj_array_t o_6058_vlFrequencyMotorMinMaxAmount;
    OD_obj_array_t o_6059_vlFrequencyMotorMinMax;
    OD_obj_var_t o_605A_quickStopOptionCode;
    OD_obj_var_t o_605B_shutdownOptionCode;
    OD_obj_var_t o_605C_disableOperationOptionCode;
    OD_obj_var_t o_605D_haltOptionCode;
    OD_obj_var_t o_605E_faultReactionOptionCode;
    OD_obj_var_t o_6060_modesOfOperation;
    OD_obj_var_t o_6061_modesOfOperationDisplay;
    OD_obj_var_t o_6062_positionDemandValue;
    OD_obj_var_t o_6063_positionActualValue;
    OD_obj_var_t o_6064_positionActualValue;
    OD_obj_var_t o_6065_followingErrorWindow;
    OD_obj_var_t o_6066_followingErrorTimeOut;
    OD_obj_var_t o_6067_positionWindow;
    OD_obj_var_t o_6068_positionWindowTime;
    OD_obj_var_t o_6069_velocitySensorActualValue;
    OD_obj_var_t o_606A_sensorSelectionCode;
    OD_obj_var_t o_606B_velocityDemandValue;
    OD_obj_var_t o_606C_velocityActualValue;
    OD_obj_var_t o_606D_velocityWindow;
    OD_obj_var_t o_606E_velocityWindowTime;
    OD_obj_var_t o_606F_velocityThreshold;
    OD_obj_var_t o_6070_velocityThresholdTime;
    OD_obj_var_t o_6071_targetTorque;
    OD_obj_var_t o_6072_maxTorque;
    OD_obj_var_t o_6073_maxCurrent;
    OD_obj_var_t o_6074_torqueDemandValue;
    OD_obj_var_t o_6075_motorRatedCurrent;
    OD_obj_var_t o_6076_motorRatedTorque;
    OD_obj_var_t o_6077_torqueActualValue;
    OD_obj_var_t o_6078_currentActualValue;
    OD_obj_var_t o_6079_DC_LinkCircuitVoltage;
    OD_obj_var_t o_607A_targetPosition;
    OD_obj_array_t o_607B_positionRangeLimit;
    OD_obj_var_t o_607C_homeOffset;
    OD_obj_array_t o_607D_softwarePositionLimit;
    OD_obj_var_t o_607E_polarity;
    OD_obj_var_t o_607F_maxProfileVelocity;
    OD_obj_var_t o_6080_maxMotorSpeed;
    OD_obj_var_t o_6081_profileVelocityInPp_mode;
    OD_obj_var_t o_6082_endVelocity;
    OD_obj_var_t o_6083_profileAcceleration;
    OD_obj_var_t o_6084_profileDeceleration;
    OD_obj_var_t o_6085_quickStopDeceleration;
    OD_obj_var_t o_6086_motionProfileType;
    OD_obj_var_t o_6087_torqueSlope;
    OD_obj_var_t o_6088_torqueProfileType;
    OD_obj_var_t o_6089_positionNotationIndex;
    OD_obj_var_t o_608A_positionDimensionIndex;
    OD_obj_var_t o_608B_velocityNotationIndex;
    OD_obj_var_t o_608C_velocityDimensionIndex;
    OD_obj_var_t o_608D_accelerationNotationIndex;
    OD_obj_var_t o_608E_accelerationDimensionIndex;
    OD_obj_array_t o_608F_positionEncoderResolution;
    OD_obj_array_t o_6090_velocityEncoderResolution;
    OD_obj_array_t o_6091_gearRatio;
    OD_obj_array_t o_6092_feedConstant;
    OD_obj_array_t o_6093_positionFactor;
    OD_obj_array_t o_6094_velocityEncoderFactor;
    OD_obj_array_t o_6095_velocityFactor1;
    OD_obj_array_t o_6096_velocityFactor2;
    OD_obj_array_t o_6097_accelerationFactor;
    OD_obj_var_t o_6098_homingMethod;
    OD_obj_array_t o_6099_homingSpeeds;
    OD_obj_var_t o_609A_homingAcceleration;
    OD_obj_var_t o_60C0_interpolationSubModeSelect;
    OD_obj_array_t o_60C1_interpolationDataRecord;
    OD_obj_record_t o_60C2_interpolationTimePeriod[3];
    OD_obj_array_t o_60C3_interpolationSyncDefinition;
    OD_obj_record_t o_60C4_interpolationDataConfiguration[7];
    OD_obj_var_t o_60C5_maxAcceleration;
    OD_obj_var_t o_60C6_maxDeceleration;
    OD_obj_var_t o_60F4_followingErrorActualValue;
    OD_obj_record_t o_60F6_torqueControlParameters[2];
    OD_obj_record_t o_60F7_powerStageParameters[2];
    OD_obj_var_t o_60F8_maxSlippage;
    OD_obj_array_t o_60F9_velocityControlParameterSet;
    OD_obj_var_t o_60FA_controlEffort;
    OD_obj_record_t o_60FB_positionControlParameterSet[2];
    OD_obj_var_t o_60FC_positionDemandValue;
    OD_obj_var_t o_60FD_digitalInputs;
    OD_obj_array_t o_60FE_digitalOutputs;
    OD_obj_var_t o_60FF_targetVelocity;
    OD_obj_var_t o_6402_motorType;
    OD_obj_var_t o_6403_motorCatalogueNumber;
    OD_obj_var_t o_6404_motorManufacturer;
    OD_obj_var_t o_6405_httpMotorCatalogAddress;
    OD_obj_var_t o_6407_motorServicePeriod;
    OD_obj_record_t o_6410_motorData[2];
    OD_obj_var_t o_6502_supportedDriveModes;
    OD_obj_var_t o_6503_driveCatalogNumber;
    OD_obj_var_t o_6504_driveManufacturer;
    OD_obj_var_t o_6505_httpDriveCatalogAddress;
    OD_obj_record_t o_6510_driveData[2];
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_RAM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_RAM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identityObject = {
        {
            .dataOrig = &OD_RAM.x1018_identityObject.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_receivePDO_CommunicationParameter1 = {
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1401_receivePDO_CommunicationParameter2 = {
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_receivePDO_MappingParameter1 = {
        {
            .dataOrig = &OD_RAM.x1600_receivePDO_MappingParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_receivePDO_MappingParameter2 = {
        {
            .dataOrig = &OD_RAM.x1601_receivePDO_MappingParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_transmitPDO_CommunicationParameter1 = {
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1801_transmitPDO_CommunicationParameter2 = {
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1A00_TPDO_MappingParameter1 = {
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDO_MappingParameter2 = {
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_6007_abortConnectionOptionCode = {
        .dataOrig = &OD_RAM.x6007_abortConnectionOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_603F_errorCode = {
        .dataOrig = &OD_RAM.x603F_errorCode,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6040_controlword = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_statusword = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6042_vlTargetVelocity = {
        .dataOrig = &OD_RAM.x6042_vlTargetVelocity,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6043_vlVelocityDemand = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6044_vlControlEffort = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6045_vlManipulatedVelocity = {
        .dataOrig = &OD_RAM.x6045_vlManipulatedVelocity,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6046_vlVelocityMinMaxAmount = {
        .dataOrig0 = &OD_RAM.x6046_vlVelocityMinMaxAmount_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6047_vlVelocityMinMax = {
        .dataOrig0 = &OD_RAM.x6047_vlVelocityMinMax_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6048_vlVelocityAcceleration = {
        {
            .dataOrig = &OD_RAM.x6048_vlVelocityAcceleration.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_6049_vlVelocityDeceleration = {
        {
            .dataOrig = &OD_RAM.x6049_vlVelocityDeceleration.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_604A_vlVelocityQuickStop = {
        {
            .dataOrig = &OD_RAM.x604A_vlVelocityQuickStop.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x604A_vlVelocityQuickStop.deltaTime,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_604B_vlSetpointFactor = {
        .dataOrig0 = &OD_RAM.x604B_vlSetpointFactor_sub0,
        .dataOrig = &OD_RAM.x604B_vlSetpointFactor[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_604C_vlDimensionFactor = {
        .dataOrig0 = &OD_RAM.x604C_vlDimensionFactor_sub0,
        .dataOrig = &OD_RAM.x604C_vlDimensionFactor[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_604D_vlPoleNumber = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_604E_vlVelocityReference = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_604F_vlRampFunctionTime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6050_vlSlowDownTime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6051_vlQuickStopTime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6052_vlNominalPercentage = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6053_vlPercentageDemand = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6054_vlActualPercentage = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6055_vlManipulatedPercentage = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6056_vlVelocityMotorMinMaxAmount = {
        .dataOrig0 = &OD_RAM.x6056_vlVelocityMotorMinMaxAmount_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6057_vlVelocityMotorMinMax = {
        .dataOrig0 = &OD_RAM.x6057_vlVelocityMotorMinMax_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6058_vlFrequencyMotorMinMaxAmount = {
        .dataOrig0 = &OD_RAM.x6058_vlFrequencyMotorMinMaxAmount_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6059_vlFrequencyMotorMinMax = {
        .dataOrig0 = &OD_RAM.x6059_vlFrequencyMotorMinMax_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_605A_quickStopOptionCode = {
        .dataOrig = &OD_RAM.x605A_quickStopOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_605B_shutdownOptionCode = {
        .dataOrig = &OD_RAM.x605B_shutdownOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_605C_disableOperationOptionCode = {
        .dataOrig = &OD_RAM.x605C_disableOperationOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_605D_haltOptionCode = {
        .dataOrig = &OD_RAM.x605D_haltOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_605E_faultReactionOptionCode = {
        .dataOrig = &OD_RAM.x605E_faultReactionOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6060_modesOfOperation = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_W,
        .dataLength = 1
    },
    .o_6061_modesOfOperationDisplay = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_6062_positionDemandValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6063_positionActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6064_positionActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6065_followingErrorWindow = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6066_followingErrorTimeOut = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6067_positionWindow = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6068_positionWindowTime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6069_velocitySensorActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_606A_sensorSelectionCode = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_606B_velocityDemandValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_606C_velocityActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606D_velocityWindow = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_606E_velocityWindowTime = {
        .dataOrig = &OD_RAM.x606E_velocityWindowTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_606F_velocityThreshold = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6070_velocityThresholdTime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6071_targetTorque = {
        .dataOrig = &OD_RAM.x6071_targetTorque,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6072_maxTorque = {
        .dataOrig = &OD_RAM.x6072_maxTorque,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6073_maxCurrent = {
        .dataOrig = &OD_RAM.x6073_maxCurrent,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6074_torqueDemandValue = {
        .dataOrig = &OD_RAM.x6074_torqueDemandValue,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6075_motorRatedCurrent = {
        .dataOrig = &OD_RAM.x6075_motorRatedCurrent,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6076_motorRatedTorque = {
        .dataOrig = &OD_RAM.x6076_motorRatedTorque,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6077_torqueActualValue = {
        .dataOrig = &OD_RAM.x6077_torqueActualValue,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6078_currentActualValue = {
        .dataOrig = &OD_RAM.x6078_currentActualValue,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6079_DC_LinkCircuitVoltage = {
        .dataOrig = &OD_RAM.x6079_DC_LinkCircuitVoltage,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_607A_targetPosition = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607B_positionRangeLimit = {
        .dataOrig0 = &OD_RAM.x607B_positionRangeLimit_sub0,
        .dataOrig = &OD_RAM.x607B_positionRangeLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_607C_homeOffset = {
        .dataOrig = &OD_RAM.x607C_homeOffset,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_607D_softwarePositionLimit = {
        .dataOrig0 = &OD_RAM.x607D_softwarePositionLimit_sub0,
        .dataOrig = &OD_RAM.x607D_softwarePositionLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_607E_polarity = {
        .dataOrig = &OD_RAM.x607E_polarity,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_607F_maxProfileVelocity = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6080_maxMotorSpeed = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6081_profileVelocityInPp_mode = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6082_endVelocity = {
        .dataOrig = &OD_RAM.x6082_endVelocity,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6083_profileAcceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6084_profileDeceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6085_quickStopDeceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6086_motionProfileType = {
        .dataOrig = &OD_RAM.x6086_motionProfileType,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6087_torqueSlope = {
        .dataOrig = &OD_RAM.x6087_torqueSlope,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6088_torqueProfileType = {
        .dataOrig = &OD_RAM.x6088_torqueProfileType,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6089_positionNotationIndex = {
        .dataOrig = &OD_RAM.x6089_positionNotationIndex,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_608A_positionDimensionIndex = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_608B_velocityNotationIndex = {
        .dataOrig = &OD_RAM.x608B_velocityNotationIndex,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_608C_velocityDimensionIndex = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_608D_accelerationNotationIndex = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_608E_accelerationDimensionIndex = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_608F_positionEncoderResolution = {
        .dataOrig0 = &OD_RAM.x608F_positionEncoderResolution_sub0,
        .dataOrig = &OD_RAM.x608F_positionEncoderResolution[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6090_velocityEncoderResolution = {
        .dataOrig0 = &OD_RAM.x6090_velocityEncoderResolution_sub0,
        .dataOrig = &OD_RAM.x6090_velocityEncoderResolution[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6091_gearRatio = {
        .dataOrig0 = &OD_RAM.x6091_gearRatio_sub0,
        .dataOrig = &OD_RAM.x6091_gearRatio[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6092_feedConstant = {
        .dataOrig0 = &OD_RAM.x6092_feedConstant_sub0,
        .dataOrig = &OD_RAM.x6092_feedConstant[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6093_positionFactor = {
        .dataOrig0 = &OD_RAM.x6093_positionFactor_sub0,
        .dataOrig = &OD_RAM.x6093_positionFactor[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6094_velocityEncoderFactor = {
        .dataOrig0 = &OD_RAM.x6094_velocityEncoderFactor_sub0,
        .dataOrig = &OD_RAM.x6094_velocityEncoderFactor[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6095_velocityFactor1 = {
        .dataOrig0 = &OD_RAM.x6095_velocityFactor1_sub0,
        .dataOrig = &OD_RAM.x6095_velocityFactor1[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6096_velocityFactor2 = {
        .dataOrig0 = &OD_RAM.x6096_velocityFactor2_sub0,
        .dataOrig = &OD_RAM.x6096_velocityFactor2[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6097_accelerationFactor = {
        .dataOrig0 = &OD_RAM.x6097_accelerationFactor_sub0,
        .dataOrig = &OD_RAM.x6097_accelerationFactor[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6098_homingMethod = {
        .dataOrig = &OD_RAM.x6098_homingMethod,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6099_homingSpeeds = {
        .dataOrig0 = &OD_RAM.x6099_homingSpeeds_sub0,
        .dataOrig = &OD_RAM.x6099_homingSpeeds[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_609A_homingAcceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_60C0_interpolationSubModeSelect = {
        .dataOrig = &OD_RAM.x60C0_interpolationSubModeSelect,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_60C1_interpolationDataRecord = {
        .dataOrig0 = &OD_RAM.x60C1_interpolationDataRecord_sub0,
        .dataOrig = &OD_RAM.x60C1_interpolationDataRecord[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_60C2_interpolationTimePeriod = {
        {
            .dataOrig = &OD_RAM.x60C2_interpolationTimePeriod.numberOfElements,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C2_interpolationTimePeriod.interpolationTimeUnits,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C2_interpolationTimePeriod.interpolationTimeIndex,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_60C3_interpolationSyncDefinition = {
        .dataOrig0 = &OD_RAM.x60C3_interpolationSyncDefinition_sub0,
        .dataOrig = &OD_RAM.x60C3_interpolationSyncDefinition[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_60C4_interpolationDataConfiguration = {
        {
            .dataOrig = &OD_RAM.x60C4_interpolationDataConfiguration.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolationDataConfiguration.maximumBufferSize,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolationDataConfiguration.actualBufferSize,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolationDataConfiguration.bufferOrganization,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolationDataConfiguration.bufferPosition,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolationDataConfiguration.sizeOfDataRecord,
            .subIndex = 5,
            .attribute = ODA_SDO_W,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60C4_interpolationDataConfiguration.bufferClear,
            .subIndex = 6,
            .attribute = ODA_SDO_W,
            .dataLength = 1
        }
    },
    .o_60C5_maxAcceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_60C6_maxDeceleration = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_60F4_followingErrorActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_60F6_torqueControlParameters = {
        {
            .dataOrig = &OD_RAM.x60F6_torqueControlParameters.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_60F7_powerStageParameters = {
        {
            .dataOrig = &OD_RAM.x60F7_powerStageParameters.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x60F7_powerStageParameters._manufacturer_specific_,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_60F8_maxSlippage = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_60F9_velocityControlParameterSet = {
        .dataOrig0 = &OD_RAM.x60F9_velocityControlParameterSet_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_60FA_controlEffort = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_60FB_positionControlParameterSet = {
        {
            .dataOrig = NULL,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_60FC_positionDemandValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_60FD_digitalInputs = {
        .dataOrig = &OD_RAM.x60FD_digitalInputs,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60FE_digitalOutputs = {
        .dataOrig0 = NULL,
        .dataOrig = &OD_RAM.x60FE_digitalOutputs[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_60FF_targetVelocity = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6402_motorType = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6403_motorCatalogueNumber = {
        .dataOrig = &OD_RAM.x6403_motorCatalogueNumber[0],
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 3
    },
    .o_6404_motorManufacturer = {
        .dataOrig = &OD_RAM.x6404_motorManufacturer[0],
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 3
    },
    .o_6405_httpMotorCatalogAddress = {
        .dataOrig = &OD_RAM.x6405_httpMotorCatalogAddress[0],
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 3
    },
    .o_6407_motorServicePeriod = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6410_motorData = {
        {
            .dataOrig = NULL,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_6502_supportedDriveModes = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6503_driveCatalogNumber = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 0
    },
    .o_6504_driveManufacturer = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 0
    },
    .o_6505_httpDriveCatalogAddress = {
        .dataOrig = &OD_RAM.x6505_httpDriveCatalogAddress[0],
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 3
    },
    .o_6510_driveData = {
        {
            .dataOrig = NULL,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identityObject, NULL},
    {0x1400, 0x03, ODT_REC, &ODObjs.o_1400_receivePDO_CommunicationParameter1, NULL},
    {0x1401, 0x03, ODT_REC, &ODObjs.o_1401_receivePDO_CommunicationParameter2, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_receivePDO_MappingParameter1, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_receivePDO_MappingParameter2, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_transmitPDO_CommunicationParameter1, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_transmitPDO_CommunicationParameter2, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDO_MappingParameter1, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDO_MappingParameter2, NULL},
    {0x6007, 0x01, ODT_VAR, &ODObjs.o_6007_abortConnectionOptionCode, NULL},
    {0x603F, 0x01, ODT_VAR, &ODObjs.o_603F_errorCode, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_controlword, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_statusword, NULL},
    {0x6042, 0x01, ODT_VAR, &ODObjs.o_6042_vlTargetVelocity, NULL},
    {0x6043, 0x01, ODT_VAR, &ODObjs.o_6043_vlVelocityDemand, NULL},
    {0x6044, 0x01, ODT_VAR, &ODObjs.o_6044_vlControlEffort, NULL},
    {0x6045, 0x01, ODT_VAR, &ODObjs.o_6045_vlManipulatedVelocity, NULL},
    {0x6046, 0x03, ODT_ARR, &ODObjs.o_6046_vlVelocityMinMaxAmount, NULL},
    {0x6047, 0x05, ODT_ARR, &ODObjs.o_6047_vlVelocityMinMax, NULL},
    {0x6048, 0x03, ODT_REC, &ODObjs.o_6048_vlVelocityAcceleration, NULL},
    {0x6049, 0x03, ODT_REC, &ODObjs.o_6049_vlVelocityDeceleration, NULL},
    {0x604A, 0x03, ODT_REC, &ODObjs.o_604A_vlVelocityQuickStop, NULL},
    {0x604B, 0x03, ODT_ARR, &ODObjs.o_604B_vlSetpointFactor, NULL},
    {0x604C, 0x03, ODT_ARR, &ODObjs.o_604C_vlDimensionFactor, NULL},
    {0x604D, 0x01, ODT_VAR, &ODObjs.o_604D_vlPoleNumber, NULL},
    {0x604E, 0x01, ODT_VAR, &ODObjs.o_604E_vlVelocityReference, NULL},
    {0x604F, 0x01, ODT_VAR, &ODObjs.o_604F_vlRampFunctionTime, NULL},
    {0x6050, 0x01, ODT_VAR, &ODObjs.o_6050_vlSlowDownTime, NULL},
    {0x6051, 0x01, ODT_VAR, &ODObjs.o_6051_vlQuickStopTime, NULL},
    {0x6052, 0x01, ODT_VAR, &ODObjs.o_6052_vlNominalPercentage, NULL},
    {0x6053, 0x01, ODT_VAR, &ODObjs.o_6053_vlPercentageDemand, NULL},
    {0x6054, 0x01, ODT_VAR, &ODObjs.o_6054_vlActualPercentage, NULL},
    {0x6055, 0x01, ODT_VAR, &ODObjs.o_6055_vlManipulatedPercentage, NULL},
    {0x6056, 0x03, ODT_ARR, &ODObjs.o_6056_vlVelocityMotorMinMaxAmount, NULL},
    {0x6057, 0x05, ODT_ARR, &ODObjs.o_6057_vlVelocityMotorMinMax, NULL},
    {0x6058, 0x03, ODT_ARR, &ODObjs.o_6058_vlFrequencyMotorMinMaxAmount, NULL},
    {0x6059, 0x05, ODT_ARR, &ODObjs.o_6059_vlFrequencyMotorMinMax, NULL},
    {0x605A, 0x01, ODT_VAR, &ODObjs.o_605A_quickStopOptionCode, NULL},
    {0x605B, 0x01, ODT_VAR, &ODObjs.o_605B_shutdownOptionCode, NULL},
    {0x605C, 0x01, ODT_VAR, &ODObjs.o_605C_disableOperationOptionCode, NULL},
    {0x605D, 0x01, ODT_VAR, &ODObjs.o_605D_haltOptionCode, NULL},
    {0x605E, 0x01, ODT_VAR, &ODObjs.o_605E_faultReactionOptionCode, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_modesOfOperation, NULL},
    {0x6061, 0x01, ODT_VAR, &ODObjs.o_6061_modesOfOperationDisplay, NULL},
    {0x6062, 0x01, ODT_VAR, &ODObjs.o_6062_positionDemandValue, NULL},
    {0x6063, 0x01, ODT_VAR, &ODObjs.o_6063_positionActualValue, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_positionActualValue, NULL},
    {0x6065, 0x01, ODT_VAR, &ODObjs.o_6065_followingErrorWindow, NULL},
    {0x6066, 0x01, ODT_VAR, &ODObjs.o_6066_followingErrorTimeOut, NULL},
    {0x6067, 0x01, ODT_VAR, &ODObjs.o_6067_positionWindow, NULL},
    {0x6068, 0x01, ODT_VAR, &ODObjs.o_6068_positionWindowTime, NULL},
    {0x6069, 0x01, ODT_VAR, &ODObjs.o_6069_velocitySensorActualValue, NULL},
    {0x606A, 0x01, ODT_VAR, &ODObjs.o_606A_sensorSelectionCode, NULL},
    {0x606B, 0x01, ODT_VAR, &ODObjs.o_606B_velocityDemandValue, NULL},
    {0x606C, 0x01, ODT_VAR, &ODObjs.o_606C_velocityActualValue, NULL},
    {0x606D, 0x01, ODT_VAR, &ODObjs.o_606D_velocityWindow, NULL},
    {0x606E, 0x01, ODT_VAR, &ODObjs.o_606E_velocityWindowTime, NULL},
    {0x606F, 0x01, ODT_VAR, &ODObjs.o_606F_velocityThreshold, NULL},
    {0x6070, 0x01, ODT_VAR, &ODObjs.o_6070_velocityThresholdTime, NULL},
    {0x6071, 0x01, ODT_VAR, &ODObjs.o_6071_targetTorque, NULL},
    {0x6072, 0x01, ODT_VAR, &ODObjs.o_6072_maxTorque, NULL},
    {0x6073, 0x01, ODT_VAR, &ODObjs.o_6073_maxCurrent, NULL},
    {0x6074, 0x01, ODT_VAR, &ODObjs.o_6074_torqueDemandValue, NULL},
    {0x6075, 0x01, ODT_VAR, &ODObjs.o_6075_motorRatedCurrent, NULL},
    {0x6076, 0x01, ODT_VAR, &ODObjs.o_6076_motorRatedTorque, NULL},
    {0x6077, 0x01, ODT_VAR, &ODObjs.o_6077_torqueActualValue, NULL},
    {0x6078, 0x01, ODT_VAR, &ODObjs.o_6078_currentActualValue, NULL},
    {0x6079, 0x01, ODT_VAR, &ODObjs.o_6079_DC_LinkCircuitVoltage, NULL},
    {0x607A, 0x01, ODT_VAR, &ODObjs.o_607A_targetPosition, NULL},
    {0x607B, 0x03, ODT_ARR, &ODObjs.o_607B_positionRangeLimit, NULL},
    {0x607C, 0x01, ODT_VAR, &ODObjs.o_607C_homeOffset, NULL},
    {0x607D, 0x03, ODT_ARR, &ODObjs.o_607D_softwarePositionLimit, NULL},
    {0x607E, 0x01, ODT_VAR, &ODObjs.o_607E_polarity, NULL},
    {0x607F, 0x01, ODT_VAR, &ODObjs.o_607F_maxProfileVelocity, NULL},
    {0x6080, 0x01, ODT_VAR, &ODObjs.o_6080_maxMotorSpeed, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_profileVelocityInPp_mode, NULL},
    {0x6082, 0x01, ODT_VAR, &ODObjs.o_6082_endVelocity, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_profileAcceleration, NULL},
    {0x6084, 0x01, ODT_VAR, &ODObjs.o_6084_profileDeceleration, NULL},
    {0x6085, 0x01, ODT_VAR, &ODObjs.o_6085_quickStopDeceleration, NULL},
    {0x6086, 0x01, ODT_VAR, &ODObjs.o_6086_motionProfileType, NULL},
    {0x6087, 0x01, ODT_VAR, &ODObjs.o_6087_torqueSlope, NULL},
    {0x6088, 0x01, ODT_VAR, &ODObjs.o_6088_torqueProfileType, NULL},
    {0x6089, 0x01, ODT_VAR, &ODObjs.o_6089_positionNotationIndex, NULL},
    {0x608A, 0x01, ODT_VAR, &ODObjs.o_608A_positionDimensionIndex, NULL},
    {0x608B, 0x01, ODT_VAR, &ODObjs.o_608B_velocityNotationIndex, NULL},
    {0x608C, 0x01, ODT_VAR, &ODObjs.o_608C_velocityDimensionIndex, NULL},
    {0x608D, 0x01, ODT_VAR, &ODObjs.o_608D_accelerationNotationIndex, NULL},
    {0x608E, 0x01, ODT_VAR, &ODObjs.o_608E_accelerationDimensionIndex, NULL},
    {0x608F, 0x03, ODT_ARR, &ODObjs.o_608F_positionEncoderResolution, NULL},
    {0x6090, 0x03, ODT_ARR, &ODObjs.o_6090_velocityEncoderResolution, NULL},
    {0x6091, 0x03, ODT_ARR, &ODObjs.o_6091_gearRatio, NULL},
    {0x6092, 0x03, ODT_ARR, &ODObjs.o_6092_feedConstant, NULL},
    {0x6093, 0x03, ODT_ARR, &ODObjs.o_6093_positionFactor, NULL},
    {0x6094, 0x03, ODT_ARR, &ODObjs.o_6094_velocityEncoderFactor, NULL},
    {0x6095, 0x03, ODT_ARR, &ODObjs.o_6095_velocityFactor1, NULL},
    {0x6096, 0x03, ODT_ARR, &ODObjs.o_6096_velocityFactor2, NULL},
    {0x6097, 0x03, ODT_ARR, &ODObjs.o_6097_accelerationFactor, NULL},
    {0x6098, 0x01, ODT_VAR, &ODObjs.o_6098_homingMethod, NULL},
    {0x6099, 0x03, ODT_ARR, &ODObjs.o_6099_homingSpeeds, NULL},
    {0x609A, 0x01, ODT_VAR, &ODObjs.o_609A_homingAcceleration, NULL},
    {0x60C0, 0x01, ODT_VAR, &ODObjs.o_60C0_interpolationSubModeSelect, NULL},
    {0x60C1, 0x02, ODT_ARR, &ODObjs.o_60C1_interpolationDataRecord, NULL},
    {0x60C2, 0x03, ODT_REC, &ODObjs.o_60C2_interpolationTimePeriod, NULL},
    {0x60C3, 0x03, ODT_ARR, &ODObjs.o_60C3_interpolationSyncDefinition, NULL},
    {0x60C4, 0x07, ODT_REC, &ODObjs.o_60C4_interpolationDataConfiguration, NULL},
    {0x60C5, 0x01, ODT_VAR, &ODObjs.o_60C5_maxAcceleration, NULL},
    {0x60C6, 0x01, ODT_VAR, &ODObjs.o_60C6_maxDeceleration, NULL},
    {0x60F4, 0x01, ODT_VAR, &ODObjs.o_60F4_followingErrorActualValue, NULL},
    {0x60F6, 0x02, ODT_REC, &ODObjs.o_60F6_torqueControlParameters, NULL},
    {0x60F7, 0x02, ODT_REC, &ODObjs.o_60F7_powerStageParameters, NULL},
    {0x60F8, 0x01, ODT_VAR, &ODObjs.o_60F8_maxSlippage, NULL},
    {0x60F9, 0x03, ODT_ARR, &ODObjs.o_60F9_velocityControlParameterSet, NULL},
    {0x60FA, 0x01, ODT_VAR, &ODObjs.o_60FA_controlEffort, NULL},
    {0x60FB, 0x02, ODT_REC, &ODObjs.o_60FB_positionControlParameterSet, NULL},
    {0x60FC, 0x01, ODT_VAR, &ODObjs.o_60FC_positionDemandValue, NULL},
    {0x60FD, 0x01, ODT_VAR, &ODObjs.o_60FD_digitalInputs, NULL},
    {0x60FE, 0x03, ODT_ARR, &ODObjs.o_60FE_digitalOutputs, NULL},
    {0x60FF, 0x01, ODT_VAR, &ODObjs.o_60FF_targetVelocity, NULL},
    {0x6402, 0x01, ODT_VAR, &ODObjs.o_6402_motorType, NULL},
    {0x6403, 0x01, ODT_VAR, &ODObjs.o_6403_motorCatalogueNumber, NULL},
    {0x6404, 0x01, ODT_VAR, &ODObjs.o_6404_motorManufacturer, NULL},
    {0x6405, 0x01, ODT_VAR, &ODObjs.o_6405_httpMotorCatalogAddress, NULL},
    {0x6407, 0x01, ODT_VAR, &ODObjs.o_6407_motorServicePeriod, NULL},
    {0x6410, 0x02, ODT_REC, &ODObjs.o_6410_motorData, NULL},
    {0x6502, 0x01, ODT_VAR, &ODObjs.o_6502_supportedDriveModes, NULL},
    {0x6503, 0x01, ODT_VAR, &ODObjs.o_6503_driveCatalogNumber, NULL},
    {0x6504, 0x01, ODT_VAR, &ODObjs.o_6504_driveManufacturer, NULL},
    {0x6505, 0x01, ODT_VAR, &ODObjs.o_6505_httpDriveCatalogAddress, NULL},
    {0x6510, 0x02, ODT_REC, &ODObjs.o_6510_driveData, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
