/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: cia_402_profile.eds
        File Version: 1

        Created:      0001/1/1 0:00:00
        Created By:   none
        Modified:     0001/1/1 0:00:00
        Modified By:  none

    Device Info:
        Vendor Name:  
        Vendor ID:    0x0
        Product Name: sample device according to CiA 402
        Product ID:   0x0

        Description:  sample CiA 402 device
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_6046 2
#define OD_CNT_ARR_6047 4
#define OD_CNT_ARR_604B 2
#define OD_CNT_ARR_604C 2
#define OD_CNT_ARR_6056 2
#define OD_CNT_ARR_6057 4
#define OD_CNT_ARR_6058 2
#define OD_CNT_ARR_6059 4
#define OD_CNT_ARR_607B 2
#define OD_CNT_ARR_607D 2
#define OD_CNT_ARR_608F 2
#define OD_CNT_ARR_6090 2
#define OD_CNT_ARR_6091 2
#define OD_CNT_ARR_6092 2
#define OD_CNT_ARR_6093 2
#define OD_CNT_ARR_6094 2
#define OD_CNT_ARR_6095 2
#define OD_CNT_ARR_6096 2
#define OD_CNT_ARR_6097 2
#define OD_CNT_ARR_6099 2
#define OD_CNT_ARR_60C1 1
#define OD_CNT_ARR_60C3 2
#define OD_CNT_ARR_60F9 2
#define OD_CNT_ARR_60FE 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
    } x1018_identityObject;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
    } x1400_receivePDO_CommunicationParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
    } x1401_receivePDO_CommunicationParameter2;
    struct {
        uint8_t numberOfEntries;
    } x1600_receivePDO_MappingParameter1;
    struct {
        uint8_t numberOfEntries;
    } x1601_receivePDO_MappingParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1800_transmitPDO_CommunicationParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1801_transmitPDO_CommunicationParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t mappingEntry1;
        uint32_t mappingEntry2;
        uint32_t mappingEntry3;
        uint32_t mappingEntry4;
        uint32_t mappingEntry5;
        uint32_t mappingEntry6;
        uint32_t mappingEntry7;
        uint32_t mappingEntry8;
    } x1A00_TPDO_MappingParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t mappingEntry1;
        uint32_t mappingEntry2;
        uint32_t mappingEntry3;
        uint32_t mappingEntry4;
        uint32_t mappingEntry5;
        uint32_t mappingEntry6;
        uint32_t mappingEntry7;
        uint32_t mappingEntry8;
    } x1A01_TPDO_MappingParameter2;
    int16_t x6007_abortConnectionOptionCode;
    uint16_t x603F_errorCode;
    int16_t x6042_vlTargetVelocity;
    int16_t x6045_vlManipulatedVelocity;
    uint8_t x6046_vlVelocityMinMaxAmount_sub0;
    uint8_t x6047_vlVelocityMinMax_sub0;
    struct {
        uint8_t numberOfEntries;
    } x6048_vlVelocityAcceleration;
    struct {
        uint8_t numberOfEntries;
    } x6049_vlVelocityDeceleration;
    struct {
        uint8_t numberOfEntries;
        uint16_t deltaTime;
    } x604A_vlVelocityQuickStop;
    uint8_t x604B_vlSetpointFactor_sub0;
    int16_t x604B_vlSetpointFactor[OD_CNT_ARR_604B];
    uint8_t x604C_vlDimensionFactor_sub0;
    int32_t x604C_vlDimensionFactor[OD_CNT_ARR_604C];
    uint8_t x6056_vlVelocityMotorMinMaxAmount_sub0;
    uint8_t x6057_vlVelocityMotorMinMax_sub0;
    uint8_t x6058_vlFrequencyMotorMinMaxAmount_sub0;
    uint8_t x6059_vlFrequencyMotorMinMax_sub0;
    int16_t x605A_quickStopOptionCode;
    int16_t x605B_shutdownOptionCode;
    int16_t x605C_disableOperationOptionCode;
    int16_t x605D_haltOptionCode;
    int16_t x605E_faultReactionOptionCode;
    uint16_t x606E_velocityWindowTime;
    int16_t x6071_targetTorque;
    uint16_t x6072_maxTorque;
    uint16_t x6073_maxCurrent;
    int16_t x6074_torqueDemandValue;
    uint32_t x6075_motorRatedCurrent;
    uint32_t x6076_motorRatedTorque;
    int16_t x6077_torqueActualValue;
    int16_t x6078_currentActualValue;
    uint32_t x6079_DC_LinkCircuitVoltage;
    uint8_t x607B_positionRangeLimit_sub0;
    int32_t x607B_positionRangeLimit[OD_CNT_ARR_607B];
    int32_t x607C_homeOffset;
    uint8_t x607D_softwarePositionLimit_sub0;
    int32_t x607D_softwarePositionLimit[OD_CNT_ARR_607D];
    uint8_t x607E_polarity;
    uint32_t x6082_endVelocity;
    int16_t x6086_motionProfileType;
    uint32_t x6087_torqueSlope;
    int16_t x6088_torqueProfileType;
    int8_t x6089_positionNotationIndex;
    int8_t x608B_velocityNotationIndex;
    uint8_t x608F_positionEncoderResolution_sub0;
    uint32_t x608F_positionEncoderResolution[OD_CNT_ARR_608F];
    uint8_t x6090_velocityEncoderResolution_sub0;
    uint32_t x6090_velocityEncoderResolution[OD_CNT_ARR_6090];
    uint8_t x6091_gearRatio_sub0;
    uint32_t x6091_gearRatio[OD_CNT_ARR_6091];
    uint8_t x6092_feedConstant_sub0;
    uint32_t x6092_feedConstant[OD_CNT_ARR_6092];
    uint8_t x6093_positionFactor_sub0;
    uint32_t x6093_positionFactor[OD_CNT_ARR_6093];
    uint8_t x6094_velocityEncoderFactor_sub0;
    uint32_t x6094_velocityEncoderFactor[OD_CNT_ARR_6094];
    uint8_t x6095_velocityFactor1_sub0;
    uint32_t x6095_velocityFactor1[OD_CNT_ARR_6095];
    uint8_t x6096_velocityFactor2_sub0;
    uint32_t x6096_velocityFactor2[OD_CNT_ARR_6096];
    uint8_t x6097_accelerationFactor_sub0;
    uint32_t x6097_accelerationFactor[OD_CNT_ARR_6097];
    int8_t x6098_homingMethod;
    uint8_t x6099_homingSpeeds_sub0;
    uint32_t x6099_homingSpeeds[OD_CNT_ARR_6099];
    int16_t x60C0_interpolationSubModeSelect;
    uint8_t x60C1_interpolationDataRecord_sub0;
    int32_t x60C1_interpolationDataRecord[OD_CNT_ARR_60C1];
    struct {
        uint8_t numberOfElements;
        uint8_t interpolationTimeUnits;
        int8_t interpolationTimeIndex;
    } x60C2_interpolationTimePeriod;
    uint8_t x60C3_interpolationSyncDefinition_sub0;
    uint8_t x60C3_interpolationSyncDefinition[OD_CNT_ARR_60C3];
    struct {
        uint8_t numberOfEntries;
        uint32_t maximumBufferSize;
        uint32_t actualBufferSize;
        uint8_t bufferOrganization;
        uint16_t bufferPosition;
        uint8_t sizeOfDataRecord;
        uint8_t bufferClear;
    } x60C4_interpolationDataConfiguration;
    struct {
        uint8_t numberOfEntries;
    } x60F6_torqueControlParameters;
    struct {
        uint8_t numberOfEntries;
        uint8_t _manufacturer_specific_;
    } x60F7_powerStageParameters;
    uint8_t x60F9_velocityControlParameterSet_sub0;
    uint32_t x60FD_digitalInputs;
    uint32_t x60FE_digitalOutputs[OD_CNT_ARR_60FE];
    char x6403_motorCatalogueNumber[4];
    char x6404_motorManufacturer[4];
    char x6405_httpMotorCatalogAddress[4];
    char x6505_httpDriveCatalogAddress[4];
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1008 &OD->list[2]
#define OD_ENTRY_H1009 &OD->list[3]
#define OD_ENTRY_H100A &OD->list[4]
#define OD_ENTRY_H1017 &OD->list[5]
#define OD_ENTRY_H1018 &OD->list[6]
#define OD_ENTRY_H1400 &OD->list[7]
#define OD_ENTRY_H1401 &OD->list[8]
#define OD_ENTRY_H1600 &OD->list[9]
#define OD_ENTRY_H1601 &OD->list[10]
#define OD_ENTRY_H1800 &OD->list[11]
#define OD_ENTRY_H1801 &OD->list[12]
#define OD_ENTRY_H1A00 &OD->list[13]
#define OD_ENTRY_H1A01 &OD->list[14]
#define OD_ENTRY_H6007 &OD->list[15]
#define OD_ENTRY_H603F &OD->list[16]
#define OD_ENTRY_H6040 &OD->list[17]
#define OD_ENTRY_H6041 &OD->list[18]
#define OD_ENTRY_H6042 &OD->list[19]
#define OD_ENTRY_H6043 &OD->list[20]
#define OD_ENTRY_H6044 &OD->list[21]
#define OD_ENTRY_H6045 &OD->list[22]
#define OD_ENTRY_H6046 &OD->list[23]
#define OD_ENTRY_H6047 &OD->list[24]
#define OD_ENTRY_H6048 &OD->list[25]
#define OD_ENTRY_H6049 &OD->list[26]
#define OD_ENTRY_H604A &OD->list[27]
#define OD_ENTRY_H604B &OD->list[28]
#define OD_ENTRY_H604C &OD->list[29]
#define OD_ENTRY_H604D &OD->list[30]
#define OD_ENTRY_H604E &OD->list[31]
#define OD_ENTRY_H604F &OD->list[32]
#define OD_ENTRY_H6050 &OD->list[33]
#define OD_ENTRY_H6051 &OD->list[34]
#define OD_ENTRY_H6052 &OD->list[35]
#define OD_ENTRY_H6053 &OD->list[36]
#define OD_ENTRY_H6054 &OD->list[37]
#define OD_ENTRY_H6055 &OD->list[38]
#define OD_ENTRY_H6056 &OD->list[39]
#define OD_ENTRY_H6057 &OD->list[40]
#define OD_ENTRY_H6058 &OD->list[41]
#define OD_ENTRY_H6059 &OD->list[42]
#define OD_ENTRY_H605A &OD->list[43]
#define OD_ENTRY_H605B &OD->list[44]
#define OD_ENTRY_H605C &OD->list[45]
#define OD_ENTRY_H605D &OD->list[46]
#define OD_ENTRY_H605E &OD->list[47]
#define OD_ENTRY_H6060 &OD->list[48]
#define OD_ENTRY_H6061 &OD->list[49]
#define OD_ENTRY_H6062 &OD->list[50]
#define OD_ENTRY_H6063 &OD->list[51]
#define OD_ENTRY_H6064 &OD->list[52]
#define OD_ENTRY_H6065 &OD->list[53]
#define OD_ENTRY_H6066 &OD->list[54]
#define OD_ENTRY_H6067 &OD->list[55]
#define OD_ENTRY_H6068 &OD->list[56]
#define OD_ENTRY_H6069 &OD->list[57]
#define OD_ENTRY_H606A &OD->list[58]
#define OD_ENTRY_H606B &OD->list[59]
#define OD_ENTRY_H606C &OD->list[60]
#define OD_ENTRY_H606D &OD->list[61]
#define OD_ENTRY_H606E &OD->list[62]
#define OD_ENTRY_H606F &OD->list[63]
#define OD_ENTRY_H6070 &OD->list[64]
#define OD_ENTRY_H6071 &OD->list[65]
#define OD_ENTRY_H6072 &OD->list[66]
#define OD_ENTRY_H6073 &OD->list[67]
#define OD_ENTRY_H6074 &OD->list[68]
#define OD_ENTRY_H6075 &OD->list[69]
#define OD_ENTRY_H6076 &OD->list[70]
#define OD_ENTRY_H6077 &OD->list[71]
#define OD_ENTRY_H6078 &OD->list[72]
#define OD_ENTRY_H6079 &OD->list[73]
#define OD_ENTRY_H607A &OD->list[74]
#define OD_ENTRY_H607B &OD->list[75]
#define OD_ENTRY_H607C &OD->list[76]
#define OD_ENTRY_H607D &OD->list[77]
#define OD_ENTRY_H607E &OD->list[78]
#define OD_ENTRY_H607F &OD->list[79]
#define OD_ENTRY_H6080 &OD->list[80]
#define OD_ENTRY_H6081 &OD->list[81]
#define OD_ENTRY_H6082 &OD->list[82]
#define OD_ENTRY_H6083 &OD->list[83]
#define OD_ENTRY_H6084 &OD->list[84]
#define OD_ENTRY_H6085 &OD->list[85]
#define OD_ENTRY_H6086 &OD->list[86]
#define OD_ENTRY_H6087 &OD->list[87]
#define OD_ENTRY_H6088 &OD->list[88]
#define OD_ENTRY_H6089 &OD->list[89]
#define OD_ENTRY_H608A &OD->list[90]
#define OD_ENTRY_H608B &OD->list[91]
#define OD_ENTRY_H608C &OD->list[92]
#define OD_ENTRY_H608D &OD->list[93]
#define OD_ENTRY_H608E &OD->list[94]
#define OD_ENTRY_H608F &OD->list[95]
#define OD_ENTRY_H6090 &OD->list[96]
#define OD_ENTRY_H6091 &OD->list[97]
#define OD_ENTRY_H6092 &OD->list[98]
#define OD_ENTRY_H6093 &OD->list[99]
#define OD_ENTRY_H6094 &OD->list[100]
#define OD_ENTRY_H6095 &OD->list[101]
#define OD_ENTRY_H6096 &OD->list[102]
#define OD_ENTRY_H6097 &OD->list[103]
#define OD_ENTRY_H6098 &OD->list[104]
#define OD_ENTRY_H6099 &OD->list[105]
#define OD_ENTRY_H609A &OD->list[106]
#define OD_ENTRY_H60C0 &OD->list[107]
#define OD_ENTRY_H60C1 &OD->list[108]
#define OD_ENTRY_H60C2 &OD->list[109]
#define OD_ENTRY_H60C3 &OD->list[110]
#define OD_ENTRY_H60C4 &OD->list[111]
#define OD_ENTRY_H60C5 &OD->list[112]
#define OD_ENTRY_H60C6 &OD->list[113]
#define OD_ENTRY_H60F4 &OD->list[114]
#define OD_ENTRY_H60F6 &OD->list[115]
#define OD_ENTRY_H60F7 &OD->list[116]
#define OD_ENTRY_H60F8 &OD->list[117]
#define OD_ENTRY_H60F9 &OD->list[118]
#define OD_ENTRY_H60FA &OD->list[119]
#define OD_ENTRY_H60FB &OD->list[120]
#define OD_ENTRY_H60FC &OD->list[121]
#define OD_ENTRY_H60FD &OD->list[122]
#define OD_ENTRY_H60FE &OD->list[123]
#define OD_ENTRY_H60FF &OD->list[124]
#define OD_ENTRY_H6402 &OD->list[125]
#define OD_ENTRY_H6403 &OD->list[126]
#define OD_ENTRY_H6404 &OD->list[127]
#define OD_ENTRY_H6405 &OD->list[128]
#define OD_ENTRY_H6407 &OD->list[129]
#define OD_ENTRY_H6410 &OD->list[130]
#define OD_ENTRY_H6502 &OD->list[131]
#define OD_ENTRY_H6503 &OD->list[132]
#define OD_ENTRY_H6504 &OD->list[133]
#define OD_ENTRY_H6505 &OD->list[134]
#define OD_ENTRY_H6510 &OD->list[135]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[2]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[3]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[4]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[5]
#define OD_ENTRY_H1018_identityObject &OD->list[6]
#define OD_ENTRY_H1400_receivePDO_CommunicationParameter1 &OD->list[7]
#define OD_ENTRY_H1401_receivePDO_CommunicationParameter2 &OD->list[8]
#define OD_ENTRY_H1600_receivePDO_MappingParameter1 &OD->list[9]
#define OD_ENTRY_H1601_receivePDO_MappingParameter2 &OD->list[10]
#define OD_ENTRY_H1800_transmitPDO_CommunicationParameter1 &OD->list[11]
#define OD_ENTRY_H1801_transmitPDO_CommunicationParameter2 &OD->list[12]
#define OD_ENTRY_H1A00_TPDO_MappingParameter1 &OD->list[13]
#define OD_ENTRY_H1A01_TPDO_MappingParameter2 &OD->list[14]
#define OD_ENTRY_H6007_abortConnectionOptionCode &OD->list[15]
#define OD_ENTRY_H603F_errorCode &OD->list[16]
#define OD_ENTRY_H6040_controlword &OD->list[17]
#define OD_ENTRY_H6041_statusword &OD->list[18]
#define OD_ENTRY_H6042_vlTargetVelocity &OD->list[19]
#define OD_ENTRY_H6043_vlVelocityDemand &OD->list[20]
#define OD_ENTRY_H6044_vlControlEffort &OD->list[21]
#define OD_ENTRY_H6045_vlManipulatedVelocity &OD->list[22]
#define OD_ENTRY_H6046_vlVelocityMinMaxAmount &OD->list[23]
#define OD_ENTRY_H6047_vlVelocityMinMax &OD->list[24]
#define OD_ENTRY_H6048_vlVelocityAcceleration &OD->list[25]
#define OD_ENTRY_H6049_vlVelocityDeceleration &OD->list[26]
#define OD_ENTRY_H604A_vlVelocityQuickStop &OD->list[27]
#define OD_ENTRY_H604B_vlSetpointFactor &OD->list[28]
#define OD_ENTRY_H604C_vlDimensionFactor &OD->list[29]
#define OD_ENTRY_H604D_vlPoleNumber &OD->list[30]
#define OD_ENTRY_H604E_vlVelocityReference &OD->list[31]
#define OD_ENTRY_H604F_vlRampFunctionTime &OD->list[32]
#define OD_ENTRY_H6050_vlSlowDownTime &OD->list[33]
#define OD_ENTRY_H6051_vlQuickStopTime &OD->list[34]
#define OD_ENTRY_H6052_vlNominalPercentage &OD->list[35]
#define OD_ENTRY_H6053_vlPercentageDemand &OD->list[36]
#define OD_ENTRY_H6054_vlActualPercentage &OD->list[37]
#define OD_ENTRY_H6055_vlManipulatedPercentage &OD->list[38]
#define OD_ENTRY_H6056_vlVelocityMotorMinMaxAmount &OD->list[39]
#define OD_ENTRY_H6057_vlVelocityMotorMinMax &OD->list[40]
#define OD_ENTRY_H6058_vlFrequencyMotorMinMaxAmount &OD->list[41]
#define OD_ENTRY_H6059_vlFrequencyMotorMinMax &OD->list[42]
#define OD_ENTRY_H605A_quickStopOptionCode &OD->list[43]
#define OD_ENTRY_H605B_shutdownOptionCode &OD->list[44]
#define OD_ENTRY_H605C_disableOperationOptionCode &OD->list[45]
#define OD_ENTRY_H605D_haltOptionCode &OD->list[46]
#define OD_ENTRY_H605E_faultReactionOptionCode &OD->list[47]
#define OD_ENTRY_H6060_modesOfOperation &OD->list[48]
#define OD_ENTRY_H6061_modesOfOperationDisplay &OD->list[49]
#define OD_ENTRY_H6062_positionDemandValue &OD->list[50]
#define OD_ENTRY_H6063_positionActualValue &OD->list[51]
#define OD_ENTRY_H6064_positionActualValue &OD->list[52]
#define OD_ENTRY_H6065_followingErrorWindow &OD->list[53]
#define OD_ENTRY_H6066_followingErrorTimeOut &OD->list[54]
#define OD_ENTRY_H6067_positionWindow &OD->list[55]
#define OD_ENTRY_H6068_positionWindowTime &OD->list[56]
#define OD_ENTRY_H6069_velocitySensorActualValue &OD->list[57]
#define OD_ENTRY_H606A_sensorSelectionCode &OD->list[58]
#define OD_ENTRY_H606B_velocityDemandValue &OD->list[59]
#define OD_ENTRY_H606C_velocityActualValue &OD->list[60]
#define OD_ENTRY_H606D_velocityWindow &OD->list[61]
#define OD_ENTRY_H606E_velocityWindowTime &OD->list[62]
#define OD_ENTRY_H606F_velocityThreshold &OD->list[63]
#define OD_ENTRY_H6070_velocityThresholdTime &OD->list[64]
#define OD_ENTRY_H6071_targetTorque &OD->list[65]
#define OD_ENTRY_H6072_maxTorque &OD->list[66]
#define OD_ENTRY_H6073_maxCurrent &OD->list[67]
#define OD_ENTRY_H6074_torqueDemandValue &OD->list[68]
#define OD_ENTRY_H6075_motorRatedCurrent &OD->list[69]
#define OD_ENTRY_H6076_motorRatedTorque &OD->list[70]
#define OD_ENTRY_H6077_torqueActualValue &OD->list[71]
#define OD_ENTRY_H6078_currentActualValue &OD->list[72]
#define OD_ENTRY_H6079_DC_LinkCircuitVoltage &OD->list[73]
#define OD_ENTRY_H607A_targetPosition &OD->list[74]
#define OD_ENTRY_H607B_positionRangeLimit &OD->list[75]
#define OD_ENTRY_H607C_homeOffset &OD->list[76]
#define OD_ENTRY_H607D_softwarePositionLimit &OD->list[77]
#define OD_ENTRY_H607E_polarity &OD->list[78]
#define OD_ENTRY_H607F_maxProfileVelocity &OD->list[79]
#define OD_ENTRY_H6080_maxMotorSpeed &OD->list[80]
#define OD_ENTRY_H6081_profileVelocityInPp_mode &OD->list[81]
#define OD_ENTRY_H6082_endVelocity &OD->list[82]
#define OD_ENTRY_H6083_profileAcceleration &OD->list[83]
#define OD_ENTRY_H6084_profileDeceleration &OD->list[84]
#define OD_ENTRY_H6085_quickStopDeceleration &OD->list[85]
#define OD_ENTRY_H6086_motionProfileType &OD->list[86]
#define OD_ENTRY_H6087_torqueSlope &OD->list[87]
#define OD_ENTRY_H6088_torqueProfileType &OD->list[88]
#define OD_ENTRY_H6089_positionNotationIndex &OD->list[89]
#define OD_ENTRY_H608A_positionDimensionIndex &OD->list[90]
#define OD_ENTRY_H608B_velocityNotationIndex &OD->list[91]
#define OD_ENTRY_H608C_velocityDimensionIndex &OD->list[92]
#define OD_ENTRY_H608D_accelerationNotationIndex &OD->list[93]
#define OD_ENTRY_H608E_accelerationDimensionIndex &OD->list[94]
#define OD_ENTRY_H608F_positionEncoderResolution &OD->list[95]
#define OD_ENTRY_H6090_velocityEncoderResolution &OD->list[96]
#define OD_ENTRY_H6091_gearRatio &OD->list[97]
#define OD_ENTRY_H6092_feedConstant &OD->list[98]
#define OD_ENTRY_H6093_positionFactor &OD->list[99]
#define OD_ENTRY_H6094_velocityEncoderFactor &OD->list[100]
#define OD_ENTRY_H6095_velocityFactor1 &OD->list[101]
#define OD_ENTRY_H6096_velocityFactor2 &OD->list[102]
#define OD_ENTRY_H6097_accelerationFactor &OD->list[103]
#define OD_ENTRY_H6098_homingMethod &OD->list[104]
#define OD_ENTRY_H6099_homingSpeeds &OD->list[105]
#define OD_ENTRY_H609A_homingAcceleration &OD->list[106]
#define OD_ENTRY_H60C0_interpolationSubModeSelect &OD->list[107]
#define OD_ENTRY_H60C1_interpolationDataRecord &OD->list[108]
#define OD_ENTRY_H60C2_interpolationTimePeriod &OD->list[109]
#define OD_ENTRY_H60C3_interpolationSyncDefinition &OD->list[110]
#define OD_ENTRY_H60C4_interpolationDataConfiguration &OD->list[111]
#define OD_ENTRY_H60C5_maxAcceleration &OD->list[112]
#define OD_ENTRY_H60C6_maxDeceleration &OD->list[113]
#define OD_ENTRY_H60F4_followingErrorActualValue &OD->list[114]
#define OD_ENTRY_H60F6_torqueControlParameters &OD->list[115]
#define OD_ENTRY_H60F7_powerStageParameters &OD->list[116]
#define OD_ENTRY_H60F8_maxSlippage &OD->list[117]
#define OD_ENTRY_H60F9_velocityControlParameterSet &OD->list[118]
#define OD_ENTRY_H60FA_controlEffort &OD->list[119]
#define OD_ENTRY_H60FB_positionControlParameterSet &OD->list[120]
#define OD_ENTRY_H60FC_positionDemandValue &OD->list[121]
#define OD_ENTRY_H60FD_digitalInputs &OD->list[122]
#define OD_ENTRY_H60FE_digitalOutputs &OD->list[123]
#define OD_ENTRY_H60FF_targetVelocity &OD->list[124]
#define OD_ENTRY_H6402_motorType &OD->list[125]
#define OD_ENTRY_H6403_motorCatalogueNumber &OD->list[126]
#define OD_ENTRY_H6404_motorManufacturer &OD->list[127]
#define OD_ENTRY_H6405_httpMotorCatalogAddress &OD->list[128]
#define OD_ENTRY_H6407_motorServicePeriod &OD->list[129]
#define OD_ENTRY_H6410_motorData &OD->list[130]
#define OD_ENTRY_H6502_supportedDriveModes &OD->list[131]
#define OD_ENTRY_H6503_driveCatalogNumber &OD->list[132]
#define OD_ENTRY_H6504_driveManufacturer &OD->list[133]
#define OD_ENTRY_H6505_httpDriveCatalogAddress &OD->list[134]
#define OD_ENTRY_H6510_driveData &OD->list[135]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = 0;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = 0;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = NULL;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = 0;\
    (config).ENTRY_H1200 = NULL;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = 0;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
