"""Markdown 文档导出器，对应 C# DocumentationGenMarkup"""
from __future__ import annotations

import os
from typing import Optional

from ..models.datatypes import DataType, ObjectType
from ..models.eds import EDS
from ..models.od_entry import ODentry
from .exporter_factory import ExporterDescriptor, ExporterFlags, IFileExporter


class DocumentationGenMarkup(IFileExporter):
    """Markdown 文档导出器"""

    def get_exporters(self) -> list[ExporterDescriptor]:
        return [
            ExporterDescriptor(
                "Documentation Markup",
                [".md"],
                ExporterFlags.Documentation,
                lambda filepath, eds_list: DocumentationGenMarkup()._gen_md_doc(filepath, eds_list[0]),
            )
        ]

    def _gen_md_doc(self, filepath: str, eds: EDS) -> None:
        with open(filepath, "w", newline="\n") as f:
            f.write(f"CANopen device documentation\n")
            f.write(f"============================\n")
            f.write(f"**{eds.di.ProductName}**\n\n")
            f.write(f"{eds.fi.Description}\n\n")

            f.write(f"|              |                                |\n")
            f.write(f"| ------------ | ------------------------------ |\n")
            f.write(f"| Project File | {eds.projectFilename:<30} |\n")
            f.write(f"| File Version | {eds.fi.FileVersion:<30} |\n")
            f.write(f"| Created      | {eds.fi.CreationDateTime:<30} |\n")
            f.write(f"| Created By   | {eds.fi.CreatedBy:<30} |\n")
            f.write(f"| Modified     | {eds.fi.ModificationDateTime:<30} |\n")
            f.write(f"| Modified By  | {eds.fi.ModifiedBy:<30} |\n\n")

            f.write(f"This file was automatically generated by [CANopenEditor](https://github.com/CANopenNode/CANopenEditor) (Python)\n\n")
            f.write(f"[TOC]\n\n")

            f.write(f"Device Information\n")
            f.write(f"------------------\n")
            f.write(f"|              |                                |\n")
            f.write(f"| ------------ | ------------------------------ |\n")
            f.write(f"| Vendor Name  | {eds.di.VendorName:<30} |\n")
            f.write(f"| Vendor ID    | {eds.di.VendorNumber:<30} |\n")
            f.write(f"| Product Name | {eds.di.ProductName:<30} |\n")
            f.write(f"| Product ID   | {eds.di.ProductNumber:<30} |\n")
            f.write(f"| Granularity  | {eds.di.Granularity:<30} |\n")
            f.write(f"| RPDO count   | {eds.di.NrOfRXPDO:<30} |\n")
            f.write(f"| TPDO count   | {eds.di.NrOfTXPDO:<30} |\n")
            f.write(f"| LSS Slave    | {eds.di.LSS_Supported:<30} |\n")
            f.write(f"| LSS Master   | {eds.di.LSS_Master:<30} |\n")
            f.write(f"| NG Slave     | {eds.di.NG_Slave:<30} |\n")
            f.write(f"| NG Master    | {eds.di.NG_Master:<30} |\n\n")

            f.write(f"### Supported Baud rates\n")
            for br, label in [
                (eds.di.BaudRate_10, "10 kBit/s"),
                (eds.di.BaudRate_20, "20 kBit/s"),
                (eds.di.BaudRate_50, "50 kBit/s"),
                (eds.di.BaudRate_125, "125 kBit/s"),
                (eds.di.BaudRate_250, "250 kBit/s"),
                (eds.di.BaudRate_500, "500 kBit/s"),
                (eds.di.BaudRate_800, "800 kBit/s"),
                (eds.di.BaudRate_1000, "1000 kBit/s"),
                (eds.di.BaudRate_auto, "auto"),
            ]:
                mark = "x" if br else " "
                f.write(f"* [{mark}] {label}\n")
            f.write("\n\n")

            f.write("PDO Mapping\n")
            f.write("-----------\n")
            self._print_pdo_md(f, eds)

            chapter = 0
            for od in eds.ods.values():
                if chapter == 0:
                    f.write("\nCommunication Specific Parameters\n")
                    f.write("---------------------------------\n")
                    chapter += 1
                if chapter == 1 and od.index >= 0x2000:
                    f.write("\nManufacturer Specific Parameters\n")
                    f.write("--------------------------------\n")
                    chapter += 1
                if chapter == 2 and od.index >= 0x6000:
                    f.write("\nDevice Profile Specific Parameters\n")
                    f.write("----------------------------------\n")
                    chapter += 1

                if not od.prop.CO_disabled:
                    self._print_od_entry_md(f, od)

    def _print_pdo_md(self, f, eds: EDS, skip_disabled: bool = False) -> None:
        parameters: dict[int, ODentry] = {}
        mappings: dict[int, ODentry] = {}

        for od in eds.ods.values():
            if od.index < 0x1400 or od.prop.CO_disabled or od.objecttype != ObjectType.RECORD or od.Nosubindexes < 3:
                continue
            elif od.index < 0x1600:
                parameters[od.index] = od
            elif od.index < 0x1800:
                mappings[od.index] = od
            elif od.index < 0x1A00:
                parameters[od.index] = od
            elif od.index < 0x1C00:
                mappings[od.index] = od
            else:
                break

        for par in parameters.values():
            mapping_index = par.index + 0x200
            if mapping_index not in mappings:
                continue

            map_od = mappings[mapping_index]

            try:
                if skip_disabled:
                    cob_id = par.subobjects[1].defaultvalue.replace("$NODEID", "").replace("+", "")
                    cob_id_num = int(cob_id, 0)
                    if cob_id_num & 0x80000000:
                        continue

                map_count = int(map_od.subobjects[0].defaultvalue, 0)
                if map_count == 0:
                    continue
            except (ValueError, KeyError):
                continue

            transmission_type = f"type={par.subobjects[2].defaultvalue}"
            pdo_label = "RPDO" if par.index < 0x1600 else "TPDO"

            if par.index < 0x1600:
                if par.Nosubindexes >= 6:
                    transmission_type += f"; event-timer={par.subobjects[5].defaultvalue}"
            else:
                if par.Nosubindexes >= 6:
                    transmission_type += f"; inhibit-time={par.subobjects[3].defaultvalue}; event-timer={par.subobjects[5].defaultvalue}"
                if par.Nosubindexes >= 7:
                    transmission_type += f"; SYNC-start-value={par.subobjects[6].defaultvalue}"

            f.write(f"\n### {pdo_label} 0x{par.index:04X}\n")
            f.write(f"|              |                                                               |\n")
            f.write(f"| ------------ | ------------------------------------------------------------- |\n")
            f.write(f"| COB_ID       | {par.subobjects[1].defaultvalue:<62}|\n")
            f.write(f"| Transmission | {transmission_type:<62}|\n")

            for sub_idx_pdo in range(1, map_count + 1):
                if sub_idx_pdo not in map_od.subobjects:
                    break
                try:
                    map_val = int(map_od.subobjects[sub_idx_pdo].defaultvalue, 0)
                except (ValueError, KeyError):
                    break

                map_idx = (map_val >> 16) & 0xFFFF
                map_sub = (map_val >> 8) & 0xFF

                name_idx = "(MISSING)"
                name_sub = " (MISSING)"
                if map_idx in eds.ods:
                    od_mapped = eds.ods[map_idx]
                    name_idx = od_mapped.parameter_name
                    if od_mapped.objecttype == ObjectType.VAR:
                        name_sub = ""
                    elif map_sub in od_mapped.subobjects:
                        name_sub = f" ({od_mapped.subobjects[map_sub].parameter_name})"
                elif map_idx < 0x20:
                    try:
                        name_idx = DataType(map_idx).name
                        name_sub = ""
                    except ValueError:
                        pass

                f.write(f"|   0x{map_val:08X} | {name_idx + name_sub:<62}|\n")

            f.write("\n")

    def _print_od_entry_md(self, f, od: ODentry) -> None:
        descriptions: list[str] = []

        f.write(f"\n### 0x{od.index:04X} - {od.parameter_name}\n")
        f.write(f"| Object Type | Count Label    | Storage Group  |\n")
        f.write(f"| ----------- | -------------- | -------------- |\n")
        f.write(f"| {od.objecttype_string():<12}| {od.prop.CO_countLabel:<15}| {od.prop.CO_storageGroup:<15}|\n")

        if od.Description:
            descriptions.append(od.Description)

        if od.objecttype == ObjectType.VAR:
            dt = self._print_data_type(od)
            f.write(f"\n| Data Type               | SDO | PDO | SRDO | Default Value                   |\n")
            f.write(f"| ----------------------- | --- | --- | ---- | ------------------------------- |\n")
            f.write(f"| {dt:<24}| {od.access_sdo().name:<4}| {od.access_pdo().name:<4}| {od.prop.CO_accessSRDO.name:<5}| {od.defaultvalue:<32}|\n")
        else:
            f.write(f"\n| Sub  | Name                  | Data Type  | SDO | PDO | SRDO | Default Value |\n")
            f.write(f"| ---- | --------------------- | ---------- | --- | --- | ---- | ------------- |\n")

            for sub_od in od.subobjects.values():
                dt = self._print_data_type(sub_od)
                f.write(f"| 0x{sub_od.Subindex:02X} | {sub_od.parameter_name:<22}| {dt:<11}| {sub_od.access_sdo().name:<4}| {sub_od.access_pdo().name:<4}| {sub_od.prop.CO_accessSRDO.name:<5}| {sub_od.defaultvalue:<14}|\n")

                if sub_od.Description:
                    descriptions.append(sub_od.Description)

        if descriptions:
            f.write("\n")
            f.write("\n".join(descriptions))
            f.write("\n")

    def _print_data_type(self, od: ODentry) -> str:
        dt = od.datatype.name
        if od.datatype in (DataType.VISIBLE_STRING, DataType.UNICODE_STRING) and od.prop.CO_stringLengthMin > len(od.defaultvalue):
            dt += f" (len={od.prop.CO_stringLengthMin})"
        return dt
