/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1000_deviceType = 0x00420192,
    .x1001_errorRegister = 0x00,
    .x1003_predefinedErrorField_sub0 = 0x00,
    .x1003_predefinedErrorField = {0x00000000, 0x00000000},
    .x1005_COB_ID_SYNC = 0x00000080,
    .x100A_manufacturerSoftwareVersion = {'3', '1', '5', '0', '.', '6', '8', 'B', 0},
    .x100C_guardTime = 0x0000,
    .x100D_lifeTimeFactor = 0x00,
    .x1010_storeParameters_sub0 = 0x09,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001, 0x00000001, 0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x06,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1016_consumerHeartbeatTime_sub0 = 0x01,
    .x1016_consumerHeartbeatTime = {0x00000000},
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identityObject = {
        .numberOfEntries = 0x04,
        .vendorId = 0x00000147,
        .productCode = 0x00000C4E,
        .revisionNumber = 0x00000002
    },
    .x1029_errorBehaviour_sub0 = 0x01,
    .x1029_errorBehaviour = {0x00},
    .x1200_serverSDO1Parameter = {
        .numberOfEntries = 0x02,
        .COB_ID_ClientToServer = 0x00000600,
        .COB_ID_ServerToClient = 0x00000580
    },
    .x1400_receivePDO1CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000200,
        .transmissionType = 0xFF
    },
    .x1401_receivePDO2CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000300,
        .transmissionType = 0xFF
    },
    .x1402_receivePDO3CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000400,
        .transmissionType = 0xFF
    },
    .x1403_receivePDO4CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000500,
        .transmissionType = 0xFF
    },
    .x1600_receivePDO1MappingParameter = {
        .numberOfMappedObjects = 0x01,
        .PDO_MappingEntry1 = 0x60400010,
        .PDO_MappingEntry2 = 0x00000000,
        .PDO_MappingEntry3 = 0x00000000,
        .PDO_MappingEntry4 = 0x00000000
    },
    .x1601_receivePDO2MappingParameter = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry1 = 0x60400010,
        .PDO_MappingEntry2 = 0x607A0020,
        .PDO_MappingEntry3 = 0x00000000,
        .PDO_MappingEntry4 = 0x00000000
    },
    .x1602_receivePDO3MappingParameter = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry1 = 0x60400010,
        .PDO_MappingEntry2 = 0x60FF0020,
        .PDO_MappingEntry3 = 0x00000000,
        .PDO_MappingEntry4 = 0x00000000
    },
    .x1603_receivePDO4MappingParameter = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry1 = 0x60400010,
        .PDO_MappingEntry2 = 0x257A0020,
        .PDO_MappingEntry3 = 0x00000000,
        .PDO_MappingEntry4 = 0x00000000
    },
    .x1800_transmitPDO1CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000180,
        .transmissionType = 0xFF
    },
    .x1801_transmitPDO2CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000280,
        .transmissionType = 0xFF
    },
    .x1802_transmitPDO3CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000380,
        .transmissionType = 0xFF
    },
    .x1803_transmitPDO4CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000480,
        .transmissionType = 0xFF
    },
    .x1A00_transmitPDO1MappingParameter = {
        .numberOfEntries = 0x01,
        .PDO_MappingEntry1 = 0x60410010,
        .PDO_MappingEntry2 = 0x00000000,
        .PDO_MappingEntry3 = 0x00000000,
        .PDO_MappingEntry4 = 0x00000000
    },
    .x1A01_transmitPDO2MappingParameter = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry1 = 0x60410010,
        .PDO_MappingEntry2 = 0x60640020,
        .PDO_MappingEntry3 = 0x00000000,
        .PDO_MappingEntry4 = 0x00000000
    },
    .x1A02_transmitPDO3MappingParameter = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry1 = 0x60410010,
        .PDO_MappingEntry2 = 0x606C0020,
        .PDO_MappingEntry3 = 0x00000000,
        .PDO_MappingEntry4 = 0x00000000
    },
    .x1A03_transmitPDO4MappingParameter = {
        .numberOfEntries = 0x02,
        .PDO_MappingEntry1 = 0x60640020,
        .PDO_MappingEntry2 = 0x606C0020,
        .PDO_MappingEntry3 = 0x00000000,
        .PDO_MappingEntry4 = 0x00000000
    },
    .x2310_digitalInputSettings = {
        .numberOfEntries = 0x06,
        .negativeLimitSwitch = 0x00,
        .positiveLimitSwitch = 0x00,
        .homingSwitch = 0x1F,
        .switchPolarity = 0x1F,
        .polarityForHomingLimit = 0x00
    },
    .x2311_digitalInputStatus = {
        .numberOfEntries = 0x02
    },
    .x2313_analogInputStatus = {
        .numberOfEntries = 0x05
    },
    .x2314_analogInputStatusRaw = {
        .numberOfEntries = 0x08
    },
    .x2315_fault_PinSettings = {
        .numberOfEntries = 0x03,
        .faultPinFunction = 0x00,
        .digitalOutputStatus = 0x00
    },
    .x2316_inputThresholdLevel = 0x01,
    .x2320_FAULHABER_FaultRegister = 0x0000,
    .x2321_errorMask = {
        .numberOfEntries = 0x03,
        .emergencyMask = 0xFFFF,
        .faultMask = 0x0000,
        .erroutMask = 0x00FF
    },
    .x2322_errorHandling = {
        .numberOfEntries = 0x02,
        .errorDelay = 0x00C8,
        .deviation = 0x7530
    },
    .x2323_deviceStatus = {
        .numberOfEntries = 0x04
    },
    .x2330_filterSettings = {
        .numberOfEntries = 0x02,
        .samplingRate = 0x0001,
        .gainSchedulingVelocityController = 0x0000
    },
    .x2331_velocityControlParameterSet = {
        .numberOfEntries = 0x02,
        .proportionalTermPOR = 0x0008,
        .integralTermI = 0x0014
    },
    .x2332_positionControlParameterSet = {
        .numberOfEntries = 0x02,
        .proportionalTermPP = 0x000A,
        .derivativeTermPD = 0x0005
    },
    .x2333_currentControlParameterSet = {
        .numberOfEntries = 0x03
    },
    .x2338_generalSettings = {
        .numberOfEntries = 0x03,
        .activatePositionLimitsInVelocityMode = 0x0000,
        .activatePositionLimitsInPositionMode = 0x0001
    },
    .x2350_motorData = {
        .numberOfEntries = 0x05,
        .speedConstantKN = 0x36B0,
        .terminalResistanceRM = 0x00030D40,
        .thermalTimeConstantTW1 = 0x55F0
    },
    .x2351_encoderData = {
        .numberOfEntries = 0x02,
        .resolutionExternalEncoder = 0x00000800
    },
    .x2403_resetGroup = 0x0000,
    .x2404_serviceSettings = 0x00FF,
    .x2405_supervisor = {
        .numberOfEntries = 0x02,
        .status = 0x00
    },
    .x2407_setSerialNumber = 0x00000000,
    .x2409_setDeviceName = 0x00000000,
    .x240A_calibrationData = {
        .numberOfEntries = 0x0B
    },
    .x240B_calibration = {
        .numberOfEntries = 0x04
    },
    .x2457_acceptanceFilter00 = {
        .numberOfEntries = 0x02
    },
    .x2458_acceptanceFilter01 = {
        .numberOfEntries = 0x02
    },
    .x2459_acceptanceFilter10 = {
        .numberOfEntries = 0x02
    },
    .x245A_acceptanceFilter11 = {
        .numberOfEntries = 0x02
    },
    .x245B_numberOfHomingStarts = 0x0000,
    .x257B_positionRangeLimitInternalValue_sub0 = 0x02,
    .x257B_positionRangeLimitInternalValue = {-1800000000, 1800000000},
    .x257D_softwarePositionLimitInternalValue = {
        .numberOfEntries = 0x02,
        .minimumPositionLimit = -1800000000,
        .maximumPositionLimit = 1800000000
    },
    .x6040_controlword = 0x0000,
    .x6060_modesOfOperation = 1,
    .x6061_modesOfOperationDisplay = 1,
    .x6067_positionWindow = 0x00000014,
    .x6068_positionWindowTime = 0x00C8,
    .x606D_velocityWindow = 0x0014,
    .x606F_velocityThreshold = 0x0014,
    .x6070_velocityThresholdTime = 0x00C8,
    .x607B_positionRangeLimit_sub0 = 0x02,
    .x607B_positionRangeLimit = {-1800000000, 1800000000},
    .x607C_homeOffset = 0,
    .x607D_softwarePositionLimit_sub0 = 0x02,
    .x607D_softwarePositionLimit = {-1800000000, 1800000000},
    .x607E_polarity = 0x00,
    .x6083_profileAcceleration = 0x00007530,
    .x6084_profileDeceleration = 0x00007530,
    .x6085_quickStopDeceleration = 0x00007530,
    .x608F_positionEncoderResolution_sub0 = 0x02,
    .x608F_positionEncoderResolution = {0x00000800, 0x00000001},
    .x6091_gearRatio_sub0 = 0x02,
    .x6091_gearRatio = {0x00000001, 0x00000001},
    .x6092_feedConstant_sub0 = 0x02,
    .x6092_feedConstant = {0x00000800, 0x00000001},
    .x6093_positionFactor_sub0 = 0x02,
    .x6093_positionFactor = {0x00000800, 0x00000800},
    .x6098_homingMethod = 20,
    .x6099_homingSpeeds_sub0 = 0x02,
    .x6099_homingSpeeds = {0x00000190, 0x00000064},
    .x609A_homingAcceleration = 0x00000032,
    .x6502_supportedDriveModes = 0x00000025
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_predefinedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNC;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_100C_guardTime;
    OD_obj_var_t o_100D_lifeTimeFactor;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identityObject[5];
    OD_obj_array_t o_1029_errorBehaviour;
    OD_obj_record_t o_1200_serverSDO1Parameter[3];
    OD_obj_record_t o_1400_receivePDO1CommunicationParameter[3];
    OD_obj_record_t o_1401_receivePDO2CommunicationParameter[3];
    OD_obj_record_t o_1402_receivePDO3CommunicationParameter[3];
    OD_obj_record_t o_1403_receivePDO4CommunicationParameter[3];
    OD_obj_record_t o_1600_receivePDO1MappingParameter[5];
    OD_obj_record_t o_1601_receivePDO2MappingParameter[5];
    OD_obj_record_t o_1602_receivePDO3MappingParameter[5];
    OD_obj_record_t o_1603_receivePDO4MappingParameter[5];
    OD_obj_record_t o_1800_transmitPDO1CommunicationParameter[3];
    OD_obj_record_t o_1801_transmitPDO2CommunicationParameter[3];
    OD_obj_record_t o_1802_transmitPDO3CommunicationParameter[3];
    OD_obj_record_t o_1803_transmitPDO4CommunicationParameter[3];
    OD_obj_record_t o_1A00_transmitPDO1MappingParameter[5];
    OD_obj_record_t o_1A01_transmitPDO2MappingParameter[5];
    OD_obj_record_t o_1A02_transmitPDO3MappingParameter[5];
    OD_obj_record_t o_1A03_transmitPDO4MappingParameter[5];
    OD_obj_record_t o_2310_digitalInputSettings[6];
    OD_obj_record_t o_2311_digitalInputStatus[3];
    OD_obj_record_t o_2313_analogInputStatus[5];
    OD_obj_record_t o_2314_analogInputStatusRaw[9];
    OD_obj_record_t o_2315_fault_PinSettings[3];
    OD_obj_var_t o_2316_inputThresholdLevel;
    OD_obj_var_t o_2320_FAULHABER_FaultRegister;
    OD_obj_record_t o_2321_errorMask[4];
    OD_obj_record_t o_2322_errorHandling[3];
    OD_obj_record_t o_2323_deviceStatus[5];
    OD_obj_record_t o_2330_filterSettings[3];
    OD_obj_record_t o_2331_velocityControlParameterSet[3];
    OD_obj_record_t o_2332_positionControlParameterSet[3];
    OD_obj_record_t o_2333_currentControlParameterSet[4];
    OD_obj_var_t o_2334_actualCurrentLimit;
    OD_obj_record_t o_2338_generalSettings[3];
    OD_obj_record_t o_2350_motorData[4];
    OD_obj_record_t o_2351_encoderData[2];
    OD_obj_var_t o_2360_outputVoltageDemandValue;
    OD_obj_var_t o_2361_velocityActualValueUnfiltered;
    OD_obj_var_t o_2400_baudrateSet;
    OD_obj_var_t o_2401_setOfSpecialConfigurations;
    OD_obj_var_t o_2403_resetGroup;
    OD_obj_var_t o_2404_serviceSettings;
    OD_obj_record_t o_2405_supervisor[3];
    OD_obj_var_t o_2407_setSerialNumber;
    OD_obj_var_t o_2409_setDeviceName;
    OD_obj_record_t o_240A_calibrationData[11];
    OD_obj_record_t o_240B_calibration[2];
    OD_obj_var_t o_2456_buildNumber;
    OD_obj_record_t o_2457_acceptanceFilter00[3];
    OD_obj_record_t o_2458_acceptanceFilter01[3];
    OD_obj_record_t o_2459_acceptanceFilter10[3];
    OD_obj_record_t o_245A_acceptanceFilter11[3];
    OD_obj_var_t o_245B_numberOfHomingStarts;
    OD_obj_var_t o_2562_positionDemandInternalValue;
    OD_obj_var_t o_257A_targetPositionInternalValue;
    OD_obj_array_t o_257B_positionRangeLimitInternalValue;
    OD_obj_record_t o_257D_softwarePositionLimitInternalValue[3];
    OD_obj_var_t o_2DFF_DFF_Object;
    OD_obj_var_t o_6040_controlword;
    OD_obj_var_t o_6041_statusword;
    OD_obj_var_t o_6060_modesOfOperation;
    OD_obj_var_t o_6061_modesOfOperationDisplay;
    OD_obj_var_t o_6062_positionDemandValue;
    OD_obj_var_t o_6063_positionActualInternalValue;
    OD_obj_var_t o_6064_positionActualValue;
    OD_obj_var_t o_6067_positionWindow;
    OD_obj_var_t o_6068_positionWindowTime;
    OD_obj_var_t o_606B_velocityDemandValue;
    OD_obj_var_t o_606C_velocityActualValue;
    OD_obj_var_t o_606D_velocityWindow;
    OD_obj_var_t o_606E_velocityWindowTime;
    OD_obj_var_t o_606F_velocityThreshold;
    OD_obj_var_t o_6070_velocityThresholdTime;
    OD_obj_var_t o_6078_currentActualValue;
    OD_obj_var_t o_607A_targetPosition;
    OD_obj_array_t o_607B_positionRangeLimit;
    OD_obj_var_t o_607C_homeOffset;
    OD_obj_array_t o_607D_softwarePositionLimit;
    OD_obj_var_t o_607E_polarity;
    OD_obj_var_t o_607F_maxProfileVelocity;
    OD_obj_var_t o_6081_profileVelocity;
    OD_obj_var_t o_6083_profileAcceleration;
    OD_obj_var_t o_6084_profileDeceleration;
    OD_obj_var_t o_6085_quickStopDeceleration;
    OD_obj_array_t o_608F_positionEncoderResolution;
    OD_obj_array_t o_6091_gearRatio;
    OD_obj_array_t o_6092_feedConstant;
    OD_obj_array_t o_6093_positionFactor;
    OD_obj_var_t o_6098_homingMethod;
    OD_obj_array_t o_6099_homingSpeeds;
    OD_obj_var_t o_609A_homingAcceleration;
    OD_obj_var_t o_60FA_controlEffort;
    OD_obj_var_t o_60FD_digitalInputs;
    OD_obj_var_t o_60FF_targetVelocity;
    OD_obj_var_t o_6502_supportedDriveModes;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_RAM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1003_predefinedErrorField = {
        .dataOrig0 = &OD_RAM.x1003_predefinedErrorField_sub0,
        .dataOrig = &OD_RAM.x1003_predefinedErrorField[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNC = {
        .dataOrig = &OD_RAM.x1005_COB_ID_SYNC,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &OD_RAM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 8
    },
    .o_100C_guardTime = {
        .dataOrig = &OD_RAM.x100C_guardTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_100D_lifeTimeFactor = {
        .dataOrig = &OD_RAM.x100D_lifeTimeFactor,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_RAM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_RAM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_RAM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_RAM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identityObject = {
        {
            .dataOrig = &OD_RAM.x1018_identityObject.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1018_identityObject.vendorId,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identityObject.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identityObject.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1029_errorBehaviour = {
        .dataOrig0 = &OD_RAM.x1029_errorBehaviour_sub0,
        .dataOrig = &OD_RAM.x1029_errorBehaviour[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_1200_serverSDO1Parameter = {
        {
            .dataOrig = &OD_RAM.x1200_serverSDO1Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_serverSDO1Parameter.COB_ID_ClientToServer,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_serverSDO1Parameter.COB_ID_ServerToClient,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_receivePDO1CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1CommunicationParameter.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO1CommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1401_receivePDO2CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2CommunicationParameter.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO2CommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1402_receivePDO3CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3CommunicationParameter.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO3CommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1403_receivePDO4CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4CommunicationParameter.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO4CommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_receivePDO1MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1600_receivePDO1MappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO1MappingParameter.PDO_MappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO1MappingParameter.PDO_MappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO1MappingParameter.PDO_MappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO1MappingParameter.PDO_MappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_receivePDO2MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1601_receivePDO2MappingParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO2MappingParameter.PDO_MappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO2MappingParameter.PDO_MappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO2MappingParameter.PDO_MappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO2MappingParameter.PDO_MappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_receivePDO3MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1602_receivePDO3MappingParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO3MappingParameter.PDO_MappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO3MappingParameter.PDO_MappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO3MappingParameter.PDO_MappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO3MappingParameter.PDO_MappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_receivePDO4MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1603_receivePDO4MappingParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO4MappingParameter.PDO_MappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO4MappingParameter.PDO_MappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO4MappingParameter.PDO_MappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO4MappingParameter.PDO_MappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_transmitPDO1CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1CommunicationParameter.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO1CommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_transmitPDO2CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2CommunicationParameter.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO2CommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_transmitPDO3CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3CommunicationParameter.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO3CommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_transmitPDO4CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4CommunicationParameter.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO4CommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_transmitPDO1MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO1MappingParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO1MappingParameter.PDO_MappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO1MappingParameter.PDO_MappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO1MappingParameter.PDO_MappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO1MappingParameter.PDO_MappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_transmitPDO2MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO2MappingParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO2MappingParameter.PDO_MappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO2MappingParameter.PDO_MappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO2MappingParameter.PDO_MappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO2MappingParameter.PDO_MappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_transmitPDO3MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO3MappingParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO3MappingParameter.PDO_MappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO3MappingParameter.PDO_MappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO3MappingParameter.PDO_MappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO3MappingParameter.PDO_MappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_transmitPDO4MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO4MappingParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO4MappingParameter.PDO_MappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO4MappingParameter.PDO_MappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO4MappingParameter.PDO_MappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO4MappingParameter.PDO_MappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2310_digitalInputSettings = {
        {
            .dataOrig = &OD_RAM.x2310_digitalInputSettings.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2310_digitalInputSettings.negativeLimitSwitch,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2310_digitalInputSettings.positiveLimitSwitch,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2310_digitalInputSettings.homingSwitch,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2310_digitalInputSettings.switchPolarity,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2310_digitalInputSettings.polarityForHomingLimit,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        }
    },
    .o_2311_digitalInputStatus = {
        {
            .dataOrig = &OD_RAM.x2311_digitalInputStatus.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TRPDO,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TRPDO,
            .dataLength = 1
        }
    },
    .o_2313_analogInputStatus = {
        {
            .dataOrig = &OD_RAM.x2313_analogInputStatus.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2314_analogInputStatusRaw = {
        {
            .dataOrig = &OD_RAM.x2314_analogInputStatusRaw.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2315_fault_PinSettings = {
        {
            .dataOrig = &OD_RAM.x2315_fault_PinSettings.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2315_fault_PinSettings.faultPinFunction,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2315_fault_PinSettings.digitalOutputStatus,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_RPDO,
            .dataLength = 1
        }
    },
    .o_2316_inputThresholdLevel = {
        .dataOrig = &OD_RAM.x2316_inputThresholdLevel,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_2320_FAULHABER_FaultRegister = {
        .dataOrig = &OD_RAM.x2320_FAULHABER_FaultRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2321_errorMask = {
        {
            .dataOrig = &OD_RAM.x2321_errorMask.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2321_errorMask.emergencyMask,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2321_errorMask.faultMask,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2321_errorMask.erroutMask,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2322_errorHandling = {
        {
            .dataOrig = &OD_RAM.x2322_errorHandling.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2322_errorHandling.errorDelay,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2322_errorHandling.deviation,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2323_deviceStatus = {
        {
            .dataOrig = &OD_RAM.x2323_deviceStatus.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2330_filterSettings = {
        {
            .dataOrig = &OD_RAM.x2330_filterSettings.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2330_filterSettings.samplingRate,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2330_filterSettings.gainSchedulingVelocityController,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2331_velocityControlParameterSet = {
        {
            .dataOrig = &OD_RAM.x2331_velocityControlParameterSet.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2331_velocityControlParameterSet.proportionalTermPOR,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2331_velocityControlParameterSet.integralTermI,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2332_positionControlParameterSet = {
        {
            .dataOrig = &OD_RAM.x2332_positionControlParameterSet.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2332_positionControlParameterSet.proportionalTermPP,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2332_positionControlParameterSet.derivativeTermPD,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2333_currentControlParameterSet = {
        {
            .dataOrig = &OD_RAM.x2333_currentControlParameterSet.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2334_actualCurrentLimit = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2338_generalSettings = {
        {
            .dataOrig = &OD_RAM.x2338_generalSettings.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2338_generalSettings.activatePositionLimitsInVelocityMode,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2338_generalSettings.activatePositionLimitsInPositionMode,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2350_motorData = {
        {
            .dataOrig = &OD_RAM.x2350_motorData.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2350_motorData.speedConstantKN,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x2350_motorData.terminalResistanceRM,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x2350_motorData.thermalTimeConstantTW1,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2351_encoderData = {
        {
            .dataOrig = &OD_RAM.x2351_encoderData.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2351_encoderData.resolutionExternalEncoder,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2360_outputVoltageDemandValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2361_velocityActualValueUnfiltered = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2400_baudrateSet = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_2401_setOfSpecialConfigurations = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2403_resetGroup = {
        .dataOrig = &OD_RAM.x2403_resetGroup,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2404_serviceSettings = {
        .dataOrig = &OD_RAM.x2404_serviceSettings,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_2405_supervisor = {
        {
            .dataOrig = &OD_RAM.x2405_supervisor.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2405_supervisor.status,
            .subIndex = 1,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_W | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2407_setSerialNumber = {
        .dataOrig = &OD_RAM.x2407_setSerialNumber,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_2409_setDeviceName = {
        .dataOrig = &OD_RAM.x2409_setDeviceName,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_240A_calibrationData = {
        {
            .dataOrig = &OD_RAM.x240A_calibrationData.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 10,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = NULL,
            .subIndex = 11,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_240B_calibration = {
        {
            .dataOrig = &OD_RAM.x240B_calibration.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2456_buildNumber = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_2457_acceptanceFilter00 = {
        {
            .dataOrig = &OD_RAM.x2457_acceptanceFilter00.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2458_acceptanceFilter01 = {
        {
            .dataOrig = &OD_RAM.x2458_acceptanceFilter01.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2459_acceptanceFilter10 = {
        {
            .dataOrig = &OD_RAM.x2459_acceptanceFilter10.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_245A_acceptanceFilter11 = {
        {
            .dataOrig = &OD_RAM.x245A_acceptanceFilter11.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_245B_numberOfHomingStarts = {
        .dataOrig = &OD_RAM.x245B_numberOfHomingStarts,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2562_positionDemandInternalValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_257A_targetPositionInternalValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_257B_positionRangeLimitInternalValue = {
        .dataOrig0 = &OD_RAM.x257B_positionRangeLimitInternalValue_sub0,
        .dataOrig = &OD_RAM.x257B_positionRangeLimitInternalValue[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_257D_softwarePositionLimitInternalValue = {
        {
            .dataOrig = &OD_RAM.x257D_softwarePositionLimitInternalValue.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x257D_softwarePositionLimitInternalValue.minimumPositionLimit,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x257D_softwarePositionLimitInternalValue.maximumPositionLimit,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2DFF_DFF_Object = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6040_controlword = {
        .dataOrig = &OD_RAM.x6040_controlword,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_statusword = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6060_modesOfOperation = {
        .dataOrig = &OD_RAM.x6060_modesOfOperation,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6061_modesOfOperationDisplay = {
        .dataOrig = &OD_RAM.x6061_modesOfOperationDisplay,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_6062_positionDemandValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6063_positionActualInternalValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6064_positionActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6067_positionWindow = {
        .dataOrig = &OD_RAM.x6067_positionWindow,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6068_positionWindowTime = {
        .dataOrig = &OD_RAM.x6068_positionWindowTime,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_606B_velocityDemandValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606C_velocityActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606D_velocityWindow = {
        .dataOrig = &OD_RAM.x606D_velocityWindow,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_606E_velocityWindowTime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_606F_velocityThreshold = {
        .dataOrig = &OD_RAM.x606F_velocityThreshold,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6070_velocityThresholdTime = {
        .dataOrig = &OD_RAM.x6070_velocityThresholdTime,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6078_currentActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_607A_targetPosition = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607B_positionRangeLimit = {
        .dataOrig0 = &OD_RAM.x607B_positionRangeLimit_sub0,
        .dataOrig = &OD_RAM.x607B_positionRangeLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_607C_homeOffset = {
        .dataOrig = &OD_RAM.x607C_homeOffset,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607D_softwarePositionLimit = {
        .dataOrig0 = &OD_RAM.x607D_softwarePositionLimit_sub0,
        .dataOrig = &OD_RAM.x607D_softwarePositionLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_607E_polarity = {
        .dataOrig = &OD_RAM.x607E_polarity,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_607F_maxProfileVelocity = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6081_profileVelocity = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6083_profileAcceleration = {
        .dataOrig = &OD_RAM.x6083_profileAcceleration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6084_profileDeceleration = {
        .dataOrig = &OD_RAM.x6084_profileDeceleration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6085_quickStopDeceleration = {
        .dataOrig = &OD_RAM.x6085_quickStopDeceleration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_608F_positionEncoderResolution = {
        .dataOrig0 = &OD_RAM.x608F_positionEncoderResolution_sub0,
        .dataOrig = &OD_RAM.x608F_positionEncoderResolution[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6091_gearRatio = {
        .dataOrig0 = &OD_RAM.x6091_gearRatio_sub0,
        .dataOrig = &OD_RAM.x6091_gearRatio[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6092_feedConstant = {
        .dataOrig0 = &OD_RAM.x6092_feedConstant_sub0,
        .dataOrig = &OD_RAM.x6092_feedConstant[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6093_positionFactor = {
        .dataOrig0 = &OD_RAM.x6093_positionFactor_sub0,
        .dataOrig = &OD_RAM.x6093_positionFactor[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6098_homingMethod = {
        .dataOrig = &OD_RAM.x6098_homingMethod,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6099_homingSpeeds = {
        .dataOrig0 = &OD_RAM.x6099_homingSpeeds_sub0,
        .dataOrig = &OD_RAM.x6099_homingSpeeds[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_609A_homingAcceleration = {
        .dataOrig = &OD_RAM.x609A_homingAcceleration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60FA_controlEffort = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60FD_digitalInputs = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60FF_targetVelocity = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6502_supportedDriveModes = {
        .dataOrig = &OD_RAM.x6502_supportedDriveModes,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x03, ODT_ARR, &ODObjs.o_1003_predefinedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNC, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x100C, 0x01, ODT_VAR, &ODObjs.o_100C_guardTime, NULL},
    {0x100D, 0x01, ODT_VAR, &ODObjs.o_100D_lifeTimeFactor, NULL},
    {0x1010, 0x0A, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x07, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1016, 0x02, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identityObject, NULL},
    {0x1029, 0x02, ODT_ARR, &ODObjs.o_1029_errorBehaviour, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_serverSDO1Parameter, NULL},
    {0x1400, 0x03, ODT_REC, &ODObjs.o_1400_receivePDO1CommunicationParameter, NULL},
    {0x1401, 0x03, ODT_REC, &ODObjs.o_1401_receivePDO2CommunicationParameter, NULL},
    {0x1402, 0x03, ODT_REC, &ODObjs.o_1402_receivePDO3CommunicationParameter, NULL},
    {0x1403, 0x03, ODT_REC, &ODObjs.o_1403_receivePDO4CommunicationParameter, NULL},
    {0x1600, 0x05, ODT_REC, &ODObjs.o_1600_receivePDO1MappingParameter, NULL},
    {0x1601, 0x05, ODT_REC, &ODObjs.o_1601_receivePDO2MappingParameter, NULL},
    {0x1602, 0x05, ODT_REC, &ODObjs.o_1602_receivePDO3MappingParameter, NULL},
    {0x1603, 0x05, ODT_REC, &ODObjs.o_1603_receivePDO4MappingParameter, NULL},
    {0x1800, 0x03, ODT_REC, &ODObjs.o_1800_transmitPDO1CommunicationParameter, NULL},
    {0x1801, 0x03, ODT_REC, &ODObjs.o_1801_transmitPDO2CommunicationParameter, NULL},
    {0x1802, 0x03, ODT_REC, &ODObjs.o_1802_transmitPDO3CommunicationParameter, NULL},
    {0x1803, 0x03, ODT_REC, &ODObjs.o_1803_transmitPDO4CommunicationParameter, NULL},
    {0x1A00, 0x05, ODT_REC, &ODObjs.o_1A00_transmitPDO1MappingParameter, NULL},
    {0x1A01, 0x05, ODT_REC, &ODObjs.o_1A01_transmitPDO2MappingParameter, NULL},
    {0x1A02, 0x05, ODT_REC, &ODObjs.o_1A02_transmitPDO3MappingParameter, NULL},
    {0x1A03, 0x05, ODT_REC, &ODObjs.o_1A03_transmitPDO4MappingParameter, NULL},
    {0x2310, 0x06, ODT_REC, &ODObjs.o_2310_digitalInputSettings, NULL},
    {0x2311, 0x03, ODT_REC, &ODObjs.o_2311_digitalInputStatus, NULL},
    {0x2313, 0x05, ODT_REC, &ODObjs.o_2313_analogInputStatus, NULL},
    {0x2314, 0x09, ODT_REC, &ODObjs.o_2314_analogInputStatusRaw, NULL},
    {0x2315, 0x03, ODT_REC, &ODObjs.o_2315_fault_PinSettings, NULL},
    {0x2316, 0x01, ODT_VAR, &ODObjs.o_2316_inputThresholdLevel, NULL},
    {0x2320, 0x01, ODT_VAR, &ODObjs.o_2320_FAULHABER_FaultRegister, NULL},
    {0x2321, 0x04, ODT_REC, &ODObjs.o_2321_errorMask, NULL},
    {0x2322, 0x03, ODT_REC, &ODObjs.o_2322_errorHandling, NULL},
    {0x2323, 0x05, ODT_REC, &ODObjs.o_2323_deviceStatus, NULL},
    {0x2330, 0x03, ODT_REC, &ODObjs.o_2330_filterSettings, NULL},
    {0x2331, 0x03, ODT_REC, &ODObjs.o_2331_velocityControlParameterSet, NULL},
    {0x2332, 0x03, ODT_REC, &ODObjs.o_2332_positionControlParameterSet, NULL},
    {0x2333, 0x04, ODT_REC, &ODObjs.o_2333_currentControlParameterSet, NULL},
    {0x2334, 0x01, ODT_VAR, &ODObjs.o_2334_actualCurrentLimit, NULL},
    {0x2338, 0x03, ODT_REC, &ODObjs.o_2338_generalSettings, NULL},
    {0x2350, 0x04, ODT_REC, &ODObjs.o_2350_motorData, NULL},
    {0x2351, 0x02, ODT_REC, &ODObjs.o_2351_encoderData, NULL},
    {0x2360, 0x01, ODT_VAR, &ODObjs.o_2360_outputVoltageDemandValue, NULL},
    {0x2361, 0x01, ODT_VAR, &ODObjs.o_2361_velocityActualValueUnfiltered, NULL},
    {0x2400, 0x01, ODT_VAR, &ODObjs.o_2400_baudrateSet, NULL},
    {0x2401, 0x01, ODT_VAR, &ODObjs.o_2401_setOfSpecialConfigurations, NULL},
    {0x2403, 0x01, ODT_VAR, &ODObjs.o_2403_resetGroup, NULL},
    {0x2404, 0x01, ODT_VAR, &ODObjs.o_2404_serviceSettings, NULL},
    {0x2405, 0x03, ODT_REC, &ODObjs.o_2405_supervisor, NULL},
    {0x2407, 0x01, ODT_VAR, &ODObjs.o_2407_setSerialNumber, NULL},
    {0x2409, 0x01, ODT_VAR, &ODObjs.o_2409_setDeviceName, NULL},
    {0x240A, 0x0B, ODT_REC, &ODObjs.o_240A_calibrationData, NULL},
    {0x240B, 0x02, ODT_REC, &ODObjs.o_240B_calibration, NULL},
    {0x2456, 0x01, ODT_VAR, &ODObjs.o_2456_buildNumber, NULL},
    {0x2457, 0x03, ODT_REC, &ODObjs.o_2457_acceptanceFilter00, NULL},
    {0x2458, 0x03, ODT_REC, &ODObjs.o_2458_acceptanceFilter01, NULL},
    {0x2459, 0x03, ODT_REC, &ODObjs.o_2459_acceptanceFilter10, NULL},
    {0x245A, 0x03, ODT_REC, &ODObjs.o_245A_acceptanceFilter11, NULL},
    {0x245B, 0x01, ODT_VAR, &ODObjs.o_245B_numberOfHomingStarts, NULL},
    {0x2562, 0x01, ODT_VAR, &ODObjs.o_2562_positionDemandInternalValue, NULL},
    {0x257A, 0x01, ODT_VAR, &ODObjs.o_257A_targetPositionInternalValue, NULL},
    {0x257B, 0x03, ODT_ARR, &ODObjs.o_257B_positionRangeLimitInternalValue, NULL},
    {0x257D, 0x03, ODT_REC, &ODObjs.o_257D_softwarePositionLimitInternalValue, NULL},
    {0x2DFF, 0x01, ODT_VAR, &ODObjs.o_2DFF_DFF_Object, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_controlword, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_statusword, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_modesOfOperation, NULL},
    {0x6061, 0x01, ODT_VAR, &ODObjs.o_6061_modesOfOperationDisplay, NULL},
    {0x6062, 0x01, ODT_VAR, &ODObjs.o_6062_positionDemandValue, NULL},
    {0x6063, 0x01, ODT_VAR, &ODObjs.o_6063_positionActualInternalValue, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_positionActualValue, NULL},
    {0x6067, 0x01, ODT_VAR, &ODObjs.o_6067_positionWindow, NULL},
    {0x6068, 0x01, ODT_VAR, &ODObjs.o_6068_positionWindowTime, NULL},
    {0x606B, 0x01, ODT_VAR, &ODObjs.o_606B_velocityDemandValue, NULL},
    {0x606C, 0x01, ODT_VAR, &ODObjs.o_606C_velocityActualValue, NULL},
    {0x606D, 0x01, ODT_VAR, &ODObjs.o_606D_velocityWindow, NULL},
    {0x606E, 0x01, ODT_VAR, &ODObjs.o_606E_velocityWindowTime, NULL},
    {0x606F, 0x01, ODT_VAR, &ODObjs.o_606F_velocityThreshold, NULL},
    {0x6070, 0x01, ODT_VAR, &ODObjs.o_6070_velocityThresholdTime, NULL},
    {0x6078, 0x01, ODT_VAR, &ODObjs.o_6078_currentActualValue, NULL},
    {0x607A, 0x01, ODT_VAR, &ODObjs.o_607A_targetPosition, NULL},
    {0x607B, 0x03, ODT_ARR, &ODObjs.o_607B_positionRangeLimit, NULL},
    {0x607C, 0x01, ODT_VAR, &ODObjs.o_607C_homeOffset, NULL},
    {0x607D, 0x03, ODT_ARR, &ODObjs.o_607D_softwarePositionLimit, NULL},
    {0x607E, 0x01, ODT_VAR, &ODObjs.o_607E_polarity, NULL},
    {0x607F, 0x01, ODT_VAR, &ODObjs.o_607F_maxProfileVelocity, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_profileVelocity, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_profileAcceleration, NULL},
    {0x6084, 0x01, ODT_VAR, &ODObjs.o_6084_profileDeceleration, NULL},
    {0x6085, 0x01, ODT_VAR, &ODObjs.o_6085_quickStopDeceleration, NULL},
    {0x608F, 0x03, ODT_ARR, &ODObjs.o_608F_positionEncoderResolution, NULL},
    {0x6091, 0x03, ODT_ARR, &ODObjs.o_6091_gearRatio, NULL},
    {0x6092, 0x03, ODT_ARR, &ODObjs.o_6092_feedConstant, NULL},
    {0x6093, 0x03, ODT_ARR, &ODObjs.o_6093_positionFactor, NULL},
    {0x6098, 0x01, ODT_VAR, &ODObjs.o_6098_homingMethod, NULL},
    {0x6099, 0x03, ODT_ARR, &ODObjs.o_6099_homingSpeeds, NULL},
    {0x609A, 0x01, ODT_VAR, &ODObjs.o_609A_homingAcceleration, NULL},
    {0x60FA, 0x01, ODT_VAR, &ODObjs.o_60FA_controlEffort, NULL},
    {0x60FD, 0x01, ODT_VAR, &ODObjs.o_60FD_digitalInputs, NULL},
    {0x60FF, 0x01, ODT_VAR, &ODObjs.o_60FF_targetVelocity, NULL},
    {0x6502, 0x01, ODT_VAR, &ODObjs.o_6502_supportedDriveModes, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
