/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: faulhaber_605_3150_71a.eds
        File Version: 0x01

        Created:      2009/11/20 14:37:00
        Created By:   Georg Bende
        Modified:     2009/11/12 14:37:00
        Modified By:  Georg Bende

    Device Info:
        Vendor Name:  Faulhaber
        Vendor ID:    0x00000147
        Product Name: Sinus2
        Product ID:   0x00000000

        Description:  EDS for SinusMotor2
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 2
#define OD_CNT_ARR_1010 3
#define OD_CNT_ARR_1011 3
#define OD_CNT_ARR_1018 4


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_CAN_ControllerType;
    uint8_t x1001_errorRegister;
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[OD_CNT_ARR_1003];
    uint32_t x1005_COB_ID_SYNC;
    uint16_t x100C_guardTime;
    uint8_t x100D_lifeTimeFactor;
    uint8_t x1010_storeParameters_sub0;
    uint8_t x1011_restoreParameters_sub0;
    uint32_t x1014_COB_ID_EmergencyMessage;
    uint8_t x1018_identityObject_sub0;
    uint32_t x1018_identityObject[OD_CNT_ARR_1018];
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_Client_ServerRx;
        uint32_t COB_ID_Server_ClientTx;
    } x1200__1stServerSDO_Parameter;
    struct {
        uint8_t largestSub_IndexSupported;
        uint32_t COB_ID_UsedByPDO;
        uint8_t transmissionType;
    } x1400__1stReceivePDO_Parameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1401__2ndReceivePDOParameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1402__3rdReceivePDO_Parameters;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t PDO_MappingForThe1stApplicationObjectToBeMapped;
    } x1600__1stReceivePDO_Mapping;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t PDO_MappingForThe1stApplicationObjectToBeMapped;
        uint32_t PDO_MappingForThe2ndApplicationObjectToBeMapped;
    } x1601__2ndReceivePDO_Mapping;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t PDO_MappingForThe1stApplicationObjectToBeMapped;
        uint32_t PDO_MappingForThe2ndApplicationObjectToBeMapped;
        uint32_t PDO_MappingForThe3rdApplicationObjectToBeMapped;
        uint32_t PDO_MappingForThe4thApplicationObjectToBeMapped;
        uint32_t PDO_MappingForThe5thApplicationObjectToBeMapped;
    } x1602__3rdReceivePDO_Mapping;
    struct {
        uint8_t largestSub_IndexSupported;
        uint32_t COB_ID_UsedByPDO;
        uint8_t transmissionType;
    } x1800__1stTransmitPDO_Parameter;
    struct {
        uint8_t largestSub_IndexSupported;
        uint32_t COB_ID_UsedByPDO;
        uint8_t transmissionType;
    } x1801__2ndTransmitPDO_Parameter;
    struct {
        uint8_t largestSub_IndexSupported;
        uint32_t COB_ID_UsedByPDO;
        uint8_t transmissionType;
    } x1802__3rdTransmitPDO_Parameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t PDO_MappingForThe1stApplicationObjectToBeMapped;
    } x1A00__1stTransmitPDO_Mapping;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t PDO_MappingForThe1stApplicationObjectToBeMapped;
        uint32_t PDO_MappingForThe2ndApplicationObjectToBeMapped;
        uint32_t PDO_MappingForThe3rdApplicationObjectToBeMapped;
    } x1A01__2ndTransmitPDO_Mapping;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t PDO_MappingForThe1stApplicationObjectToBeMapped;
        uint32_t PDO_MappingForThe2ndApplicationObjectToBeMapped;
    } x1A02__3rdTransmitPDO_Mapping;
    struct {
        uint8_t numberOfEntries;
        uint8_t commandNumber;
        int32_t commandArgument;
    } x2301_DFF_CommandChannel;
    struct {
        uint8_t numberOfEntries;
        int32_t commandResult;
        int8_t errorCode;
    } x2302_DFF_CommandAnswer;
    struct {
        uint8_t numberOfEntries;
        uint8_t _1stBinaryData;
        uint8_t _2ndBinaryData;
        uint8_t timeFlagEnable;
        uint8_t numberOfRequestedPackets;
        uint8_t distanceBetweenRequestedPackets;
    } x2303_traceParameterSettings;
    struct {
        uint8_t numberOfEntries;
    } x2304_binaryAnswer;
    struct {
        uint8_t numberOfEntries;
        uint8_t homingNegativeLimit;
        uint8_t homingPositiveLimit;
        uint8_t homingSwitch;
        uint8_t notifySwitch;
        uint8_t switchPolarity;
        uint8_t switchPolarityEnableInHoming;
    } x2310_switchSettings;
    uint8_t x2311_notifyStatus;
    struct {
        uint8_t numberOfEntries;
        uint16_t internalFaultRegister;
        uint16_t emergencySwitches;
        uint16_t faultSwitches;
        uint16_t errorOutputs;
    } x2320_faults;
    uint16_t x2403_specialSettings;
    uint16_t x2404_serviceSettings;
    uint16_t x6040_controlword;
    int8_t x6060_modesOfOperation;
    int8_t x6061_modesOfOperationDisplay;
    uint32_t x6067_positionWindow;
    uint16_t x6068_positionWindowTime;
    int32_t x606B_velocityDemandValue;
    uint16_t x606D_velocityWindow;
    uint16_t x606E_velocityWindowTime;
    uint16_t x606F_velocityThreshold;
    uint16_t x6070_velocityThresholdTime;
    int32_t x607C_homeOffset;
    struct {
        uint8_t numberOfEntries;
        int32_t negativePositionLimit;
        int32_t positivePositionLimit;
    } x607D_softwarePositionLimit;
    uint8_t x607E_polarity;
    uint32_t x607F_maxProfileVelocity;
    uint32_t x6081_profileVelocity;
    uint32_t x6083_profileAcceleration;
    uint32_t x6084_profileDeceleration;
    uint32_t x6085_quickStopDeceleration;
    int16_t x6086_motionProfileType;
    struct {
        uint8_t numberOfEntries;
        uint32_t encoderIncrements;
        uint32_t motorRevolutions;
    } x608F_positionEncoderResolution;
    struct {
        uint8_t numberOfEntries;
        uint32_t numerator;
        uint32_t divisor;
    } x6093_positionFactor;
    struct {
        uint8_t numberOfEntries;
        uint32_t numerator;
        uint32_t divisor;
    } x6096_velocityFactor;
    struct {
        uint8_t numberOfEntries;
        uint32_t numerator;
        uint32_t divisor;
    } x6097_accelerationFactor;
    int8_t x6098_homingMethod;
    struct {
        uint8_t numberOfEntries;
        uint32_t switchSeekVelocity;
        uint32_t homingVelocity;
    } x6099_homingVelocities;
    uint32_t x609A_homingAcceleration;
    struct {
        uint8_t numberOfEntries;
        uint16_t p;
        uint16_t i;
    } x60F9_velocityControlParameterSet;
    struct {
        uint8_t numberOfEntries;
        uint8_t PP;
        uint8_t PD;
    } x60FB_positionControlParameterSet;
    int32_t x60FF_targetVelocity;
    struct {
        uint8_t numberOfEntries;
        int32_t motorType;
        uint16_t kn;
        uint32_t rm;
    } x6510_driveData;
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1008 &OD->list[4]
#define OD_ENTRY_H1009 &OD->list[5]
#define OD_ENTRY_H100A &OD->list[6]
#define OD_ENTRY_H100C &OD->list[7]
#define OD_ENTRY_H100D &OD->list[8]
#define OD_ENTRY_H1010 &OD->list[9]
#define OD_ENTRY_H1011 &OD->list[10]
#define OD_ENTRY_H1014 &OD->list[11]
#define OD_ENTRY_H1018 &OD->list[12]
#define OD_ENTRY_H1200 &OD->list[13]
#define OD_ENTRY_H1400 &OD->list[14]
#define OD_ENTRY_H1401 &OD->list[15]
#define OD_ENTRY_H1402 &OD->list[16]
#define OD_ENTRY_H1600 &OD->list[17]
#define OD_ENTRY_H1601 &OD->list[18]
#define OD_ENTRY_H1602 &OD->list[19]
#define OD_ENTRY_H1800 &OD->list[20]
#define OD_ENTRY_H1801 &OD->list[21]
#define OD_ENTRY_H1802 &OD->list[22]
#define OD_ENTRY_H1A00 &OD->list[23]
#define OD_ENTRY_H1A01 &OD->list[24]
#define OD_ENTRY_H1A02 &OD->list[25]
#define OD_ENTRY_H2301 &OD->list[26]
#define OD_ENTRY_H2302 &OD->list[27]
#define OD_ENTRY_H2303 &OD->list[28]
#define OD_ENTRY_H2304 &OD->list[29]
#define OD_ENTRY_H2310 &OD->list[30]
#define OD_ENTRY_H2311 &OD->list[31]
#define OD_ENTRY_H2320 &OD->list[32]
#define OD_ENTRY_H2400 &OD->list[33]
#define OD_ENTRY_H2403 &OD->list[34]
#define OD_ENTRY_H2404 &OD->list[35]
#define OD_ENTRY_H6040 &OD->list[36]
#define OD_ENTRY_H6041 &OD->list[37]
#define OD_ENTRY_H6060 &OD->list[38]
#define OD_ENTRY_H6061 &OD->list[39]
#define OD_ENTRY_H6062 &OD->list[40]
#define OD_ENTRY_H6063 &OD->list[41]
#define OD_ENTRY_H6064 &OD->list[42]
#define OD_ENTRY_H6067 &OD->list[43]
#define OD_ENTRY_H6068 &OD->list[44]
#define OD_ENTRY_H6069 &OD->list[45]
#define OD_ENTRY_H606B &OD->list[46]
#define OD_ENTRY_H606C &OD->list[47]
#define OD_ENTRY_H606D &OD->list[48]
#define OD_ENTRY_H606E &OD->list[49]
#define OD_ENTRY_H606F &OD->list[50]
#define OD_ENTRY_H6070 &OD->list[51]
#define OD_ENTRY_H607A &OD->list[52]
#define OD_ENTRY_H607C &OD->list[53]
#define OD_ENTRY_H607D &OD->list[54]
#define OD_ENTRY_H607E &OD->list[55]
#define OD_ENTRY_H607F &OD->list[56]
#define OD_ENTRY_H6081 &OD->list[57]
#define OD_ENTRY_H6083 &OD->list[58]
#define OD_ENTRY_H6084 &OD->list[59]
#define OD_ENTRY_H6085 &OD->list[60]
#define OD_ENTRY_H6086 &OD->list[61]
#define OD_ENTRY_H608F &OD->list[62]
#define OD_ENTRY_H6093 &OD->list[63]
#define OD_ENTRY_H6096 &OD->list[64]
#define OD_ENTRY_H6097 &OD->list[65]
#define OD_ENTRY_H6098 &OD->list[66]
#define OD_ENTRY_H6099 &OD->list[67]
#define OD_ENTRY_H609A &OD->list[68]
#define OD_ENTRY_H60F9 &OD->list[69]
#define OD_ENTRY_H60FA &OD->list[70]
#define OD_ENTRY_H60FB &OD->list[71]
#define OD_ENTRY_H60FC &OD->list[72]
#define OD_ENTRY_H60FF &OD->list[73]
#define OD_ENTRY_H6510 &OD->list[74]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_CAN_ControllerType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNC &OD->list[3]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[4]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[5]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[6]
#define OD_ENTRY_H100C_guardTime &OD->list[7]
#define OD_ENTRY_H100D_lifeTimeFactor &OD->list[8]
#define OD_ENTRY_H1010_storeParameters &OD->list[9]
#define OD_ENTRY_H1011_restoreParameters &OD->list[10]
#define OD_ENTRY_H1014_COB_ID_EmergencyMessage &OD->list[11]
#define OD_ENTRY_H1018_identityObject &OD->list[12]
#define OD_ENTRY_H1200__1stServerSDO_Parameter &OD->list[13]
#define OD_ENTRY_H1400__1stReceivePDO_Parameter &OD->list[14]
#define OD_ENTRY_H1401__2ndReceivePDOParameter &OD->list[15]
#define OD_ENTRY_H1402__3rdReceivePDO_Parameters &OD->list[16]
#define OD_ENTRY_H1600__1stReceivePDO_Mapping &OD->list[17]
#define OD_ENTRY_H1601__2ndReceivePDO_Mapping &OD->list[18]
#define OD_ENTRY_H1602__3rdReceivePDO_Mapping &OD->list[19]
#define OD_ENTRY_H1800__1stTransmitPDO_Parameter &OD->list[20]
#define OD_ENTRY_H1801__2ndTransmitPDO_Parameter &OD->list[21]
#define OD_ENTRY_H1802__3rdTransmitPDO_Parameter &OD->list[22]
#define OD_ENTRY_H1A00__1stTransmitPDO_Mapping &OD->list[23]
#define OD_ENTRY_H1A01__2ndTransmitPDO_Mapping &OD->list[24]
#define OD_ENTRY_H1A02__3rdTransmitPDO_Mapping &OD->list[25]
#define OD_ENTRY_H2301_DFF_CommandChannel &OD->list[26]
#define OD_ENTRY_H2302_DFF_CommandAnswer &OD->list[27]
#define OD_ENTRY_H2303_traceParameterSettings &OD->list[28]
#define OD_ENTRY_H2304_binaryAnswer &OD->list[29]
#define OD_ENTRY_H2310_switchSettings &OD->list[30]
#define OD_ENTRY_H2311_notifyStatus &OD->list[31]
#define OD_ENTRY_H2320_faults &OD->list[32]
#define OD_ENTRY_H2400_baudrate &OD->list[33]
#define OD_ENTRY_H2403_specialSettings &OD->list[34]
#define OD_ENTRY_H2404_serviceSettings &OD->list[35]
#define OD_ENTRY_H6040_controlword &OD->list[36]
#define OD_ENTRY_H6041_statusword &OD->list[37]
#define OD_ENTRY_H6060_modesOfOperation &OD->list[38]
#define OD_ENTRY_H6061_modesOfOperationDisplay &OD->list[39]
#define OD_ENTRY_H6062_positionDemandValue &OD->list[40]
#define OD_ENTRY_H6063_positionActualValueInternalUnits &OD->list[41]
#define OD_ENTRY_H6064_positionActualValue &OD->list[42]
#define OD_ENTRY_H6067_positionWindow &OD->list[43]
#define OD_ENTRY_H6068_positionWindowTime &OD->list[44]
#define OD_ENTRY_H6069_velocitySensorActualValue &OD->list[45]
#define OD_ENTRY_H606B_velocityDemandValue &OD->list[46]
#define OD_ENTRY_H606C_velocityActualValue &OD->list[47]
#define OD_ENTRY_H606D_velocityWindow &OD->list[48]
#define OD_ENTRY_H606E_velocityWindowTime &OD->list[49]
#define OD_ENTRY_H606F_velocityThreshold &OD->list[50]
#define OD_ENTRY_H6070_velocityThresholdTime &OD->list[51]
#define OD_ENTRY_H607A_targetPosition &OD->list[52]
#define OD_ENTRY_H607C_homeOffset &OD->list[53]
#define OD_ENTRY_H607D_softwarePositionLimit &OD->list[54]
#define OD_ENTRY_H607E_polarity &OD->list[55]
#define OD_ENTRY_H607F_maxProfileVelocity &OD->list[56]
#define OD_ENTRY_H6081_profileVelocity &OD->list[57]
#define OD_ENTRY_H6083_profileAcceleration &OD->list[58]
#define OD_ENTRY_H6084_profileDeceleration &OD->list[59]
#define OD_ENTRY_H6085_quickStopDeceleration &OD->list[60]
#define OD_ENTRY_H6086_motionProfileType &OD->list[61]
#define OD_ENTRY_H608F_positionEncoderResolution &OD->list[62]
#define OD_ENTRY_H6093_positionFactor &OD->list[63]
#define OD_ENTRY_H6096_velocityFactor &OD->list[64]
#define OD_ENTRY_H6097_accelerationFactor &OD->list[65]
#define OD_ENTRY_H6098_homingMethod &OD->list[66]
#define OD_ENTRY_H6099_homingVelocities &OD->list[67]
#define OD_ENTRY_H609A_homingAcceleration &OD->list[68]
#define OD_ENTRY_H60F9_velocityControlParameterSet &OD->list[69]
#define OD_ENTRY_H60FA_controlEffort &OD->list[70]
#define OD_ENTRY_H60FB_positionControlParameterSet &OD->list[71]
#define OD_ENTRY_H60FC_positionDemandValue &OD->list[72]
#define OD_ENTRY_H60FF_targetVelocity &OD->list[73]
#define OD_ENTRY_H6510_driveData &OD->list[74]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = 0;\
    (config).ENTRY_H1017 = NULL;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = 0;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = 0;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = 0;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
