/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1000_deviceType = 0x00030191,
    .x1001_errorRegister = 0x00,
    .x1003_pre_definedErrorField_sub0 = 0x00,
    .x1003_pre_definedErrorField = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1005_COB_ID_SYNC = 0x00000080,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1008_manufacturerDeviceName = {'C', 'A', 'N', 'o', 'p', 'e', 'n', ' ', 'I', 'O', '-', 'X', '1', 0},
    .x1009_manufacturerHardwareVersion = {'4', '1', '4', '0', '.', '2', '-', '0', 0},
    .x100A_manufacturerSoftwareVersion = {'V', '1', '.', '3', '3', ' ', '/', ' ', 'V', '5', '.', '3', '8', 0},
    .x100C_guardTime = 0x0000,
    .x100D_lifeTimeFactor = 0x00,
    .x1010_storeParameters_sub0 = 0x01,
    .x1011_restoreDefaultParameters_sub0 = 0x01,
    .x1014_COB_ID_EmergencyMessage = 0x00000080,
    .x1016_consumerHeartbeatTime_sub0 = 0x05,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identityObject = {
        .numberOfEntries = 0x04,
        .vendor_ID = 0x0000003F,
        .productCode = 0x002DCAA8,
        .revisionNumber = 0x01330538
    },
    .x1029_errorBehaviour_sub0 = 0x01,
    .x1029_errorBehaviour = {0x00},
    .x1200__1ServerSDO_Parameter = {
        .numberOfEntries = 0x02,
        .COB_ID_Client_ServerRx = 0x00000600,
        .COD_ID_Server_ClientTx = 0x00000580
    },
    .x1400__1ReceivePDOParameter = {
        .largestSub_IndexSupported = 0x05,
        .COB_IdUsedByPDO = 0x00000200,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0000,
        .eventtimer = 0x0000
    },
    .x1401__2ReceivePDOParameter = {
        .largestSub_IndexSupported = 0x05,
        .COB_ID_UsedByPDO = 0x80000300,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0000,
        .eventtimer = 0x0000
    },
    .x1600__1ReceivePDO_MappingParameter = {
        .numberOfMappedObjects = 0x01,
        .PDO_Mapping1AppObject = 0x62000108,
        .PDO_Mapping2AppObject = 0x00000000,
        .PDO_Mapping3AppObject = 0x00000000,
        .PDO_Mapping4AppObject = 0x00000000,
        .PDO_Mapping5AppObject = 0x00000000,
        .PDO_Mapping6AppObject = 0x00000000,
        .PDO_Mapping7AppObject = 0x00000000,
        .PDO_Mapping8AppObject = 0x00000000
    },
    .x1601__2ReceivePDO_MappingParameter = {
        .numberOfMappedObjects = 0x00,
        .PDO_Mapping1AppObject = 0x00000000,
        .PDO_Mapping2AppObject = 0x00000000,
        .PDO_Mapping3AppObject = 0x00000000,
        .PDO_Mapping4AppObject = 0x00000000,
        .PDO_Mapping5AppObject = 0x00000000,
        .PDO_Mapping6AppObject = 0x00000000,
        .PDO_Mapping7AppObject = 0x00000000,
        .PDO_Mapping8AppObject = 0x00000000
    },
    .x1800__1TransmitPDO_Parameter = {
        .largestSub_IndexSupported = 0x05,
        .COB_ID_UsedByPDO = 0x00000180,
        .transmissionType = 0xFF,
        .inhibitTime = 0x01F4,
        .eventtimer = 0x0000
    },
    .x1801__2TransmitPDO_Parameter = {
        .largestSub_IndexSupported = 0x05,
        .COB_ID_UsedByPDO = 0x80000280,
        .transmissionType = 0xFF,
        .inhibitTime = 0x01F4,
        .eventtimer = 0x0000
    },
    .x1A00__1TransmitPDO_MappingParameter = {
        .numberOfMappedObjectsInPDO = 0x02,
        .PDO_Mapping1AppObject = 0x60000108,
        .PDO_Mapping2AppObject = 0x60000208,
        .PDO_Mapping3AppObject = 0x00000000,
        .PDO_Mapping4AppObject = 0x00000000,
        .PDO_Mapping5AppObject = 0x00000000,
        .PDO_Mapping6AppObject = 0x00000000,
        .PDO_Mapping7AppObject = 0x00000000,
        .PDO_Mapping8AppObject = 0x00000000
    },
    .x1A01__2TransmitPDO_MappingParameter = {
        .numberOfMappedObjectsInPDO = 0x00,
        .PDO_Mapping1AppObject = 0x00000000,
        .PDO_Mapping2AppObject = 0x00000000,
        .PDO_Mapping3AppObject = 0x00000000,
        .PDO_Mapping4AppObject = 0x00000000,
        .PDO_Mapping5AppObject = 0x00000000,
        .PDO_Mapping6AppObject = 0x00000000,
        .PDO_Mapping7AppObject = 0x00000000,
        .PDO_Mapping8AppObject = 0x00000000
    },
    .x1F51_programControl_sub0 = 0x01,
    .x2000_NMT_BootNetwork = {
        .numberOfEntries = 0x02,
        .NMT_BootEnable = 0x00,
        .NMT_StartTime = 0x01F4
    },
    .x2001_deviceFeatures_sub0 = 0x02,
    .x2002_powerFailConfiguration = {
        .numberOfEntries = 0x01,
        .powerFailInterruptEnable = 0x01
    },
    .x2010_disableInput8Bit_sub0 = 0x02,
    .x2010_disableInput8Bit = {0x00, 0x00},
    .x2011_enablePulsedDigitalOutput8_Bit_sub0 = 0x01,
    .x2011_enablePulsedDigitalOutput8_Bit = {0x00},
    .x2012_enableRetriggerPulsedDigitalOutput8_Bit_sub0 = 0x01,
    .x2012_enableRetriggerPulsedDigitalOutput8_Bit = {0x00},
    .x2013_enableActiveOffPulsedDigitalOutput8_Bit_sub0 = 0x01,
    .x2013_enableActiveOffPulsedDigitalOutput8_Bit = {0x00},
    .x2014_pulselengthPulsedDigitalOutput_sub0 = 0x08,
    .x2014_pulselengthPulsedDigitalOutput = {0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000},
    .x2500_forProductionOnly = {
        .numberOfEntries = 0x26
    },
    .x6000_readInput8Bit_sub0 = 0x02,
    .x6000_readInput8Bit = {0x00, 0x00},
    .x6003_filterConstantInput8Bit_sub0 = 0x02,
    .x6003_filterConstantInput8Bit = {0x00, 0x00},
    .x6005_globalInterruptEnableDigital8Bit = true,
    .x6006_interruptMaskAnyChange8Bit_sub0 = 0x02,
    .x6006_interruptMaskAnyChange8Bit = {0xFF, 0xFF},
    .x6007_interruptMaskLowToHigh8Bit_sub0 = 0x02,
    .x6007_interruptMaskLowToHigh8Bit = {0x00, 0x00},
    .x6008_interruptMaskHighToLow8Bit_sub0 = 0x02,
    .x6008_interruptMaskHighToLow8Bit = {0x00, 0x00},
    .x6200_writeOutput8Bit_sub0 = 0x01,
    .x6200_writeOutput8Bit = {0x00},
    .x6206_errorModeOutput8_Bit_sub0 = 0x01,
    .x6206_errorModeOutput8_Bit = {0xFF},
    .x6207_errorValueOutput8_Bit_sub0 = 0x01,
    .x6207_errorValueOutput8_Bit = {0x00},
    .x6208_filterConstantOutput8Bit_sub0 = 0x01,
    .x6208_filterConstantOutput8Bit = {0xFF}
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNC;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_100C_guardTime;
    OD_obj_var_t o_100D_lifeTimeFactor;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1014_COB_ID_EmergencyMessage;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identityObject[5];
    OD_obj_array_t o_1029_errorBehaviour;
    OD_obj_record_t o_1200__1ServerSDO_Parameter[3];
    OD_obj_record_t o_1400__1ReceivePDOParameter[5];
    OD_obj_record_t o_1401__2ReceivePDOParameter[5];
    OD_obj_record_t o_1600__1ReceivePDO_MappingParameter[9];
    OD_obj_record_t o_1601__2ReceivePDO_MappingParameter[9];
    OD_obj_record_t o_1800__1TransmitPDO_Parameter[5];
    OD_obj_record_t o_1801__2TransmitPDO_Parameter[5];
    OD_obj_record_t o_1A00__1TransmitPDO_MappingParameter[9];
    OD_obj_record_t o_1A01__2TransmitPDO_MappingParameter[9];
    OD_obj_array_t o_1F51_programControl;
    OD_obj_record_t o_2000_NMT_BootNetwork[3];
    OD_obj_array_t o_2001_deviceFeatures;
    OD_obj_record_t o_2002_powerFailConfiguration[2];
    OD_obj_array_t o_2010_disableInput8Bit;
    OD_obj_array_t o_2011_enablePulsedDigitalOutput8_Bit;
    OD_obj_array_t o_2012_enableRetriggerPulsedDigitalOutput8_Bit;
    OD_obj_array_t o_2013_enableActiveOffPulsedDigitalOutput8_Bit;
    OD_obj_array_t o_2014_pulselengthPulsedDigitalOutput;
    OD_obj_record_t o_2500_forProductionOnly[7];
    OD_obj_array_t o_6000_readInput8Bit;
    OD_obj_array_t o_6003_filterConstantInput8Bit;
    OD_obj_var_t o_6005_globalInterruptEnableDigital8Bit;
    OD_obj_array_t o_6006_interruptMaskAnyChange8Bit;
    OD_obj_array_t o_6007_interruptMaskLowToHigh8Bit;
    OD_obj_array_t o_6008_interruptMaskHighToLow8Bit;
    OD_obj_array_t o_6200_writeOutput8Bit;
    OD_obj_array_t o_6206_errorModeOutput8_Bit;
    OD_obj_array_t o_6207_errorValueOutput8_Bit;
    OD_obj_array_t o_6208_filterConstantOutput8Bit;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_RAM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = &OD_RAM.x1003_pre_definedErrorField_sub0,
        .dataOrig = &OD_RAM.x1003_pre_definedErrorField[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNC = {
        .dataOrig = &OD_RAM.x1005_COB_ID_SYNC,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_RAM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &OD_RAM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 13
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &OD_RAM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 8
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &OD_RAM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 13
    },
    .o_100C_guardTime = {
        .dataOrig = &OD_RAM.x100C_guardTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_100D_lifeTimeFactor = {
        .dataOrig = &OD_RAM.x100D_lifeTimeFactor,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1014_COB_ID_EmergencyMessage = {
        .dataOrig = &OD_RAM.x1014_COB_ID_EmergencyMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_RAM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_RAM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_RAM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identityObject = {
        {
            .dataOrig = &OD_RAM.x1018_identityObject.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1018_identityObject.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identityObject.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identityObject.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1029_errorBehaviour = {
        .dataOrig0 = &OD_RAM.x1029_errorBehaviour_sub0,
        .dataOrig = &OD_RAM.x1029_errorBehaviour[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_1200__1ServerSDO_Parameter = {
        {
            .dataOrig = &OD_RAM.x1200__1ServerSDO_Parameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200__1ServerSDO_Parameter.COB_ID_Client_ServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200__1ServerSDO_Parameter.COD_ID_Server_ClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400__1ReceivePDOParameter = {
        {
            .dataOrig = &OD_RAM.x1400__1ReceivePDOParameter.largestSub_IndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400__1ReceivePDOParameter.COB_IdUsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1400__1ReceivePDOParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400__1ReceivePDOParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1400__1ReceivePDOParameter.eventtimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401__2ReceivePDOParameter = {
        {
            .dataOrig = &OD_RAM.x1401__2ReceivePDOParameter.largestSub_IndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401__2ReceivePDOParameter.COB_ID_UsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1401__2ReceivePDOParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401__2ReceivePDOParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1401__2ReceivePDOParameter.eventtimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600__1ReceivePDO_MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.PDO_Mapping1AppObject,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.PDO_Mapping2AppObject,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.PDO_Mapping3AppObject,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.PDO_Mapping4AppObject,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.PDO_Mapping5AppObject,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.PDO_Mapping6AppObject,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.PDO_Mapping7AppObject,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600__1ReceivePDO_MappingParameter.PDO_Mapping8AppObject,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601__2ReceivePDO_MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.PDO_Mapping1AppObject,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.PDO_Mapping2AppObject,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.PDO_Mapping3AppObject,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.PDO_Mapping4AppObject,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.PDO_Mapping5AppObject,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.PDO_Mapping6AppObject,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.PDO_Mapping7AppObject,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601__2ReceivePDO_MappingParameter.PDO_Mapping8AppObject,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800__1TransmitPDO_Parameter = {
        {
            .dataOrig = &OD_RAM.x1800__1TransmitPDO_Parameter.largestSub_IndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800__1TransmitPDO_Parameter.COB_ID_UsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1800__1TransmitPDO_Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800__1TransmitPDO_Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1800__1TransmitPDO_Parameter.eventtimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1801__2TransmitPDO_Parameter = {
        {
            .dataOrig = &OD_RAM.x1801__2TransmitPDO_Parameter.largestSub_IndexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801__2TransmitPDO_Parameter.COB_ID_UsedByPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1801__2TransmitPDO_Parameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801__2TransmitPDO_Parameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1801__2TransmitPDO_Parameter.eventtimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1A00__1TransmitPDO_MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.numberOfMappedObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.PDO_Mapping1AppObject,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.PDO_Mapping2AppObject,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.PDO_Mapping3AppObject,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.PDO_Mapping4AppObject,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.PDO_Mapping5AppObject,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.PDO_Mapping6AppObject,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.PDO_Mapping7AppObject,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00__1TransmitPDO_MappingParameter.PDO_Mapping8AppObject,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01__2TransmitPDO_MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.numberOfMappedObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.PDO_Mapping1AppObject,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.PDO_Mapping2AppObject,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.PDO_Mapping3AppObject,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.PDO_Mapping4AppObject,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.PDO_Mapping5AppObject,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.PDO_Mapping6AppObject,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.PDO_Mapping7AppObject,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01__2TransmitPDO_MappingParameter.PDO_Mapping8AppObject,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1F51_programControl = {
        .dataOrig0 = &OD_RAM.x1F51_programControl_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2000_NMT_BootNetwork = {
        {
            .dataOrig = &OD_RAM.x2000_NMT_BootNetwork.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2000_NMT_BootNetwork.NMT_BootEnable,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2000_NMT_BootNetwork.NMT_StartTime,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_2001_deviceFeatures = {
        .dataOrig0 = &OD_RAM.x2001_deviceFeatures_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_2002_powerFailConfiguration = {
        {
            .dataOrig = &OD_RAM.x2002_powerFailConfiguration.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x2002_powerFailConfiguration.powerFailInterruptEnable,
            .subIndex = 1,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_2010_disableInput8Bit = {
        .dataOrig0 = &OD_RAM.x2010_disableInput8Bit_sub0,
        .dataOrig = &OD_RAM.x2010_disableInput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2011_enablePulsedDigitalOutput8_Bit = {
        .dataOrig0 = &OD_RAM.x2011_enablePulsedDigitalOutput8_Bit_sub0,
        .dataOrig = &OD_RAM.x2011_enablePulsedDigitalOutput8_Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2012_enableRetriggerPulsedDigitalOutput8_Bit = {
        .dataOrig0 = &OD_RAM.x2012_enableRetriggerPulsedDigitalOutput8_Bit_sub0,
        .dataOrig = &OD_RAM.x2012_enableRetriggerPulsedDigitalOutput8_Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2013_enableActiveOffPulsedDigitalOutput8_Bit = {
        .dataOrig0 = &OD_RAM.x2013_enableActiveOffPulsedDigitalOutput8_Bit_sub0,
        .dataOrig = &OD_RAM.x2013_enableActiveOffPulsedDigitalOutput8_Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2014_pulselengthPulsedDigitalOutput = {
        .dataOrig0 = &OD_RAM.x2014_pulselengthPulsedDigitalOutput_sub0,
        .dataOrig = &OD_RAM.x2014_pulselengthPulsedDigitalOutput[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_2500_forProductionOnly = {
        {
            .dataOrig = &OD_RAM.x2500_forProductionOnly.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_W | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 36,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 37,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 38,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        }
    },
    .o_6000_readInput8Bit = {
        .dataOrig0 = &OD_RAM.x6000_readInput8Bit_sub0,
        .dataOrig = &OD_RAM.x6000_readInput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6003_filterConstantInput8Bit = {
        .dataOrig0 = &OD_RAM.x6003_filterConstantInput8Bit_sub0,
        .dataOrig = &OD_RAM.x6003_filterConstantInput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6005_globalInterruptEnableDigital8Bit = {
        .dataOrig = &OD_RAM.x6005_globalInterruptEnableDigital8Bit,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6006_interruptMaskAnyChange8Bit = {
        .dataOrig0 = &OD_RAM.x6006_interruptMaskAnyChange8Bit_sub0,
        .dataOrig = &OD_RAM.x6006_interruptMaskAnyChange8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6007_interruptMaskLowToHigh8Bit = {
        .dataOrig0 = &OD_RAM.x6007_interruptMaskLowToHigh8Bit_sub0,
        .dataOrig = &OD_RAM.x6007_interruptMaskLowToHigh8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6008_interruptMaskHighToLow8Bit = {
        .dataOrig0 = &OD_RAM.x6008_interruptMaskHighToLow8Bit_sub0,
        .dataOrig = &OD_RAM.x6008_interruptMaskHighToLow8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6200_writeOutput8Bit = {
        .dataOrig0 = &OD_RAM.x6200_writeOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x6200_writeOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6206_errorModeOutput8_Bit = {
        .dataOrig0 = &OD_RAM.x6206_errorModeOutput8_Bit_sub0,
        .dataOrig = &OD_RAM.x6206_errorModeOutput8_Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6207_errorValueOutput8_Bit = {
        .dataOrig0 = &OD_RAM.x6207_errorValueOutput8_Bit_sub0,
        .dataOrig = &OD_RAM.x6207_errorValueOutput8_Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6208_filterConstantOutput8Bit = {
        .dataOrig0 = &OD_RAM.x6208_filterConstantOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x6208_filterConstantOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x0B, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNC, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x100C, 0x01, ODT_VAR, &ODObjs.o_100C_guardTime, NULL},
    {0x100D, 0x01, ODT_VAR, &ODObjs.o_100D_lifeTimeFactor, NULL},
    {0x1010, 0x02, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x02, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EmergencyMessage, NULL},
    {0x1016, 0x06, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identityObject, NULL},
    {0x1029, 0x02, ODT_ARR, &ODObjs.o_1029_errorBehaviour, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200__1ServerSDO_Parameter, NULL},
    {0x1400, 0x05, ODT_REC, &ODObjs.o_1400__1ReceivePDOParameter, NULL},
    {0x1401, 0x05, ODT_REC, &ODObjs.o_1401__2ReceivePDOParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600__1ReceivePDO_MappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601__2ReceivePDO_MappingParameter, NULL},
    {0x1800, 0x05, ODT_REC, &ODObjs.o_1800__1TransmitPDO_Parameter, NULL},
    {0x1801, 0x05, ODT_REC, &ODObjs.o_1801__2TransmitPDO_Parameter, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00__1TransmitPDO_MappingParameter, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01__2TransmitPDO_MappingParameter, NULL},
    {0x1F51, 0x02, ODT_ARR, &ODObjs.o_1F51_programControl, NULL},
    {0x2000, 0x03, ODT_REC, &ODObjs.o_2000_NMT_BootNetwork, NULL},
    {0x2001, 0x03, ODT_ARR, &ODObjs.o_2001_deviceFeatures, NULL},
    {0x2002, 0x02, ODT_REC, &ODObjs.o_2002_powerFailConfiguration, NULL},
    {0x2010, 0x03, ODT_ARR, &ODObjs.o_2010_disableInput8Bit, NULL},
    {0x2011, 0x02, ODT_ARR, &ODObjs.o_2011_enablePulsedDigitalOutput8_Bit, NULL},
    {0x2012, 0x02, ODT_ARR, &ODObjs.o_2012_enableRetriggerPulsedDigitalOutput8_Bit, NULL},
    {0x2013, 0x02, ODT_ARR, &ODObjs.o_2013_enableActiveOffPulsedDigitalOutput8_Bit, NULL},
    {0x2014, 0x09, ODT_ARR, &ODObjs.o_2014_pulselengthPulsedDigitalOutput, NULL},
    {0x2500, 0x07, ODT_REC, &ODObjs.o_2500_forProductionOnly, NULL},
    {0x6000, 0x03, ODT_ARR, &ODObjs.o_6000_readInput8Bit, NULL},
    {0x6003, 0x03, ODT_ARR, &ODObjs.o_6003_filterConstantInput8Bit, NULL},
    {0x6005, 0x01, ODT_VAR, &ODObjs.o_6005_globalInterruptEnableDigital8Bit, NULL},
    {0x6006, 0x03, ODT_ARR, &ODObjs.o_6006_interruptMaskAnyChange8Bit, NULL},
    {0x6007, 0x03, ODT_ARR, &ODObjs.o_6007_interruptMaskLowToHigh8Bit, NULL},
    {0x6008, 0x03, ODT_ARR, &ODObjs.o_6008_interruptMaskHighToLow8Bit, NULL},
    {0x6200, 0x02, ODT_ARR, &ODObjs.o_6200_writeOutput8Bit, NULL},
    {0x6206, 0x02, ODT_ARR, &ODObjs.o_6206_errorModeOutput8_Bit, NULL},
    {0x6207, 0x02, ODT_ARR, &ODObjs.o_6207_errorValueOutput8_Bit, NULL},
    {0x6208, 0x02, ODT_ARR, &ODObjs.o_6208_filterConstantOutput8Bit, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
