/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1003_pre_definedErrorField_sub0 = 0x03,
    .x1003_pre_definedErrorField = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1008_manufacturerDeviceName = {'T', 'E', 'S', 'T', ' ', 'D', 'E', 'V', 'I', 'C', 'E', 0},
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identityObject = {
        .highestSub_indexSupported = 0x04
    },
    .x1400_receivePDO0CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_IDUseByRPDO1 = 0x00000200,
        .transmissionTypeRPDO1 = 0xFF
    },
    .x1401_receivePDO1CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_IDUseByRPDO2 = 0x00000300,
        .transmissionTypeRPDO2 = 0xFF
    },
    .x1402_receivePDO2CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_IDUseByRPDO3 = 0x00000400,
        .transmissionTypeRPDO3 = 0xFF
    },
    .x1403_receivePDO3CommunicationParameter = {
        .numberOfEntries = 0x02,
        .COB_IDUseByRPDO4 = 0x00000500,
        .transmissionTypeRPDO4 = 0xFF
    },
    .x1600_receivePDO0MappingParameter = {
        .numberOfMappedObjectsRPDO1 = 0x01,
        .RPDO1MappingInformation1 = 0x60400010,
        .RPDO1MappingInformation2 = 0x00000000,
        .RPDO1MappingInformation3 = 0x00000000,
        .RPDO1MappingInformation4 = 0x00000000
    },
    .x1601_receivePDO1MappingParameter = {
        .numberOfMappedObjectsRPDO2 = 0x02,
        .RPDO2MappingInformation1 = 0x60400010,
        .RPDO2MappingInformation2 = 0x60600008,
        .RPDO2MappingInformation3 = 0x00000000,
        .RPDO2MappingInformation4 = 0x00000000
    },
    .x1602_receivePDO2MappingParameter = {
        .numberOfMappedObjectsRPDO3 = 0x02,
        .RPDO3MappingInformation1 = 0x60400010,
        .RPDO3MappingInformation2 = 0x607A0020,
        .RPDO3MappingInformation3 = 0x00000000,
        .RPDO3MappingInformation4 = 0x00000000
    },
    .x1603_receivePDO3MappingParameter = {
        .numberOfMappedObjectsRPDO4 = 0x02,
        .RPDO4MappingInformation1 = 0x60400010,
        .RPDO4MappingInformation2 = 0x60FF0020,
        .RPDO4MappingInformation3 = 0x00000000,
        .RPDO4MappingInformation4 = 0x00000000
    },
    .x1800_transmitPDO0CommunicationParameters = {
        .numberOfEntries = 0x02,
        .COB_IDUseByTPDO1 = 0x00000180,
        .transmissionTypeTPDO1 = 0xFF
    },
    .x1801_transmitPDO1CommunicationParameters = {
        .numberOfEntries = 0x02,
        .COB_IDUseByTPDO2 = 0x00000280,
        .transmissionTypeTPDO2 = 0xFF
    },
    .x1802_transmitPDO2CommunicationParameters = {
        .numberOfEntries = 0x02,
        .COB_IDUseByTPDO3 = 0x00000380,
        .transmissionTypeTPDO3 = 0x00
    },
    .x1803_transmitPDO3CommunicationParameters = {
        .numberOfEntries = 0x02,
        .COB_IDUseByTPDO4 = 0x00000480,
        .transmissionTypeTPDO4 = 0x00
    },
    .x1A00_transmitPDO0MappingParameter = {
        .numberOfMappedObjectsTPDO1 = 0x01,
        .TPDO1MappingInformation1 = 0x60410010,
        .TPDO1MappingInformation2 = 0x00000000,
        .TPDO1MappingInformation3 = 0x00000000,
        .TPDO1MappingInformation4 = 0x00000000
    },
    .x1A01_transmitPDO1MappingParameter = {
        .numberOfMappedObjectsTPDO2 = 0x02,
        .TPDO2MappingInformation1 = 0x60410010,
        .TPDO2MappingInformation2 = 0x60610008,
        .TPDO2MappingInformation3 = 0x00000000,
        .TPDO2MappingInformation4 = 0x00000000
    },
    .x1A02_transmitPDO2MappingParameter = {
        .numberOfMappedObjectsTPDO3 = 0x02,
        .TPDO3MappingInformation1 = 0x60410010,
        .TPDO3MappingInformation2 = 0x60640020,
        .TPDO3MappingInformation3 = 0x00000000,
        .TPDO3MappingInformation4 = 0x00000000
    },
    .x1A03_transmitPDO3MappingParameter = {
        .numberOfMappedObjectsTPDO4 = 0x02,
        .TPDO4MappingInformation1 = 0x60410010,
        .TPDO4MappingInformation2 = 0x606C0020,
        .TPDO4MappingInformation3 = 0x00000000,
        .TPDO4MappingInformation4 = 0x00000000
    },
    .x3002_sensorSamplingRateHz = 5.2,
    .x3004_sensorStatus_sub0 = 0x03,
    .x3006_valve1Open_sub0 = 0x18,
    .x3050_EDSFileExtensions = {
        .highestSubindex = 0x02
    }
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identityObject[4];
    OD_obj_record_t o_1400_receivePDO0CommunicationParameter[3];
    OD_obj_record_t o_1401_receivePDO1CommunicationParameter[3];
    OD_obj_record_t o_1402_receivePDO2CommunicationParameter[3];
    OD_obj_record_t o_1403_receivePDO3CommunicationParameter[3];
    OD_obj_record_t o_1600_receivePDO0MappingParameter[5];
    OD_obj_record_t o_1601_receivePDO1MappingParameter[5];
    OD_obj_record_t o_1602_receivePDO2MappingParameter[5];
    OD_obj_record_t o_1603_receivePDO3MappingParameter[5];
    OD_obj_record_t o_1800_transmitPDO0CommunicationParameters[3];
    OD_obj_record_t o_1801_transmitPDO1CommunicationParameters[3];
    OD_obj_record_t o_1802_transmitPDO2CommunicationParameters[3];
    OD_obj_record_t o_1803_transmitPDO3CommunicationParameters[3];
    OD_obj_record_t o_1A00_transmitPDO0MappingParameter[5];
    OD_obj_record_t o_1A01_transmitPDO1MappingParameter[5];
    OD_obj_record_t o_1A02_transmitPDO2MappingParameter[5];
    OD_obj_record_t o_1A03_transmitPDO3MappingParameter[5];
    OD_obj_var_t o_2000_writableString;
    OD_obj_var_t o_2001_INTEGER16Value;
    OD_obj_var_t o_2002_UNSIGNED8Value;
    OD_obj_var_t o_2003_INTEGER8Value;
    OD_obj_var_t o_2004_INTEGER32Value;
    OD_obj_var_t o_2005_BOOLEANValue;
    OD_obj_var_t o_2006_BOOLEANValue2;
    OD_obj_var_t o_2020_complexDataType;
    OD_obj_var_t o_3002_sensorSamplingRateHz;
    OD_obj_array_t o_3004_sensorStatus;
    OD_obj_array_t o_3006_valve1Open;
    OD_obj_var_t o_3020_INTEGER8OnlyPositiveValues;
    OD_obj_var_t o_3021_UNSIGNED8ValueRange2To10;
    OD_obj_var_t o_3030_INTEGER32OnlyNegativeValues;
    OD_obj_var_t o_3040_INTEGER64ValueRange_10To10;
    OD_obj_record_t o_3050_EDSFileExtensions[3];
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = &OD_RAM.x1003_pre_definedErrorField_sub0,
        .dataOrig = &OD_RAM.x1003_pre_definedErrorField[0],
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &OD_RAM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 11
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_RAM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identityObject = {
        {
            .dataOrig = &OD_RAM.x1018_identityObject.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_receivePDO0CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1400_receivePDO0CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO0CommunicationParameter.COB_IDUseByRPDO1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO0CommunicationParameter.transmissionTypeRPDO1,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1401_receivePDO1CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1401_receivePDO1CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO1CommunicationParameter.COB_IDUseByRPDO2,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO1CommunicationParameter.transmissionTypeRPDO2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1402_receivePDO2CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1402_receivePDO2CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO2CommunicationParameter.COB_IDUseByRPDO3,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1402_receivePDO2CommunicationParameter.transmissionTypeRPDO3,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1403_receivePDO3CommunicationParameter = {
        {
            .dataOrig = &OD_RAM.x1403_receivePDO3CommunicationParameter.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO3CommunicationParameter.COB_IDUseByRPDO4,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1403_receivePDO3CommunicationParameter.transmissionTypeRPDO4,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_receivePDO0MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1600_receivePDO0MappingParameter.numberOfMappedObjectsRPDO1,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO0MappingParameter.RPDO1MappingInformation1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO0MappingParameter.RPDO1MappingInformation2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO0MappingParameter.RPDO1MappingInformation3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1600_receivePDO0MappingParameter.RPDO1MappingInformation4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_receivePDO1MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1601_receivePDO1MappingParameter.numberOfMappedObjectsRPDO2,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO1MappingParameter.RPDO2MappingInformation1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO1MappingParameter.RPDO2MappingInformation2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO1MappingParameter.RPDO2MappingInformation3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1601_receivePDO1MappingParameter.RPDO2MappingInformation4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_receivePDO2MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1602_receivePDO2MappingParameter.numberOfMappedObjectsRPDO3,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO2MappingParameter.RPDO3MappingInformation1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO2MappingParameter.RPDO3MappingInformation2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO2MappingParameter.RPDO3MappingInformation3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1602_receivePDO2MappingParameter.RPDO3MappingInformation4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_receivePDO3MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1603_receivePDO3MappingParameter.numberOfMappedObjectsRPDO4,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO3MappingParameter.RPDO4MappingInformation1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO3MappingParameter.RPDO4MappingInformation2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO3MappingParameter.RPDO4MappingInformation3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1603_receivePDO3MappingParameter.RPDO4MappingInformation4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_transmitPDO0CommunicationParameters = {
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO0CommunicationParameters.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO0CommunicationParameters.COB_IDUseByTPDO1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO0CommunicationParameters.transmissionTypeTPDO1,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_transmitPDO1CommunicationParameters = {
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO1CommunicationParameters.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO1CommunicationParameters.COB_IDUseByTPDO2,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO1CommunicationParameters.transmissionTypeTPDO2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_transmitPDO2CommunicationParameters = {
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO2CommunicationParameters.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO2CommunicationParameters.COB_IDUseByTPDO3,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1802_transmitPDO2CommunicationParameters.transmissionTypeTPDO3,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_transmitPDO3CommunicationParameters = {
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO3CommunicationParameters.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO3CommunicationParameters.COB_IDUseByTPDO4,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1803_transmitPDO3CommunicationParameters.transmissionTypeTPDO4,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_transmitPDO0MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO0MappingParameter.numberOfMappedObjectsTPDO1,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO0MappingParameter.TPDO1MappingInformation1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO0MappingParameter.TPDO1MappingInformation2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO0MappingParameter.TPDO1MappingInformation3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_transmitPDO0MappingParameter.TPDO1MappingInformation4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_transmitPDO1MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO1MappingParameter.numberOfMappedObjectsTPDO2,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO1MappingParameter.TPDO2MappingInformation1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO1MappingParameter.TPDO2MappingInformation2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO1MappingParameter.TPDO2MappingInformation3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_transmitPDO1MappingParameter.TPDO2MappingInformation4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_transmitPDO2MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO2MappingParameter.numberOfMappedObjectsTPDO3,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO2MappingParameter.TPDO3MappingInformation1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO2MappingParameter.TPDO3MappingInformation2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO2MappingParameter.TPDO3MappingInformation3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A02_transmitPDO2MappingParameter.TPDO3MappingInformation4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_transmitPDO3MappingParameter = {
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO3MappingParameter.numberOfMappedObjectsTPDO4,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO3MappingParameter.TPDO4MappingInformation1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO3MappingParameter.TPDO4MappingInformation2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO3MappingParameter.TPDO4MappingInformation3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A03_transmitPDO3MappingParameter.TPDO4MappingInformation4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2000_writableString = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataLength = 0
    },
    .o_2001_INTEGER16Value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2002_UNSIGNED8Value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2003_INTEGER8Value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2004_INTEGER32Value = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2005_BOOLEANValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2006_BOOLEANValue2 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2020_complexDataType = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 0
    },
    .o_3002_sensorSamplingRateHz = {
        .dataOrig = &OD_RAM.x3002_sensorSamplingRateHz,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_3004_sensorStatus = {
        .dataOrig0 = &OD_RAM.x3004_sensorStatus_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_3006_valve1Open = {
        .dataOrig0 = &OD_RAM.x3006_valve1Open_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_3020_INTEGER8OnlyPositiveValues = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_3021_UNSIGNED8ValueRange2To10 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_3030_INTEGER32OnlyNegativeValues = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_3040_INTEGER64ValueRange_10To10 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 8
    },
    .o_3050_EDSFileExtensions = {
        {
            .dataOrig = &OD_RAM.x3050_EDSFileExtensions.highestSubindex,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x06, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x04, ODT_REC, &ODObjs.o_1018_identityObject, NULL},
    {0x1400, 0x03, ODT_REC, &ODObjs.o_1400_receivePDO0CommunicationParameter, NULL},
    {0x1401, 0x03, ODT_REC, &ODObjs.o_1401_receivePDO1CommunicationParameter, NULL},
    {0x1402, 0x03, ODT_REC, &ODObjs.o_1402_receivePDO2CommunicationParameter, NULL},
    {0x1403, 0x03, ODT_REC, &ODObjs.o_1403_receivePDO3CommunicationParameter, NULL},
    {0x1600, 0x05, ODT_REC, &ODObjs.o_1600_receivePDO0MappingParameter, NULL},
    {0x1601, 0x05, ODT_REC, &ODObjs.o_1601_receivePDO1MappingParameter, NULL},
    {0x1602, 0x05, ODT_REC, &ODObjs.o_1602_receivePDO2MappingParameter, NULL},
    {0x1603, 0x05, ODT_REC, &ODObjs.o_1603_receivePDO3MappingParameter, NULL},
    {0x1800, 0x03, ODT_REC, &ODObjs.o_1800_transmitPDO0CommunicationParameters, NULL},
    {0x1801, 0x03, ODT_REC, &ODObjs.o_1801_transmitPDO1CommunicationParameters, NULL},
    {0x1802, 0x03, ODT_REC, &ODObjs.o_1802_transmitPDO2CommunicationParameters, NULL},
    {0x1803, 0x03, ODT_REC, &ODObjs.o_1803_transmitPDO3CommunicationParameters, NULL},
    {0x1A00, 0x05, ODT_REC, &ODObjs.o_1A00_transmitPDO0MappingParameter, NULL},
    {0x1A01, 0x05, ODT_REC, &ODObjs.o_1A01_transmitPDO1MappingParameter, NULL},
    {0x1A02, 0x05, ODT_REC, &ODObjs.o_1A02_transmitPDO2MappingParameter, NULL},
    {0x1A03, 0x05, ODT_REC, &ODObjs.o_1A03_transmitPDO3MappingParameter, NULL},
    {0x2000, 0x01, ODT_VAR, &ODObjs.o_2000_writableString, NULL},
    {0x2001, 0x01, ODT_VAR, &ODObjs.o_2001_INTEGER16Value, NULL},
    {0x2002, 0x01, ODT_VAR, &ODObjs.o_2002_UNSIGNED8Value, NULL},
    {0x2003, 0x01, ODT_VAR, &ODObjs.o_2003_INTEGER8Value, NULL},
    {0x2004, 0x01, ODT_VAR, &ODObjs.o_2004_INTEGER32Value, NULL},
    {0x2005, 0x01, ODT_VAR, &ODObjs.o_2005_BOOLEANValue, NULL},
    {0x2006, 0x01, ODT_VAR, &ODObjs.o_2006_BOOLEANValue2, NULL},
    {0x2020, 0x01, ODT_VAR, &ODObjs.o_2020_complexDataType, NULL},
    {0x3002, 0x01, ODT_VAR, &ODObjs.o_3002_sensorSamplingRateHz, NULL},
    {0x3004, 0x04, ODT_ARR, &ODObjs.o_3004_sensorStatus, NULL},
    {0x3006, 0x19, ODT_ARR, &ODObjs.o_3006_valve1Open, NULL},
    {0x3020, 0x01, ODT_VAR, &ODObjs.o_3020_INTEGER8OnlyPositiveValues, NULL},
    {0x3021, 0x01, ODT_VAR, &ODObjs.o_3021_UNSIGNED8ValueRange2To10, NULL},
    {0x3030, 0x01, ODT_VAR, &ODObjs.o_3030_INTEGER32OnlyNegativeValues, NULL},
    {0x3040, 0x01, ODT_VAR, &ODObjs.o_3040_INTEGER64ValueRange_10To10, NULL},
    {0x3050, 0x03, ODT_REC, &ODObjs.o_3050_EDSFileExtensions, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
