/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: canopen_sample.eds
        File Version: 

        Created:      2016/11/16 16:38:00
        Created By:   Christian Sandberg
        Modified:     2016/11/16 16:38:00
        Modified By:  

    Device Info:
        Vendor Name:  Vendor Name
        Vendor ID:    1
        Product Name: 
        Product ID:   

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 5
#define OD_CNT_ARR_3004 3
#define OD_CNT_ARR_3006 24


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[OD_CNT_ARR_1003];
    char x1008_manufacturerDeviceName[12];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
    } x1018_identityObject;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUseByRPDO1;
        uint8_t transmissionTypeRPDO1;
    } x1400_receivePDO0CommunicationParameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUseByRPDO2;
        uint8_t transmissionTypeRPDO2;
    } x1401_receivePDO1CommunicationParameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUseByRPDO3;
        uint8_t transmissionTypeRPDO3;
    } x1402_receivePDO2CommunicationParameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUseByRPDO4;
        uint8_t transmissionTypeRPDO4;
    } x1403_receivePDO3CommunicationParameter;
    struct {
        uint8_t numberOfMappedObjectsRPDO1;
        uint32_t RPDO1MappingInformation1;
        uint32_t RPDO1MappingInformation2;
        uint32_t RPDO1MappingInformation3;
        uint32_t RPDO1MappingInformation4;
    } x1600_receivePDO0MappingParameter;
    struct {
        uint8_t numberOfMappedObjectsRPDO2;
        uint32_t RPDO2MappingInformation1;
        uint32_t RPDO2MappingInformation2;
        uint32_t RPDO2MappingInformation3;
        uint32_t RPDO2MappingInformation4;
    } x1601_receivePDO1MappingParameter;
    struct {
        uint8_t numberOfMappedObjectsRPDO3;
        uint32_t RPDO3MappingInformation1;
        uint32_t RPDO3MappingInformation2;
        uint32_t RPDO3MappingInformation3;
        uint32_t RPDO3MappingInformation4;
    } x1602_receivePDO2MappingParameter;
    struct {
        uint8_t numberOfMappedObjectsRPDO4;
        uint32_t RPDO4MappingInformation1;
        uint32_t RPDO4MappingInformation2;
        uint32_t RPDO4MappingInformation3;
        uint32_t RPDO4MappingInformation4;
    } x1603_receivePDO3MappingParameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUseByTPDO1;
        uint8_t transmissionTypeTPDO1;
    } x1800_transmitPDO0CommunicationParameters;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUseByTPDO2;
        uint8_t transmissionTypeTPDO2;
    } x1801_transmitPDO1CommunicationParameters;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUseByTPDO3;
        uint8_t transmissionTypeTPDO3;
    } x1802_transmitPDO2CommunicationParameters;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_IDUseByTPDO4;
        uint8_t transmissionTypeTPDO4;
    } x1803_transmitPDO3CommunicationParameters;
    struct {
        uint8_t numberOfMappedObjectsTPDO1;
        uint32_t TPDO1MappingInformation1;
        uint32_t TPDO1MappingInformation2;
        uint32_t TPDO1MappingInformation3;
        uint32_t TPDO1MappingInformation4;
    } x1A00_transmitPDO0MappingParameter;
    struct {
        uint8_t numberOfMappedObjectsTPDO2;
        uint32_t TPDO2MappingInformation1;
        uint32_t TPDO2MappingInformation2;
        uint32_t TPDO2MappingInformation3;
        uint32_t TPDO2MappingInformation4;
    } x1A01_transmitPDO1MappingParameter;
    struct {
        uint8_t numberOfMappedObjectsTPDO3;
        uint32_t TPDO3MappingInformation1;
        uint32_t TPDO3MappingInformation2;
        uint32_t TPDO3MappingInformation3;
        uint32_t TPDO3MappingInformation4;
    } x1A02_transmitPDO2MappingParameter;
    struct {
        uint8_t numberOfMappedObjectsTPDO4;
        uint32_t TPDO4MappingInformation1;
        uint32_t TPDO4MappingInformation2;
        uint32_t TPDO4MappingInformation3;
        uint32_t TPDO4MappingInformation4;
    } x1A03_transmitPDO3MappingParameter;
    float32_t x3002_sensorSamplingRateHz;
    uint8_t x3004_sensorStatus_sub0;
    uint8_t x3006_valve1Open_sub0;
    struct {
        uint8_t highestSubindex;
    } x3050_EDSFileExtensions;
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1008 &OD->list[3]
#define OD_ENTRY_H1017 &OD->list[4]
#define OD_ENTRY_H1018 &OD->list[5]
#define OD_ENTRY_H1400 &OD->list[6]
#define OD_ENTRY_H1401 &OD->list[7]
#define OD_ENTRY_H1402 &OD->list[8]
#define OD_ENTRY_H1403 &OD->list[9]
#define OD_ENTRY_H1600 &OD->list[10]
#define OD_ENTRY_H1601 &OD->list[11]
#define OD_ENTRY_H1602 &OD->list[12]
#define OD_ENTRY_H1603 &OD->list[13]
#define OD_ENTRY_H1800 &OD->list[14]
#define OD_ENTRY_H1801 &OD->list[15]
#define OD_ENTRY_H1802 &OD->list[16]
#define OD_ENTRY_H1803 &OD->list[17]
#define OD_ENTRY_H1A00 &OD->list[18]
#define OD_ENTRY_H1A01 &OD->list[19]
#define OD_ENTRY_H1A02 &OD->list[20]
#define OD_ENTRY_H1A03 &OD->list[21]
#define OD_ENTRY_H2000 &OD->list[22]
#define OD_ENTRY_H2001 &OD->list[23]
#define OD_ENTRY_H2002 &OD->list[24]
#define OD_ENTRY_H2003 &OD->list[25]
#define OD_ENTRY_H2004 &OD->list[26]
#define OD_ENTRY_H2005 &OD->list[27]
#define OD_ENTRY_H2006 &OD->list[28]
#define OD_ENTRY_H2020 &OD->list[29]
#define OD_ENTRY_H3002 &OD->list[30]
#define OD_ENTRY_H3004 &OD->list[31]
#define OD_ENTRY_H3006 &OD->list[32]
#define OD_ENTRY_H3020 &OD->list[33]
#define OD_ENTRY_H3021 &OD->list[34]
#define OD_ENTRY_H3030 &OD->list[35]
#define OD_ENTRY_H3040 &OD->list[36]
#define OD_ENTRY_H3050 &OD->list[37]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[3]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[4]
#define OD_ENTRY_H1018_identityObject &OD->list[5]
#define OD_ENTRY_H1400_receivePDO0CommunicationParameter &OD->list[6]
#define OD_ENTRY_H1401_receivePDO1CommunicationParameter &OD->list[7]
#define OD_ENTRY_H1402_receivePDO2CommunicationParameter &OD->list[8]
#define OD_ENTRY_H1403_receivePDO3CommunicationParameter &OD->list[9]
#define OD_ENTRY_H1600_receivePDO0MappingParameter &OD->list[10]
#define OD_ENTRY_H1601_receivePDO1MappingParameter &OD->list[11]
#define OD_ENTRY_H1602_receivePDO2MappingParameter &OD->list[12]
#define OD_ENTRY_H1603_receivePDO3MappingParameter &OD->list[13]
#define OD_ENTRY_H1800_transmitPDO0CommunicationParameters &OD->list[14]
#define OD_ENTRY_H1801_transmitPDO1CommunicationParameters &OD->list[15]
#define OD_ENTRY_H1802_transmitPDO2CommunicationParameters &OD->list[16]
#define OD_ENTRY_H1803_transmitPDO3CommunicationParameters &OD->list[17]
#define OD_ENTRY_H1A00_transmitPDO0MappingParameter &OD->list[18]
#define OD_ENTRY_H1A01_transmitPDO1MappingParameter &OD->list[19]
#define OD_ENTRY_H1A02_transmitPDO2MappingParameter &OD->list[20]
#define OD_ENTRY_H1A03_transmitPDO3MappingParameter &OD->list[21]
#define OD_ENTRY_H2000_writableString &OD->list[22]
#define OD_ENTRY_H2001_INTEGER16Value &OD->list[23]
#define OD_ENTRY_H2002_UNSIGNED8Value &OD->list[24]
#define OD_ENTRY_H2003_INTEGER8Value &OD->list[25]
#define OD_ENTRY_H2004_INTEGER32Value &OD->list[26]
#define OD_ENTRY_H2005_BOOLEANValue &OD->list[27]
#define OD_ENTRY_H2006_BOOLEANValue2 &OD->list[28]
#define OD_ENTRY_H2020_complexDataType &OD->list[29]
#define OD_ENTRY_H3002_sensorSamplingRateHz &OD->list[30]
#define OD_ENTRY_H3004_sensorStatus &OD->list[31]
#define OD_ENTRY_H3006_valve1Open &OD->list[32]
#define OD_ENTRY_H3020_INTEGER8OnlyPositiveValues &OD->list[33]
#define OD_ENTRY_H3021_UNSIGNED8ValueRange2To10 &OD->list[34]
#define OD_ENTRY_H3030_INTEGER32OnlyNegativeValues &OD->list[35]
#define OD_ENTRY_H3040_INTEGER64ValueRange_10To10 &OD->list[36]
#define OD_ENTRY_H3050_EDSFileExtensions &OD->list[37]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = 0;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = 0;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = NULL;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = 0;\
    (config).ENTRY_H1200 = NULL;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = 0;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
