/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: aa_anchor_minimal.eds
        File Version: 1

        Created:      2024/1/1 12:00:00
        Created By:   Test
        Modified:     2024/1/1 12:00:00
        Modified By:  Test

    Device Info:
        Vendor Name:  TestVendor
        Vendor ID:    0x123
        Product Name: TestProduct
        Product ID:   0x456

        Description:  Minimal test EDS
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
    } x1018_identity;
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1018 &OD->list[2]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1018_identity &OD->list[2]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = 0;\
    (config).ENTRY_H1017 = NULL;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = 0;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = NULL;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = 0;\
    (config).ENTRY_H1200 = NULL;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = NULL;\
    (config).ENTRY_H1600 = NULL;\
    (config).CNT_TPDO = 0;\
    (config).ENTRY_H1800 = NULL;\
    (config).ENTRY_H1A00 = NULL;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
