/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1000_deviceType = 0x00000000,
    .x1001_errorRegister = 0x00,
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identityObject = {
        .numberOfEntries = 0x04
    },
    .x1400_receivePDO_CommunicationParameter1 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000200,
        .transmissionType = 0xFE
    },
    .x1401_receivePDO_CommunicationParameter2 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000300,
        .transmissionType = 0xFE
    },
    .x1600_receivePDO_MappingParameter1 = {
        .numberOfEntries = 0x00
    },
    .x1601_receivePDO_MappingParameter2 = {
        .numberOfEntries = 0x00
    },
    .x1800_transmitPDO_CommunicationParameter1 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000
    },
    .x1801_transmitPDO_CommunicationParameter2 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000
    },
    .x1A00_TPDO_MappingParameter1 = {
        .numberOfEntries = 0x00,
        .mappingEntry1 = 0x00000000,
        .mappingEntry2 = 0x00000000,
        .mappingEntry3 = 0x00000000,
        .mappingEntry4 = 0x00000000,
        .mappingEntry5 = 0x00000000,
        .mappingEntry6 = 0x00000000,
        .mappingEntry7 = 0x00000000,
        .mappingEntry8 = 0x00000000
    },
    .x1A01_TPDO_MappingParameter2 = {
        .numberOfEntries = 0x00,
        .mappingEntry1 = 0x00000000,
        .mappingEntry2 = 0x00000000,
        .mappingEntry3 = 0x00000000,
        .mappingEntry4 = 0x00000000,
        .mappingEntry5 = 0x00000000,
        .mappingEntry6 = 0x00000000,
        .mappingEntry7 = 0x00000000,
        .mappingEntry8 = 0x00000000
    },
    .x6302_camPolarityRegister = {0x00, 0x00}
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identityObject[5];
    OD_obj_record_t o_1400_receivePDO_CommunicationParameter1[3];
    OD_obj_record_t o_1401_receivePDO_CommunicationParameter2[3];
    OD_obj_record_t o_1600_receivePDO_MappingParameter1[9];
    OD_obj_record_t o_1601_receivePDO_MappingParameter2[9];
    OD_obj_record_t o_1800_transmitPDO_CommunicationParameter1[6];
    OD_obj_record_t o_1801_transmitPDO_CommunicationParameter2[6];
    OD_obj_record_t o_1A00_TPDO_MappingParameter1[9];
    OD_obj_record_t o_1A01_TPDO_MappingParameter2[9];
    OD_obj_var_t o_6000_operatingParameters;
    OD_obj_var_t o_6001_measuringUnitsPerRevolution;
    OD_obj_var_t o_6002_totalMeasuringRangeInMeasuringUnits;
    OD_obj_var_t o_6003_presetValue;
    OD_obj_var_t o_6004_positionValue;
    OD_obj_array_t o_6005_linearEncoderMeasuringStepSettings;
    OD_obj_array_t o_6010_presetValueForMultiSensorDevices;
    OD_obj_array_t o_6020_positionValueForMultiSensorDevices;
    OD_obj_array_t o_6030_speedValue;
    OD_obj_array_t o_6040_accelerationValue;
    OD_obj_array_t o_6050_jerkValue;
    OD_obj_var_t o_6200_cyclicTimerValue;
    OD_obj_array_t o_6300_camStateRegister;
    OD_obj_array_t o_6301_CAM_Enable;
    OD_obj_array_t o_6302_camPolarityRegister;
    OD_obj_array_t o_6310_CAM1LowLimit;
    OD_obj_array_t o_6311_CAM2LowLimit;
    OD_obj_array_t o_6312_CAM3LowLimit;
    OD_obj_array_t o_6313_CAM4LowLimit;
    OD_obj_array_t o_6314_CAM5LowLimit;
    OD_obj_array_t o_6315_CAM6LowLimit;
    OD_obj_array_t o_6316_CAM7LowLimit;
    OD_obj_array_t o_6317_CAM8LowLimit;
    OD_obj_array_t o_6320_cam1HighLimit;
    OD_obj_array_t o_6321_cam2HighLimit;
    OD_obj_array_t o_6322_cam3HighLimit;
    OD_obj_array_t o_6323_cam4HighLimit;
    OD_obj_array_t o_6324_cam5HighLimit;
    OD_obj_array_t o_6325_cam6HighLimit;
    OD_obj_array_t o_6326_cam7HighLimit;
    OD_obj_array_t o_6327_cam8HighLimit;
    OD_obj_array_t o_6330_cam1Hysteresis;
    OD_obj_array_t o_6331_cam2Hysteresis;
    OD_obj_array_t o_6332_cam3Hysteresis;
    OD_obj_array_t o_6333_cam4Hysteresis;
    OD_obj_array_t o_6334_cam5Hysteresis;
    OD_obj_array_t o_6335_cam6Hysteresis;
    OD_obj_array_t o_6336_cam7Hysteresis;
    OD_obj_array_t o_6337_cam8Hysteresis;
    OD_obj_array_t o_6400_areaStateRegister;
    OD_obj_array_t o_6401_workAreaLowLimit;
    OD_obj_array_t o_6402_workAreaHighLimit;
    OD_obj_var_t o_6500_operatingStatus;
    OD_obj_var_t o_6501_single_TurnResolutionMeasuringStep;
    OD_obj_var_t o_6502_numberOfDistinguishableRevolutions;
    OD_obj_var_t o_6503_alarms;
    OD_obj_var_t o_6504_supportedAlarms;
    OD_obj_var_t o_6505_warnings;
    OD_obj_var_t o_6506_supportedWarnings;
    OD_obj_var_t o_6507_profileAndSoftwareVersion;
    OD_obj_var_t o_6508_operatingTime;
    OD_obj_var_t o_6509_offsetValue;
    OD_obj_array_t o_650A_moduleIdentification;
    OD_obj_var_t o_650B_serialNumber;
    OD_obj_array_t o_650C_offsetValueForMulti_sensorDevices;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_RAM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_RAM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identityObject = {
        {
            .dataOrig = &OD_RAM.x1018_identityObject.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_receivePDO_CommunicationParameter1 = {
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1401_receivePDO_CommunicationParameter2 = {
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_receivePDO_MappingParameter1 = {
        {
            .dataOrig = &OD_RAM.x1600_receivePDO_MappingParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_receivePDO_MappingParameter2 = {
        {
            .dataOrig = &OD_RAM.x1601_receivePDO_MappingParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_transmitPDO_CommunicationParameter1 = {
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1801_transmitPDO_CommunicationParameter2 = {
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1A00_TPDO_MappingParameter1 = {
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDO_MappingParameter2 = {
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_6000_operatingParameters = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6001_measuringUnitsPerRevolution = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6002_totalMeasuringRangeInMeasuringUnits = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6003_presetValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_6004_positionValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6005_linearEncoderMeasuringStepSettings = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6010_presetValueForMultiSensorDevices = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6020_positionValueForMultiSensorDevices = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6030_speedValue = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_6040_accelerationValue = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_6050_jerkValue = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_6200_cyclicTimerValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6300_camStateRegister = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6301_CAM_Enable = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6302_camPolarityRegister = {
        .dataOrig0 = NULL,
        .dataOrig = &OD_RAM.x6302_camPolarityRegister[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6310_CAM1LowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6311_CAM2LowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6312_CAM3LowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6313_CAM4LowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6314_CAM5LowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6315_CAM6LowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6316_CAM7LowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6317_CAM8LowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6320_cam1HighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6321_cam2HighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6322_cam3HighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6323_cam4HighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6324_cam5HighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6325_cam6HighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6326_cam7HighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6327_cam8HighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6330_cam1Hysteresis = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6331_cam2Hysteresis = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6332_cam3Hysteresis = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6333_cam4Hysteresis = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6334_cam5Hysteresis = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6335_cam6Hysteresis = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6336_cam7Hysteresis = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6337_cam8Hysteresis = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6400_areaStateRegister = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6401_workAreaLowLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6402_workAreaHighLimit = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6500_operatingStatus = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6501_single_TurnResolutionMeasuringStep = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6502_numberOfDistinguishableRevolutions = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6503_alarms = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6504_supportedAlarms = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6505_warnings = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6506_supportedWarnings = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6507_profileAndSoftwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6508_operatingTime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6509_offsetValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_650A_moduleIdentification = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_650B_serialNumber = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_650C_offsetValueForMulti_sensorDevices = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identityObject, NULL},
    {0x1400, 0x03, ODT_REC, &ODObjs.o_1400_receivePDO_CommunicationParameter1, NULL},
    {0x1401, 0x03, ODT_REC, &ODObjs.o_1401_receivePDO_CommunicationParameter2, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_receivePDO_MappingParameter1, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_receivePDO_MappingParameter2, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_transmitPDO_CommunicationParameter1, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_transmitPDO_CommunicationParameter2, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDO_MappingParameter1, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDO_MappingParameter2, NULL},
    {0x6000, 0x01, ODT_VAR, &ODObjs.o_6000_operatingParameters, NULL},
    {0x6001, 0x01, ODT_VAR, &ODObjs.o_6001_measuringUnitsPerRevolution, NULL},
    {0x6002, 0x01, ODT_VAR, &ODObjs.o_6002_totalMeasuringRangeInMeasuringUnits, NULL},
    {0x6003, 0x01, ODT_VAR, &ODObjs.o_6003_presetValue, NULL},
    {0x6004, 0x01, ODT_VAR, &ODObjs.o_6004_positionValue, NULL},
    {0x6005, 0x05, ODT_ARR, &ODObjs.o_6005_linearEncoderMeasuringStepSettings, NULL},
    {0x6010, 0x03, ODT_ARR, &ODObjs.o_6010_presetValueForMultiSensorDevices, NULL},
    {0x6020, 0x03, ODT_ARR, &ODObjs.o_6020_positionValueForMultiSensorDevices, NULL},
    {0x6030, 0x03, ODT_ARR, &ODObjs.o_6030_speedValue, NULL},
    {0x6040, 0x04, ODT_ARR, &ODObjs.o_6040_accelerationValue, NULL},
    {0x6050, 0x04, ODT_ARR, &ODObjs.o_6050_jerkValue, NULL},
    {0x6200, 0x01, ODT_VAR, &ODObjs.o_6200_cyclicTimerValue, NULL},
    {0x6300, 0x03, ODT_ARR, &ODObjs.o_6300_camStateRegister, NULL},
    {0x6301, 0x03, ODT_ARR, &ODObjs.o_6301_CAM_Enable, NULL},
    {0x6302, 0x03, ODT_ARR, &ODObjs.o_6302_camPolarityRegister, NULL},
    {0x6310, 0x03, ODT_ARR, &ODObjs.o_6310_CAM1LowLimit, NULL},
    {0x6311, 0x03, ODT_ARR, &ODObjs.o_6311_CAM2LowLimit, NULL},
    {0x6312, 0x03, ODT_ARR, &ODObjs.o_6312_CAM3LowLimit, NULL},
    {0x6313, 0x03, ODT_ARR, &ODObjs.o_6313_CAM4LowLimit, NULL},
    {0x6314, 0x03, ODT_ARR, &ODObjs.o_6314_CAM5LowLimit, NULL},
    {0x6315, 0x03, ODT_ARR, &ODObjs.o_6315_CAM6LowLimit, NULL},
    {0x6316, 0x03, ODT_ARR, &ODObjs.o_6316_CAM7LowLimit, NULL},
    {0x6317, 0x03, ODT_ARR, &ODObjs.o_6317_CAM8LowLimit, NULL},
    {0x6320, 0x03, ODT_ARR, &ODObjs.o_6320_cam1HighLimit, NULL},
    {0x6321, 0x03, ODT_ARR, &ODObjs.o_6321_cam2HighLimit, NULL},
    {0x6322, 0x03, ODT_ARR, &ODObjs.o_6322_cam3HighLimit, NULL},
    {0x6323, 0x03, ODT_ARR, &ODObjs.o_6323_cam4HighLimit, NULL},
    {0x6324, 0x03, ODT_ARR, &ODObjs.o_6324_cam5HighLimit, NULL},
    {0x6325, 0x03, ODT_ARR, &ODObjs.o_6325_cam6HighLimit, NULL},
    {0x6326, 0x03, ODT_ARR, &ODObjs.o_6326_cam7HighLimit, NULL},
    {0x6327, 0x03, ODT_ARR, &ODObjs.o_6327_cam8HighLimit, NULL},
    {0x6330, 0x03, ODT_ARR, &ODObjs.o_6330_cam1Hysteresis, NULL},
    {0x6331, 0x03, ODT_ARR, &ODObjs.o_6331_cam2Hysteresis, NULL},
    {0x6332, 0x03, ODT_ARR, &ODObjs.o_6332_cam3Hysteresis, NULL},
    {0x6333, 0x03, ODT_ARR, &ODObjs.o_6333_cam4Hysteresis, NULL},
    {0x6334, 0x03, ODT_ARR, &ODObjs.o_6334_cam5Hysteresis, NULL},
    {0x6335, 0x03, ODT_ARR, &ODObjs.o_6335_cam6Hysteresis, NULL},
    {0x6336, 0x03, ODT_ARR, &ODObjs.o_6336_cam7Hysteresis, NULL},
    {0x6337, 0x03, ODT_ARR, &ODObjs.o_6337_cam8Hysteresis, NULL},
    {0x6400, 0x03, ODT_ARR, &ODObjs.o_6400_areaStateRegister, NULL},
    {0x6401, 0x03, ODT_ARR, &ODObjs.o_6401_workAreaLowLimit, NULL},
    {0x6402, 0x03, ODT_ARR, &ODObjs.o_6402_workAreaHighLimit, NULL},
    {0x6500, 0x01, ODT_VAR, &ODObjs.o_6500_operatingStatus, NULL},
    {0x6501, 0x01, ODT_VAR, &ODObjs.o_6501_single_TurnResolutionMeasuringStep, NULL},
    {0x6502, 0x01, ODT_VAR, &ODObjs.o_6502_numberOfDistinguishableRevolutions, NULL},
    {0x6503, 0x01, ODT_VAR, &ODObjs.o_6503_alarms, NULL},
    {0x6504, 0x01, ODT_VAR, &ODObjs.o_6504_supportedAlarms, NULL},
    {0x6505, 0x01, ODT_VAR, &ODObjs.o_6505_warnings, NULL},
    {0x6506, 0x01, ODT_VAR, &ODObjs.o_6506_supportedWarnings, NULL},
    {0x6507, 0x01, ODT_VAR, &ODObjs.o_6507_profileAndSoftwareVersion, NULL},
    {0x6508, 0x01, ODT_VAR, &ODObjs.o_6508_operatingTime, NULL},
    {0x6509, 0x01, ODT_VAR, &ODObjs.o_6509_offsetValue, NULL},
    {0x650A, 0x04, ODT_ARR, &ODObjs.o_650A_moduleIdentification, NULL},
    {0x650B, 0x01, ODT_VAR, &ODObjs.o_650B_serialNumber, NULL},
    {0x650C, 0x03, ODT_ARR, &ODObjs.o_650C_offsetValueForMulti_sensorDevices, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
