/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1000_deviceType = 0x00000000,
    .x1001_errorRegister = 0x00,
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identityObject = {
        .numberOfEntries = 0x04
    },
    .x1400_receivePDO_CommunicationParameter1 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000200,
        .transmissionType = 0xFE
    },
    .x1401_receivePDO_CommunicationParameter2 = {
        .numberOfEntries = 0x02,
        .COB_ID = 0x00000300,
        .transmissionType = 0xFE
    },
    .x1600_receivePDO_MappingParameter1 = {
        .numberOfEntries = 0x00
    },
    .x1601_receivePDO_MappingParameter2 = {
        .numberOfEntries = 0x00
    },
    .x1800_transmitPDO_CommunicationParameter1 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000180,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000
    },
    .x1801_transmitPDO_CommunicationParameter2 = {
        .numberOfEntries = 0x05,
        .COB_ID = 0x00000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x0000
    },
    .x1A00_TPDO_MappingParameter1 = {
        .numberOfEntries = 0x00,
        .mappingEntry1 = 0x00000000,
        .mappingEntry2 = 0x00000000,
        .mappingEntry3 = 0x00000000,
        .mappingEntry4 = 0x00000000,
        .mappingEntry5 = 0x00000000,
        .mappingEntry6 = 0x00000000,
        .mappingEntry7 = 0x00000000,
        .mappingEntry8 = 0x00000000
    },
    .x1A01_TPDO_MappingParameter2 = {
        .numberOfEntries = 0x00,
        .mappingEntry1 = 0x00000000,
        .mappingEntry2 = 0x00000000,
        .mappingEntry3 = 0x00000000,
        .mappingEntry4 = 0x00000000,
        .mappingEntry5 = 0x00000000,
        .mappingEntry6 = 0x00000000,
        .mappingEntry7 = 0x00000000,
        .mappingEntry8 = 0x00000000
    },
    .x6000_readInput8Bit_sub0 = 0x02,
    .x6000_readInput8Bit = {0x00, 0x00},
    .x6002_polarity8InputLines_sub0 = 0x02,
    .x6002_polarity8InputLines = {0x00, 0x00},
    .x6003_filterConstant8InputLines_sub0 = 0x02,
    .x6003_filterConstant8InputLines = {0x00, 0x00},
    .x6005_enableDigitalInputInterrupts = true,
    .x6006_inputInterruptMask8_AnyChange_sub0 = 0x02,
    .x6006_inputInterruptMask8_AnyChange = {0xFF, 0xFF},
    .x6007_inputInterruptMask8_LowToHigh_sub0 = 0x02,
    .x6007_inputInterruptMask8_LowToHigh = {0x00, 0x00},
    .x6008_inputInterruptMask8_HighToLow_sub0 = 0x02,
    .x6008_inputInterruptMask8_HighToLow = {0x00, 0x00},
    .x6020_readState1InputLine1_128_sub0 = 0x10,
    .x6030_polarity1InputLine1_128_sub0 = 0x10,
    .x6030_polarity1InputLine1_128 = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    .x6038_filterConstant1InputLine1_128_sub0 = 0x10,
    .x6038_filterConstant1InputLine1_128 = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    .x6050_interruptMask1InputLine1_128_AnyChange_sub0 = 0x10,
    .x6050_interruptMask1InputLine1_128_AnyChange = {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
    .x6060_interruptMask1InputLine1_128_LowToHigh_sub0 = 0x10,
    .x6060_interruptMask1InputLine1_128_LowToHigh = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    .x6070_interruptMask1InputLine1_128_HighToLow_sub0 = 0x10,
    .x6070_interruptMask1InputLine1_128_HighToLow = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    .x6100_readState16InputLines_sub0 = 0x01,
    .x6100_readState16InputLines = {0x0000},
    .x6102_polarity16InputLines_sub0 = 0x01,
    .x6102_polarity16InputLines = {0x0000},
    .x6103_filterConstant16InputLines_sub0 = 0x01,
    .x6103_filterConstant16InputLines = {0x0000},
    .x6106_inputInterruptMask16InputLines_AnyChange_sub0 = 0x01,
    .x6106_inputInterruptMask16InputLines_AnyChange = {0xFFFF},
    .x6107_inputInterruptMask16InputLines_LowToHigh_sub0 = 0x01,
    .x6107_inputInterruptMask16InputLines_LowToHigh = {0x0000},
    .x6108_inputInterruptMask16InputLines_HighToLow_sub0 = 0x01,
    .x6108_inputInterruptMask16InputLines_HighToLow = {0x0000},
    .x6120_readState32InputLines_sub0 = 0x01,
    .x6122_polarity32InputLines_sub0 = 0x01,
    .x6122_polarity32InputLines = {0x00000000},
    .x6123_filterConstant32InputLines_sub0 = 0x01,
    .x6123_filterConstant32InputLines = {0x00000000},
    .x6126_inputInterruptMask32InputLines_AnyChange_sub0 = 0x01,
    .x6126_inputInterruptMask32InputLines_AnyChange = {0xFFFFFFFF},
    .x6127_inputInterruptMask32InputLines_LowToHigh_sub0 = 0x01,
    .x6127_inputInterruptMask32InputLines_LowToHigh = {0x00000000},
    .x6128_inputInterruptMask32InputLines_HighToLow_sub0 = 0x01,
    .x6128_inputInterruptMask32InputLines_HighToLow = {0x00000000},
    .x6200_writeOutput8_bit_sub0 = 0x02,
    .x6200_writeOutput8_bit = {0x00, 0x00},
    .x6202_polarity8OutputLines_sub0 = 0x02,
    .x6202_polarity8OutputLines = {0x00, 0x00},
    .x6206_faultMode8OutputLines_sub0 = 0x02,
    .x6206_faultMode8OutputLines = {0xFF, 0xFF},
    .x6207_faultState8OutputLines_sub0 = 0x02,
    .x6207_faultState8OutputLines = {0x00, 0x00},
    .x6208_filterConstant8OutputLines_sub0 = 0x02,
    .x6208_filterConstant8OutputLines = {0xFF, 0xFF},
    .x6220_writeState1OutputLine1_128_sub0 = 0x08,
    .x6240_polarity1OutputLine1_128_sub0 = 0x08,
    .x6240_polarity1OutputLine1_128 = {false, false, false, false, false, false, false, false},
    .x6250_faultMode1OutputLine1_128_sub0 = 0x08,
    .x6250_faultMode1OutputLine1_128 = {true, true, true, true, true, true, true, true},
    .x6260_faultState1OutputLine1_128_sub0 = 0x08,
    .x6260_faultState1OutputLine1_128 = {false, false, false, false, false, false, false, false},
    .x6270_filterConstant1OutputLine1_128_sub0 = 0x08,
    .x6270_filterConstant1OutputLine1_128 = {true, true, true, true, true, true, true, true},
    .x6300_writeState16OutputLines_sub0 = 0x01,
    .x6300_writeState16OutputLines = {0x0000},
    .x6302_polarity16OutputLines_sub0 = 0x01,
    .x6302_polarity16OutputLines = {0x0000},
    .x6306_errorModeOutput16_bit_sub0 = 0x01,
    .x6306_errorModeOutput16_bit = {0xFFFF},
    .x6307_errorValueOutput16_bit_sub0 = 0x01,
    .x6307_errorValueOutput16_bit = {0x0000},
    .x6308_filterConstant16OutputLines_sub0 = 0x01,
    .x6308_filterConstant16OutputLines = {0xFFFF},
    .x6320_writeState32OutputLines_sub0 = 0x01,
    .x6320_writeState32OutputLines = {0x00000000},
    .x6322_polarity32OutputLines_sub0 = 0x01,
    .x6322_polarity32OutputLines = {0x00000000},
    .x6326_errorMode32OutputLines_sub0 = 0x01,
    .x6326_errorMode32OutputLines = {0xFFFFFFFF},
    .x6327_errorValue32OutputLines_sub0 = 0x01,
    .x6327_errorValue32OutputLines = {0x00000000},
    .x6328_filterConstant32OutputLines_sub0 = 0x01,
    .x6328_filterConstant32OutputLines = {0xFFFFFFFF},
    .x6400_readAnalogInput8Bit_sub0 = 0x08,
    .x6400_readAnalogInput8Bit = {0, 0, 0, 0, 0, 0, 0, 0},
    .x6401_readAnalogInput16Bit_sub0 = 0x08,
    .x6401_readAnalogInput16Bit = {0, 0, 0, 0, 0, 0, 0, 0},
    .x6402_readAnalogInput32Bit_sub0 = 0x01,
    .x6402_readAnalogInput32Bit = {0},
    .x6403_readAnalogInput_Converted_sub0 = 0x08,
    .x6403_readAnalogInput_Converted = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0},
    .x6404_readAnalogInputManufacturerSpecific_sub0 = 0x02,
    .x6410_writeAnalogOutput8Bit_sub0 = 0x08,
    .x6410_writeAnalogOutput8Bit = {0, 0, 0, 0, 0, 0, 0, 0},
    .x6411_writeAnalogOutput16Bit_sub0 = 0x02,
    .x6411_writeAnalogOutput16Bit = {0, 0},
    .x6412_writeAnalogOutput32Bit_sub0 = 0x02,
    .x6412_writeAnalogOutput32Bit = {0, 0},
    .x6413_writeAnalogOutputReal_sub0 = 0x02,
    .x6413_writeAnalogOutputReal = {0.0, 0.0},
    .x6414_writeAnalogOutputManu_sub0 = 0x01,
    .x6421_analogInputInterruptTriggerSelection_sub0 = 0x08,
    .x6421_analogInputInterruptTriggerSelection = {0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07},
    .x6422_analogInterruptSource_sub0 = 0x01,
    .x6422_analogInterruptSource = {0x00000000},
    .x6423_globalAnalogInterruptEnable = false,
    .x6424_analogInputInterruptUpperLimit_sub0 = 0x08,
    .x6424_analogInputInterruptUpperLimit = {0, 0, 0, 0, 0, 0, 0, 0},
    .x6425_analogInputInterruptLowerLimit_sub0 = 0x08,
    .x6425_analogInputInterruptLowerLimit = {0, 0, 0, 0, 0, 0, 0, 0},
    .x6426_analogInputInterruptDelta_sub0 = 0x08,
    .x6426_analogInputInterruptDelta = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x6427_analogInputInterruptNegativeDelta_sub0 = 0x01,
    .x6427_analogInputInterruptNegativeDelta = {0x00000000},
    .x6428_analogInputInterruptPositiveDelta_sub0 = 0x01,
    .x6428_analogInputInterruptPositiveDelta = {0x00000000},
    .x6429_analogInputInterruptRealUpperLimit_sub0 = 0x01,
    .x6429_analogInputInterruptRealUpperLimit = {0.0},
    .x642A_analogInputInterruptRealLowerLimit_sub0 = 0x01,
    .x642A_analogInputInterruptRealLowerLimit = {0.0},
    .x642B_analogInputInterruptRealDelta_sub0 = 0x02,
    .x642B_analogInputInterruptRealDelta = {0.0, 0.0},
    .x642C_analogInputInterruptRealNegativeDelta_sub0 = 0x02,
    .x642C_analogInputInterruptRealNegativeDelta = {0.0, 0.0},
    .x642D_analogInputInterruptRealPositiveDelta_sub0 = 0x01,
    .x642D_analogInputInterruptRealPositiveDelta = {0.0},
    .x642E_analogInputConversionOffset_sub0 = 0x08,
    .x642E_analogInputConversionOffset = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0},
    .x642F_analogInputConversionScaling_sub0 = 0x08,
    .x642F_analogInputConversionScaling = {1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0},
    .x6430_analogInputSI_sub0 = 0x01,
    .x6431_analogInputOffsetInteger_sub0 = 0x01,
    .x6431_analogInputOffsetInteger = {0},
    .x6432_analogInputScalingInteger_sub0 = 0x01,
    .x6432_analogInputScalingInteger = {1},
    .x6441_analogOutputConversionOffset_sub0 = 0x08,
    .x6441_analogOutputConversionOffset = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0},
    .x6442_analogOutputConversionScaling_sub0 = 0x08,
    .x6442_analogOutputConversionScaling = {1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0},
    .x6443_analogOutputFaultMode_sub0 = 0x02,
    .x6443_analogOutputFaultMode = {0x01, 0x01},
    .x6444_defaultAnalogOutputFaultStateUnconverted_sub0 = 0x02,
    .x6444_defaultAnalogOutputFaultStateUnconverted = {0, 0},
    .x6445_defaultRealAnalogOutputFaultStateUnconverted_sub0 = 0x01,
    .x6445_defaultRealAnalogOutputFaultStateUnconverted = {0.0},
    .x6446_analogOutputOffsetInteger_sub0 = 0x01,
    .x6446_analogOutputOffsetInteger = {0},
    .x6447_analogOutputScalingInteger_sub0 = 0x01,
    .x6447_analogOutputScalingInteger = {1},
    .x6450_analogOutputSI_sub0 = 0x01,
    .x6450_analogOutputSI = {0x00000000}
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identityObject[5];
    OD_obj_record_t o_1400_receivePDO_CommunicationParameter1[3];
    OD_obj_record_t o_1401_receivePDO_CommunicationParameter2[3];
    OD_obj_record_t o_1600_receivePDO_MappingParameter1[9];
    OD_obj_record_t o_1601_receivePDO_MappingParameter2[9];
    OD_obj_record_t o_1800_transmitPDO_CommunicationParameter1[6];
    OD_obj_record_t o_1801_transmitPDO_CommunicationParameter2[6];
    OD_obj_record_t o_1A00_TPDO_MappingParameter1[9];
    OD_obj_record_t o_1A01_TPDO_MappingParameter2[9];
    OD_obj_array_t o_6000_readInput8Bit;
    OD_obj_array_t o_6002_polarity8InputLines;
    OD_obj_array_t o_6003_filterConstant8InputLines;
    OD_obj_var_t o_6005_enableDigitalInputInterrupts;
    OD_obj_array_t o_6006_inputInterruptMask8_AnyChange;
    OD_obj_array_t o_6007_inputInterruptMask8_LowToHigh;
    OD_obj_array_t o_6008_inputInterruptMask8_HighToLow;
    OD_obj_array_t o_6020_readState1InputLine1_128;
    OD_obj_array_t o_6030_polarity1InputLine1_128;
    OD_obj_array_t o_6038_filterConstant1InputLine1_128;
    OD_obj_array_t o_6050_interruptMask1InputLine1_128_AnyChange;
    OD_obj_array_t o_6060_interruptMask1InputLine1_128_LowToHigh;
    OD_obj_array_t o_6070_interruptMask1InputLine1_128_HighToLow;
    OD_obj_array_t o_6100_readState16InputLines;
    OD_obj_array_t o_6102_polarity16InputLines;
    OD_obj_array_t o_6103_filterConstant16InputLines;
    OD_obj_array_t o_6106_inputInterruptMask16InputLines_AnyChange;
    OD_obj_array_t o_6107_inputInterruptMask16InputLines_LowToHigh;
    OD_obj_array_t o_6108_inputInterruptMask16InputLines_HighToLow;
    OD_obj_array_t o_6120_readState32InputLines;
    OD_obj_array_t o_6122_polarity32InputLines;
    OD_obj_array_t o_6123_filterConstant32InputLines;
    OD_obj_array_t o_6126_inputInterruptMask32InputLines_AnyChange;
    OD_obj_array_t o_6127_inputInterruptMask32InputLines_LowToHigh;
    OD_obj_array_t o_6128_inputInterruptMask32InputLines_HighToLow;
    OD_obj_array_t o_6200_writeOutput8_bit;
    OD_obj_array_t o_6202_polarity8OutputLines;
    OD_obj_array_t o_6206_faultMode8OutputLines;
    OD_obj_array_t o_6207_faultState8OutputLines;
    OD_obj_array_t o_6208_filterConstant8OutputLines;
    OD_obj_array_t o_6220_writeState1OutputLine1_128;
    OD_obj_array_t o_6240_polarity1OutputLine1_128;
    OD_obj_array_t o_6250_faultMode1OutputLine1_128;
    OD_obj_array_t o_6260_faultState1OutputLine1_128;
    OD_obj_array_t o_6270_filterConstant1OutputLine1_128;
    OD_obj_array_t o_6300_writeState16OutputLines;
    OD_obj_array_t o_6302_polarity16OutputLines;
    OD_obj_array_t o_6306_errorModeOutput16_bit;
    OD_obj_array_t o_6307_errorValueOutput16_bit;
    OD_obj_array_t o_6308_filterConstant16OutputLines;
    OD_obj_array_t o_6320_writeState32OutputLines;
    OD_obj_array_t o_6322_polarity32OutputLines;
    OD_obj_array_t o_6326_errorMode32OutputLines;
    OD_obj_array_t o_6327_errorValue32OutputLines;
    OD_obj_array_t o_6328_filterConstant32OutputLines;
    OD_obj_array_t o_6400_readAnalogInput8Bit;
    OD_obj_array_t o_6401_readAnalogInput16Bit;
    OD_obj_array_t o_6402_readAnalogInput32Bit;
    OD_obj_array_t o_6403_readAnalogInput_Converted;
    OD_obj_array_t o_6404_readAnalogInputManufacturerSpecific;
    OD_obj_array_t o_6410_writeAnalogOutput8Bit;
    OD_obj_array_t o_6411_writeAnalogOutput16Bit;
    OD_obj_array_t o_6412_writeAnalogOutput32Bit;
    OD_obj_array_t o_6413_writeAnalogOutputReal;
    OD_obj_array_t o_6414_writeAnalogOutputManu;
    OD_obj_array_t o_6421_analogInputInterruptTriggerSelection;
    OD_obj_array_t o_6422_analogInterruptSource;
    OD_obj_var_t o_6423_globalAnalogInterruptEnable;
    OD_obj_array_t o_6424_analogInputInterruptUpperLimit;
    OD_obj_array_t o_6425_analogInputInterruptLowerLimit;
    OD_obj_array_t o_6426_analogInputInterruptDelta;
    OD_obj_array_t o_6427_analogInputInterruptNegativeDelta;
    OD_obj_array_t o_6428_analogInputInterruptPositiveDelta;
    OD_obj_array_t o_6429_analogInputInterruptRealUpperLimit;
    OD_obj_array_t o_642A_analogInputInterruptRealLowerLimit;
    OD_obj_array_t o_642B_analogInputInterruptRealDelta;
    OD_obj_array_t o_642C_analogInputInterruptRealNegativeDelta;
    OD_obj_array_t o_642D_analogInputInterruptRealPositiveDelta;
    OD_obj_array_t o_642E_analogInputConversionOffset;
    OD_obj_array_t o_642F_analogInputConversionScaling;
    OD_obj_array_t o_6430_analogInputSI;
    OD_obj_array_t o_6431_analogInputOffsetInteger;
    OD_obj_array_t o_6432_analogInputScalingInteger;
    OD_obj_array_t o_6441_analogOutputConversionOffset;
    OD_obj_array_t o_6442_analogOutputConversionScaling;
    OD_obj_array_t o_6443_analogOutputFaultMode;
    OD_obj_array_t o_6444_defaultAnalogOutputFaultStateUnconverted;
    OD_obj_array_t o_6445_defaultRealAnalogOutputFaultStateUnconverted;
    OD_obj_array_t o_6446_analogOutputOffsetInteger;
    OD_obj_array_t o_6447_analogOutputScalingInteger;
    OD_obj_array_t o_6450_analogOutputSI;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_RAM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R,
        .dataLength = 1
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 0
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_RAM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identityObject = {
        {
            .dataOrig = &OD_RAM.x1018_identityObject.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1400_receivePDO_CommunicationParameter1 = {
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1400_receivePDO_CommunicationParameter1.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1401_receivePDO_CommunicationParameter2 = {
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1401_receivePDO_CommunicationParameter2.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_receivePDO_MappingParameter1 = {
        {
            .dataOrig = &OD_RAM.x1600_receivePDO_MappingParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_receivePDO_MappingParameter2 = {
        {
            .dataOrig = &OD_RAM.x1601_receivePDO_MappingParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = NULL,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = NULL,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_transmitPDO_CommunicationParameter1 = {
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1800_transmitPDO_CommunicationParameter1.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1801_transmitPDO_CommunicationParameter2 = {
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.COB_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1801_transmitPDO_CommunicationParameter2.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1A00_TPDO_MappingParameter1 = {
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A00_TPDO_MappingParameter1.mappingEntry8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDO_MappingParameter2 = {
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1A01_TPDO_MappingParameter2.mappingEntry8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_6000_readInput8Bit = {
        .dataOrig0 = &OD_RAM.x6000_readInput8Bit_sub0,
        .dataOrig = &OD_RAM.x6000_readInput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6002_polarity8InputLines = {
        .dataOrig0 = &OD_RAM.x6002_polarity8InputLines_sub0,
        .dataOrig = &OD_RAM.x6002_polarity8InputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6003_filterConstant8InputLines = {
        .dataOrig0 = &OD_RAM.x6003_filterConstant8InputLines_sub0,
        .dataOrig = &OD_RAM.x6003_filterConstant8InputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6005_enableDigitalInputInterrupts = {
        .dataOrig = &OD_RAM.x6005_enableDigitalInputInterrupts,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6006_inputInterruptMask8_AnyChange = {
        .dataOrig0 = &OD_RAM.x6006_inputInterruptMask8_AnyChange_sub0,
        .dataOrig = &OD_RAM.x6006_inputInterruptMask8_AnyChange[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6007_inputInterruptMask8_LowToHigh = {
        .dataOrig0 = &OD_RAM.x6007_inputInterruptMask8_LowToHigh_sub0,
        .dataOrig = &OD_RAM.x6007_inputInterruptMask8_LowToHigh[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6008_inputInterruptMask8_HighToLow = {
        .dataOrig0 = &OD_RAM.x6008_inputInterruptMask8_HighToLow_sub0,
        .dataOrig = &OD_RAM.x6008_inputInterruptMask8_HighToLow[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6020_readState1InputLine1_128 = {
        .dataOrig0 = &OD_RAM.x6020_readState1InputLine1_128_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6030_polarity1InputLine1_128 = {
        .dataOrig0 = &OD_RAM.x6030_polarity1InputLine1_128_sub0,
        .dataOrig = &OD_RAM.x6030_polarity1InputLine1_128[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6038_filterConstant1InputLine1_128 = {
        .dataOrig0 = &OD_RAM.x6038_filterConstant1InputLine1_128_sub0,
        .dataOrig = &OD_RAM.x6038_filterConstant1InputLine1_128[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6050_interruptMask1InputLine1_128_AnyChange = {
        .dataOrig0 = &OD_RAM.x6050_interruptMask1InputLine1_128_AnyChange_sub0,
        .dataOrig = &OD_RAM.x6050_interruptMask1InputLine1_128_AnyChange[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6060_interruptMask1InputLine1_128_LowToHigh = {
        .dataOrig0 = &OD_RAM.x6060_interruptMask1InputLine1_128_LowToHigh_sub0,
        .dataOrig = &OD_RAM.x6060_interruptMask1InputLine1_128_LowToHigh[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6070_interruptMask1InputLine1_128_HighToLow = {
        .dataOrig0 = &OD_RAM.x6070_interruptMask1InputLine1_128_HighToLow_sub0,
        .dataOrig = &OD_RAM.x6070_interruptMask1InputLine1_128_HighToLow[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6100_readState16InputLines = {
        .dataOrig0 = &OD_RAM.x6100_readState16InputLines_sub0,
        .dataOrig = &OD_RAM.x6100_readState16InputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6102_polarity16InputLines = {
        .dataOrig0 = &OD_RAM.x6102_polarity16InputLines_sub0,
        .dataOrig = &OD_RAM.x6102_polarity16InputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6103_filterConstant16InputLines = {
        .dataOrig0 = &OD_RAM.x6103_filterConstant16InputLines_sub0,
        .dataOrig = &OD_RAM.x6103_filterConstant16InputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6106_inputInterruptMask16InputLines_AnyChange = {
        .dataOrig0 = &OD_RAM.x6106_inputInterruptMask16InputLines_AnyChange_sub0,
        .dataOrig = &OD_RAM.x6106_inputInterruptMask16InputLines_AnyChange[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6107_inputInterruptMask16InputLines_LowToHigh = {
        .dataOrig0 = &OD_RAM.x6107_inputInterruptMask16InputLines_LowToHigh_sub0,
        .dataOrig = &OD_RAM.x6107_inputInterruptMask16InputLines_LowToHigh[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6108_inputInterruptMask16InputLines_HighToLow = {
        .dataOrig0 = &OD_RAM.x6108_inputInterruptMask16InputLines_HighToLow_sub0,
        .dataOrig = &OD_RAM.x6108_inputInterruptMask16InputLines_HighToLow[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6120_readState32InputLines = {
        .dataOrig0 = &OD_RAM.x6120_readState32InputLines_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6122_polarity32InputLines = {
        .dataOrig0 = &OD_RAM.x6122_polarity32InputLines_sub0,
        .dataOrig = &OD_RAM.x6122_polarity32InputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6123_filterConstant32InputLines = {
        .dataOrig0 = &OD_RAM.x6123_filterConstant32InputLines_sub0,
        .dataOrig = &OD_RAM.x6123_filterConstant32InputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6126_inputInterruptMask32InputLines_AnyChange = {
        .dataOrig0 = &OD_RAM.x6126_inputInterruptMask32InputLines_AnyChange_sub0,
        .dataOrig = &OD_RAM.x6126_inputInterruptMask32InputLines_AnyChange[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6127_inputInterruptMask32InputLines_LowToHigh = {
        .dataOrig0 = &OD_RAM.x6127_inputInterruptMask32InputLines_LowToHigh_sub0,
        .dataOrig = &OD_RAM.x6127_inputInterruptMask32InputLines_LowToHigh[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6128_inputInterruptMask32InputLines_HighToLow = {
        .dataOrig0 = &OD_RAM.x6128_inputInterruptMask32InputLines_HighToLow_sub0,
        .dataOrig = &OD_RAM.x6128_inputInterruptMask32InputLines_HighToLow[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6200_writeOutput8_bit = {
        .dataOrig0 = &OD_RAM.x6200_writeOutput8_bit_sub0,
        .dataOrig = &OD_RAM.x6200_writeOutput8_bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6202_polarity8OutputLines = {
        .dataOrig0 = &OD_RAM.x6202_polarity8OutputLines_sub0,
        .dataOrig = &OD_RAM.x6202_polarity8OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6206_faultMode8OutputLines = {
        .dataOrig0 = &OD_RAM.x6206_faultMode8OutputLines_sub0,
        .dataOrig = &OD_RAM.x6206_faultMode8OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6207_faultState8OutputLines = {
        .dataOrig0 = &OD_RAM.x6207_faultState8OutputLines_sub0,
        .dataOrig = &OD_RAM.x6207_faultState8OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6208_filterConstant8OutputLines = {
        .dataOrig0 = &OD_RAM.x6208_filterConstant8OutputLines_sub0,
        .dataOrig = &OD_RAM.x6208_filterConstant8OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6220_writeState1OutputLine1_128 = {
        .dataOrig0 = &OD_RAM.x6220_writeState1OutputLine1_128_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6240_polarity1OutputLine1_128 = {
        .dataOrig0 = &OD_RAM.x6240_polarity1OutputLine1_128_sub0,
        .dataOrig = &OD_RAM.x6240_polarity1OutputLine1_128[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6250_faultMode1OutputLine1_128 = {
        .dataOrig0 = &OD_RAM.x6250_faultMode1OutputLine1_128_sub0,
        .dataOrig = &OD_RAM.x6250_faultMode1OutputLine1_128[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6260_faultState1OutputLine1_128 = {
        .dataOrig0 = &OD_RAM.x6260_faultState1OutputLine1_128_sub0,
        .dataOrig = &OD_RAM.x6260_faultState1OutputLine1_128[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6270_filterConstant1OutputLine1_128 = {
        .dataOrig0 = &OD_RAM.x6270_filterConstant1OutputLine1_128_sub0,
        .dataOrig = &OD_RAM.x6270_filterConstant1OutputLine1_128[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(bool_t)
    },
    .o_6300_writeState16OutputLines = {
        .dataOrig0 = &OD_RAM.x6300_writeState16OutputLines_sub0,
        .dataOrig = &OD_RAM.x6300_writeState16OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6302_polarity16OutputLines = {
        .dataOrig0 = &OD_RAM.x6302_polarity16OutputLines_sub0,
        .dataOrig = &OD_RAM.x6302_polarity16OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6306_errorModeOutput16_bit = {
        .dataOrig0 = &OD_RAM.x6306_errorModeOutput16_bit_sub0,
        .dataOrig = &OD_RAM.x6306_errorModeOutput16_bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6307_errorValueOutput16_bit = {
        .dataOrig0 = &OD_RAM.x6307_errorValueOutput16_bit_sub0,
        .dataOrig = &OD_RAM.x6307_errorValueOutput16_bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6308_filterConstant16OutputLines = {
        .dataOrig0 = &OD_RAM.x6308_filterConstant16OutputLines_sub0,
        .dataOrig = &OD_RAM.x6308_filterConstant16OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6320_writeState32OutputLines = {
        .dataOrig0 = &OD_RAM.x6320_writeState32OutputLines_sub0,
        .dataOrig = &OD_RAM.x6320_writeState32OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6322_polarity32OutputLines = {
        .dataOrig0 = &OD_RAM.x6322_polarity32OutputLines_sub0,
        .dataOrig = &OD_RAM.x6322_polarity32OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6326_errorMode32OutputLines = {
        .dataOrig0 = &OD_RAM.x6326_errorMode32OutputLines_sub0,
        .dataOrig = &OD_RAM.x6326_errorMode32OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6327_errorValue32OutputLines = {
        .dataOrig0 = &OD_RAM.x6327_errorValue32OutputLines_sub0,
        .dataOrig = &OD_RAM.x6327_errorValue32OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6328_filterConstant32OutputLines = {
        .dataOrig0 = &OD_RAM.x6328_filterConstant32OutputLines_sub0,
        .dataOrig = &OD_RAM.x6328_filterConstant32OutputLines[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6400_readAnalogInput8Bit = {
        .dataOrig0 = &OD_RAM.x6400_readAnalogInput8Bit_sub0,
        .dataOrig = &OD_RAM.x6400_readAnalogInput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(int8_t)
    },
    .o_6401_readAnalogInput16Bit = {
        .dataOrig0 = &OD_RAM.x6401_readAnalogInput16Bit_sub0,
        .dataOrig = &OD_RAM.x6401_readAnalogInput16Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_6402_readAnalogInput32Bit = {
        .dataOrig0 = &OD_RAM.x6402_readAnalogInput32Bit_sub0,
        .dataOrig = &OD_RAM.x6402_readAnalogInput32Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6403_readAnalogInput_Converted = {
        .dataOrig0 = &OD_RAM.x6403_readAnalogInput_Converted_sub0,
        .dataOrig = &OD_RAM.x6403_readAnalogInput_Converted[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_6404_readAnalogInputManufacturerSpecific = {
        .dataOrig0 = &OD_RAM.x6404_readAnalogInputManufacturerSpecific_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_6410_writeAnalogOutput8Bit = {
        .dataOrig0 = &OD_RAM.x6410_writeAnalogOutput8Bit_sub0,
        .dataOrig = &OD_RAM.x6410_writeAnalogOutput8Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(int8_t)
    },
    .o_6411_writeAnalogOutput16Bit = {
        .dataOrig0 = &OD_RAM.x6411_writeAnalogOutput16Bit_sub0,
        .dataOrig = &OD_RAM.x6411_writeAnalogOutput16Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(int16_t)
    },
    .o_6412_writeAnalogOutput32Bit = {
        .dataOrig0 = &OD_RAM.x6412_writeAnalogOutput32Bit_sub0,
        .dataOrig = &OD_RAM.x6412_writeAnalogOutput32Bit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6413_writeAnalogOutputReal = {
        .dataOrig0 = &OD_RAM.x6413_writeAnalogOutputReal_sub0,
        .dataOrig = &OD_RAM.x6413_writeAnalogOutputReal[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_6414_writeAnalogOutputManu = {
        .dataOrig0 = &OD_RAM.x6414_writeAnalogOutputManu_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6421_analogInputInterruptTriggerSelection = {
        .dataOrig0 = &OD_RAM.x6421_analogInputInterruptTriggerSelection_sub0,
        .dataOrig = &OD_RAM.x6421_analogInputInterruptTriggerSelection[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6422_analogInterruptSource = {
        .dataOrig0 = &OD_RAM.x6422_analogInterruptSource_sub0,
        .dataOrig = &OD_RAM.x6422_analogInterruptSource[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6423_globalAnalogInterruptEnable = {
        .dataOrig = &OD_RAM.x6423_globalAnalogInterruptEnable,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6424_analogInputInterruptUpperLimit = {
        .dataOrig0 = &OD_RAM.x6424_analogInputInterruptUpperLimit_sub0,
        .dataOrig = &OD_RAM.x6424_analogInputInterruptUpperLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6425_analogInputInterruptLowerLimit = {
        .dataOrig0 = &OD_RAM.x6425_analogInputInterruptLowerLimit_sub0,
        .dataOrig = &OD_RAM.x6425_analogInputInterruptLowerLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6426_analogInputInterruptDelta = {
        .dataOrig0 = &OD_RAM.x6426_analogInputInterruptDelta_sub0,
        .dataOrig = &OD_RAM.x6426_analogInputInterruptDelta[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6427_analogInputInterruptNegativeDelta = {
        .dataOrig0 = &OD_RAM.x6427_analogInputInterruptNegativeDelta_sub0,
        .dataOrig = &OD_RAM.x6427_analogInputInterruptNegativeDelta[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6428_analogInputInterruptPositiveDelta = {
        .dataOrig0 = &OD_RAM.x6428_analogInputInterruptPositiveDelta_sub0,
        .dataOrig = &OD_RAM.x6428_analogInputInterruptPositiveDelta[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6429_analogInputInterruptRealUpperLimit = {
        .dataOrig0 = &OD_RAM.x6429_analogInputInterruptRealUpperLimit_sub0,
        .dataOrig = &OD_RAM.x6429_analogInputInterruptRealUpperLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_642A_analogInputInterruptRealLowerLimit = {
        .dataOrig0 = &OD_RAM.x642A_analogInputInterruptRealLowerLimit_sub0,
        .dataOrig = &OD_RAM.x642A_analogInputInterruptRealLowerLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_642B_analogInputInterruptRealDelta = {
        .dataOrig0 = &OD_RAM.x642B_analogInputInterruptRealDelta_sub0,
        .dataOrig = &OD_RAM.x642B_analogInputInterruptRealDelta[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_642C_analogInputInterruptRealNegativeDelta = {
        .dataOrig0 = &OD_RAM.x642C_analogInputInterruptRealNegativeDelta_sub0,
        .dataOrig = &OD_RAM.x642C_analogInputInterruptRealNegativeDelta[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_642D_analogInputInterruptRealPositiveDelta = {
        .dataOrig0 = &OD_RAM.x642D_analogInputInterruptRealPositiveDelta_sub0,
        .dataOrig = &OD_RAM.x642D_analogInputInterruptRealPositiveDelta[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_642E_analogInputConversionOffset = {
        .dataOrig0 = &OD_RAM.x642E_analogInputConversionOffset_sub0,
        .dataOrig = &OD_RAM.x642E_analogInputConversionOffset[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_642F_analogInputConversionScaling = {
        .dataOrig0 = &OD_RAM.x642F_analogInputConversionScaling_sub0,
        .dataOrig = &OD_RAM.x642F_analogInputConversionScaling[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_6430_analogInputSI = {
        .dataOrig0 = &OD_RAM.x6430_analogInputSI_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6431_analogInputOffsetInteger = {
        .dataOrig0 = &OD_RAM.x6431_analogInputOffsetInteger_sub0,
        .dataOrig = &OD_RAM.x6431_analogInputOffsetInteger[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6432_analogInputScalingInteger = {
        .dataOrig0 = &OD_RAM.x6432_analogInputScalingInteger_sub0,
        .dataOrig = &OD_RAM.x6432_analogInputScalingInteger[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6441_analogOutputConversionOffset = {
        .dataOrig0 = &OD_RAM.x6441_analogOutputConversionOffset_sub0,
        .dataOrig = &OD_RAM.x6441_analogOutputConversionOffset[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_6442_analogOutputConversionScaling = {
        .dataOrig0 = &OD_RAM.x6442_analogOutputConversionScaling_sub0,
        .dataOrig = &OD_RAM.x6442_analogOutputConversionScaling[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_6443_analogOutputFaultMode = {
        .dataOrig0 = &OD_RAM.x6443_analogOutputFaultMode_sub0,
        .dataOrig = &OD_RAM.x6443_analogOutputFaultMode[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6444_defaultAnalogOutputFaultStateUnconverted = {
        .dataOrig0 = &OD_RAM.x6444_defaultAnalogOutputFaultStateUnconverted_sub0,
        .dataOrig = &OD_RAM.x6444_defaultAnalogOutputFaultStateUnconverted[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6445_defaultRealAnalogOutputFaultStateUnconverted = {
        .dataOrig0 = &OD_RAM.x6445_defaultRealAnalogOutputFaultStateUnconverted_sub0,
        .dataOrig = &OD_RAM.x6445_defaultRealAnalogOutputFaultStateUnconverted[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_6446_analogOutputOffsetInteger = {
        .dataOrig0 = &OD_RAM.x6446_analogOutputOffsetInteger_sub0,
        .dataOrig = &OD_RAM.x6446_analogOutputOffsetInteger[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6447_analogOutputScalingInteger = {
        .dataOrig0 = &OD_RAM.x6447_analogOutputScalingInteger_sub0,
        .dataOrig = &OD_RAM.x6447_analogOutputScalingInteger[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6450_analogOutputSI = {
        .dataOrig0 = &OD_RAM.x6450_analogOutputSI_sub0,
        .dataOrig = &OD_RAM.x6450_analogOutputSI[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identityObject, NULL},
    {0x1400, 0x03, ODT_REC, &ODObjs.o_1400_receivePDO_CommunicationParameter1, NULL},
    {0x1401, 0x03, ODT_REC, &ODObjs.o_1401_receivePDO_CommunicationParameter2, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_receivePDO_MappingParameter1, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_receivePDO_MappingParameter2, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_transmitPDO_CommunicationParameter1, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_transmitPDO_CommunicationParameter2, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDO_MappingParameter1, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDO_MappingParameter2, NULL},
    {0x6000, 0x03, ODT_ARR, &ODObjs.o_6000_readInput8Bit, NULL},
    {0x6002, 0x03, ODT_ARR, &ODObjs.o_6002_polarity8InputLines, NULL},
    {0x6003, 0x03, ODT_ARR, &ODObjs.o_6003_filterConstant8InputLines, NULL},
    {0x6005, 0x01, ODT_VAR, &ODObjs.o_6005_enableDigitalInputInterrupts, NULL},
    {0x6006, 0x03, ODT_ARR, &ODObjs.o_6006_inputInterruptMask8_AnyChange, NULL},
    {0x6007, 0x03, ODT_ARR, &ODObjs.o_6007_inputInterruptMask8_LowToHigh, NULL},
    {0x6008, 0x03, ODT_ARR, &ODObjs.o_6008_inputInterruptMask8_HighToLow, NULL},
    {0x6020, 0x11, ODT_ARR, &ODObjs.o_6020_readState1InputLine1_128, NULL},
    {0x6030, 0x11, ODT_ARR, &ODObjs.o_6030_polarity1InputLine1_128, NULL},
    {0x6038, 0x11, ODT_ARR, &ODObjs.o_6038_filterConstant1InputLine1_128, NULL},
    {0x6050, 0x11, ODT_ARR, &ODObjs.o_6050_interruptMask1InputLine1_128_AnyChange, NULL},
    {0x6060, 0x11, ODT_ARR, &ODObjs.o_6060_interruptMask1InputLine1_128_LowToHigh, NULL},
    {0x6070, 0x11, ODT_ARR, &ODObjs.o_6070_interruptMask1InputLine1_128_HighToLow, NULL},
    {0x6100, 0x02, ODT_ARR, &ODObjs.o_6100_readState16InputLines, NULL},
    {0x6102, 0x02, ODT_ARR, &ODObjs.o_6102_polarity16InputLines, NULL},
    {0x6103, 0x02, ODT_ARR, &ODObjs.o_6103_filterConstant16InputLines, NULL},
    {0x6106, 0x02, ODT_ARR, &ODObjs.o_6106_inputInterruptMask16InputLines_AnyChange, NULL},
    {0x6107, 0x02, ODT_ARR, &ODObjs.o_6107_inputInterruptMask16InputLines_LowToHigh, NULL},
    {0x6108, 0x02, ODT_ARR, &ODObjs.o_6108_inputInterruptMask16InputLines_HighToLow, NULL},
    {0x6120, 0x02, ODT_ARR, &ODObjs.o_6120_readState32InputLines, NULL},
    {0x6122, 0x02, ODT_ARR, &ODObjs.o_6122_polarity32InputLines, NULL},
    {0x6123, 0x02, ODT_ARR, &ODObjs.o_6123_filterConstant32InputLines, NULL},
    {0x6126, 0x02, ODT_ARR, &ODObjs.o_6126_inputInterruptMask32InputLines_AnyChange, NULL},
    {0x6127, 0x02, ODT_ARR, &ODObjs.o_6127_inputInterruptMask32InputLines_LowToHigh, NULL},
    {0x6128, 0x02, ODT_ARR, &ODObjs.o_6128_inputInterruptMask32InputLines_HighToLow, NULL},
    {0x6200, 0x03, ODT_ARR, &ODObjs.o_6200_writeOutput8_bit, NULL},
    {0x6202, 0x03, ODT_ARR, &ODObjs.o_6202_polarity8OutputLines, NULL},
    {0x6206, 0x03, ODT_ARR, &ODObjs.o_6206_faultMode8OutputLines, NULL},
    {0x6207, 0x03, ODT_ARR, &ODObjs.o_6207_faultState8OutputLines, NULL},
    {0x6208, 0x03, ODT_ARR, &ODObjs.o_6208_filterConstant8OutputLines, NULL},
    {0x6220, 0x09, ODT_ARR, &ODObjs.o_6220_writeState1OutputLine1_128, NULL},
    {0x6240, 0x09, ODT_ARR, &ODObjs.o_6240_polarity1OutputLine1_128, NULL},
    {0x6250, 0x09, ODT_ARR, &ODObjs.o_6250_faultMode1OutputLine1_128, NULL},
    {0x6260, 0x09, ODT_ARR, &ODObjs.o_6260_faultState1OutputLine1_128, NULL},
    {0x6270, 0x09, ODT_ARR, &ODObjs.o_6270_filterConstant1OutputLine1_128, NULL},
    {0x6300, 0x02, ODT_ARR, &ODObjs.o_6300_writeState16OutputLines, NULL},
    {0x6302, 0x02, ODT_ARR, &ODObjs.o_6302_polarity16OutputLines, NULL},
    {0x6306, 0x02, ODT_ARR, &ODObjs.o_6306_errorModeOutput16_bit, NULL},
    {0x6307, 0x02, ODT_ARR, &ODObjs.o_6307_errorValueOutput16_bit, NULL},
    {0x6308, 0x02, ODT_ARR, &ODObjs.o_6308_filterConstant16OutputLines, NULL},
    {0x6320, 0x02, ODT_ARR, &ODObjs.o_6320_writeState32OutputLines, NULL},
    {0x6322, 0x02, ODT_ARR, &ODObjs.o_6322_polarity32OutputLines, NULL},
    {0x6326, 0x02, ODT_ARR, &ODObjs.o_6326_errorMode32OutputLines, NULL},
    {0x6327, 0x02, ODT_ARR, &ODObjs.o_6327_errorValue32OutputLines, NULL},
    {0x6328, 0x02, ODT_ARR, &ODObjs.o_6328_filterConstant32OutputLines, NULL},
    {0x6400, 0x09, ODT_ARR, &ODObjs.o_6400_readAnalogInput8Bit, NULL},
    {0x6401, 0x09, ODT_ARR, &ODObjs.o_6401_readAnalogInput16Bit, NULL},
    {0x6402, 0x02, ODT_ARR, &ODObjs.o_6402_readAnalogInput32Bit, NULL},
    {0x6403, 0x09, ODT_ARR, &ODObjs.o_6403_readAnalogInput_Converted, NULL},
    {0x6404, 0x03, ODT_ARR, &ODObjs.o_6404_readAnalogInputManufacturerSpecific, NULL},
    {0x6410, 0x09, ODT_ARR, &ODObjs.o_6410_writeAnalogOutput8Bit, NULL},
    {0x6411, 0x03, ODT_ARR, &ODObjs.o_6411_writeAnalogOutput16Bit, NULL},
    {0x6412, 0x03, ODT_ARR, &ODObjs.o_6412_writeAnalogOutput32Bit, NULL},
    {0x6413, 0x03, ODT_ARR, &ODObjs.o_6413_writeAnalogOutputReal, NULL},
    {0x6414, 0x02, ODT_ARR, &ODObjs.o_6414_writeAnalogOutputManu, NULL},
    {0x6421, 0x09, ODT_ARR, &ODObjs.o_6421_analogInputInterruptTriggerSelection, NULL},
    {0x6422, 0x02, ODT_ARR, &ODObjs.o_6422_analogInterruptSource, NULL},
    {0x6423, 0x01, ODT_VAR, &ODObjs.o_6423_globalAnalogInterruptEnable, NULL},
    {0x6424, 0x09, ODT_ARR, &ODObjs.o_6424_analogInputInterruptUpperLimit, NULL},
    {0x6425, 0x09, ODT_ARR, &ODObjs.o_6425_analogInputInterruptLowerLimit, NULL},
    {0x6426, 0x09, ODT_ARR, &ODObjs.o_6426_analogInputInterruptDelta, NULL},
    {0x6427, 0x02, ODT_ARR, &ODObjs.o_6427_analogInputInterruptNegativeDelta, NULL},
    {0x6428, 0x02, ODT_ARR, &ODObjs.o_6428_analogInputInterruptPositiveDelta, NULL},
    {0x6429, 0x02, ODT_ARR, &ODObjs.o_6429_analogInputInterruptRealUpperLimit, NULL},
    {0x642A, 0x02, ODT_ARR, &ODObjs.o_642A_analogInputInterruptRealLowerLimit, NULL},
    {0x642B, 0x03, ODT_ARR, &ODObjs.o_642B_analogInputInterruptRealDelta, NULL},
    {0x642C, 0x03, ODT_ARR, &ODObjs.o_642C_analogInputInterruptRealNegativeDelta, NULL},
    {0x642D, 0x02, ODT_ARR, &ODObjs.o_642D_analogInputInterruptRealPositiveDelta, NULL},
    {0x642E, 0x09, ODT_ARR, &ODObjs.o_642E_analogInputConversionOffset, NULL},
    {0x642F, 0x09, ODT_ARR, &ODObjs.o_642F_analogInputConversionScaling, NULL},
    {0x6430, 0x02, ODT_ARR, &ODObjs.o_6430_analogInputSI, NULL},
    {0x6431, 0x02, ODT_ARR, &ODObjs.o_6431_analogInputOffsetInteger, NULL},
    {0x6432, 0x02, ODT_ARR, &ODObjs.o_6432_analogInputScalingInteger, NULL},
    {0x6441, 0x09, ODT_ARR, &ODObjs.o_6441_analogOutputConversionOffset, NULL},
    {0x6442, 0x09, ODT_ARR, &ODObjs.o_6442_analogOutputConversionScaling, NULL},
    {0x6443, 0x03, ODT_ARR, &ODObjs.o_6443_analogOutputFaultMode, NULL},
    {0x6444, 0x03, ODT_ARR, &ODObjs.o_6444_defaultAnalogOutputFaultStateUnconverted, NULL},
    {0x6445, 0x02, ODT_ARR, &ODObjs.o_6445_defaultRealAnalogOutputFaultStateUnconverted, NULL},
    {0x6446, 0x02, ODT_ARR, &ODObjs.o_6446_analogOutputOffsetInteger, NULL},
    {0x6447, 0x02, ODT_ARR, &ODObjs.o_6447_analogOutputScalingInteger, NULL},
    {0x6450, 0x02, ODT_ARR, &ODObjs.o_6450_analogOutputSI, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
