/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1018_identity = {
        .numberOfEntries = 0x04,
        .vendorID = 0x00000000,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x2001_BOOLEAN = false,
    .x2002_INTEGER8 = 12,
    .x2003_INTEGER16 = 34,
    .x2004_INTEGER32 = 45,
    .x2005_UNSIGNED8 = 0x38,
    .x2006_UNSIGNED16 = 0x2006,
    .x2007_UNSIGNED32 = 0x20072008,
    .x2008_REAL32 = 1.2,
    .x2009_VISIBLE_STRING = {'A', 'B', 'C', 'D', 0},
    .x200B_UNICODE_STRING = {0x0061, 0x0062, 0x0063, 0x2713, 0x0000},
    .x2011_REAL64 = 1.6,
    .x2015_INTEGER64 = -64,
    .x2016_UNSIGNED24 = {0x18, 0x00, 0x00},
    .x2018_UNSIGNED40 = {0x28, 0x00, 0x00, 0x00, 0x00},
    .x2019_UNSIGNED48 = {0x30, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x201A_UNSIGNED56 = {0x38, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x201B_UNSIGNED64 = 0x0000000000000040
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_2001_BOOLEAN;
    OD_obj_var_t o_2002_INTEGER8;
    OD_obj_var_t o_2003_INTEGER16;
    OD_obj_var_t o_2004_INTEGER32;
    OD_obj_var_t o_2005_UNSIGNED8;
    OD_obj_var_t o_2006_UNSIGNED16;
    OD_obj_var_t o_2007_UNSIGNED32;
    OD_obj_var_t o_2008_REAL32;
    OD_obj_var_t o_2009_VISIBLE_STRING;
    OD_obj_var_t o_200A_OCTET_STRING;
    OD_obj_var_t o_200B_UNICODE_STRING;
    OD_obj_var_t o_200F_DOMAIN;
    OD_obj_var_t o_2010_INTEGER24;
    OD_obj_var_t o_2011_REAL64;
    OD_obj_var_t o_2012_INTEGER40;
    OD_obj_var_t o_2013_INTEGER48;
    OD_obj_var_t o_2014_INTEGER56;
    OD_obj_var_t o_2015_INTEGER64;
    OD_obj_var_t o_2016_UNSIGNED24;
    OD_obj_var_t o_2018_UNSIGNED40;
    OD_obj_var_t o_2019_UNSIGNED48;
    OD_obj_var_t o_201A_UNSIGNED56;
    OD_obj_var_t o_201B_UNSIGNED64;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1018_identity = {
        {
            .dataOrig = &OD_RAM.x1018_identity.numberOfEntries,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1018_identity.vendorID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2001_BOOLEAN = {
        .dataOrig = &OD_RAM.x2001_BOOLEAN,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2002_INTEGER8 = {
        .dataOrig = &OD_RAM.x2002_INTEGER8,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2003_INTEGER16 = {
        .dataOrig = &OD_RAM.x2003_INTEGER16,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2004_INTEGER32 = {
        .dataOrig = &OD_RAM.x2004_INTEGER32,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2005_UNSIGNED8 = {
        .dataOrig = &OD_RAM.x2005_UNSIGNED8,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 1
    },
    .o_2006_UNSIGNED16 = {
        .dataOrig = &OD_RAM.x2006_UNSIGNED16,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2007_UNSIGNED32 = {
        .dataOrig = &OD_RAM.x2007_UNSIGNED32,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2008_REAL32 = {
        .dataOrig = &OD_RAM.x2008_REAL32,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_2009_VISIBLE_STRING = {
        .dataOrig = &OD_RAM.x2009_VISIBLE_STRING[0],
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_STR,
        .dataLength = 4
    },
    .o_200A_OCTET_STRING = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 0
    },
    .o_200B_UNICODE_STRING = {
        .dataOrig = &OD_RAM.x200B_UNICODE_STRING[0],
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_STR,
        .dataLength = 8
    },
    .o_200F_DOMAIN = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 0
    },
    .o_2010_INTEGER24 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 3
    },
    .o_2011_REAL64 = {
        .dataOrig = &OD_RAM.x2011_REAL64,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 8
    },
    .o_2012_INTEGER40 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 5
    },
    .o_2013_INTEGER48 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 6
    },
    .o_2014_INTEGER56 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 7
    },
    .o_2015_INTEGER64 = {
        .dataOrig = &OD_RAM.x2015_INTEGER64,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 8
    },
    .o_2016_UNSIGNED24 = {
        .dataOrig = &OD_RAM.x2016_UNSIGNED24[0],
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 3
    },
    .o_2018_UNSIGNED40 = {
        .dataOrig = &OD_RAM.x2018_UNSIGNED40[0],
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 5
    },
    .o_2019_UNSIGNED48 = {
        .dataOrig = &OD_RAM.x2019_UNSIGNED48[0],
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 6
    },
    .o_201A_UNSIGNED56 = {
        .dataOrig = &OD_RAM.x201A_UNSIGNED56[0],
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 7
    },
    .o_201B_UNSIGNED64 = {
        .dataOrig = &OD_RAM.x201B_UNSIGNED64,
        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
        .dataLength = 8
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x2001, 0x01, ODT_VAR, &ODObjs.o_2001_BOOLEAN, NULL},
    {0x2002, 0x01, ODT_VAR, &ODObjs.o_2002_INTEGER8, NULL},
    {0x2003, 0x01, ODT_VAR, &ODObjs.o_2003_INTEGER16, NULL},
    {0x2004, 0x01, ODT_VAR, &ODObjs.o_2004_INTEGER32, NULL},
    {0x2005, 0x01, ODT_VAR, &ODObjs.o_2005_UNSIGNED8, NULL},
    {0x2006, 0x01, ODT_VAR, &ODObjs.o_2006_UNSIGNED16, NULL},
    {0x2007, 0x01, ODT_VAR, &ODObjs.o_2007_UNSIGNED32, NULL},
    {0x2008, 0x01, ODT_VAR, &ODObjs.o_2008_REAL32, NULL},
    {0x2009, 0x01, ODT_VAR, &ODObjs.o_2009_VISIBLE_STRING, NULL},
    {0x200A, 0x01, ODT_VAR, &ODObjs.o_200A_OCTET_STRING, NULL},
    {0x200B, 0x01, ODT_VAR, &ODObjs.o_200B_UNICODE_STRING, NULL},
    {0x200F, 0x01, ODT_VAR, &ODObjs.o_200F_DOMAIN, NULL},
    {0x2010, 0x01, ODT_VAR, &ODObjs.o_2010_INTEGER24, NULL},
    {0x2011, 0x01, ODT_VAR, &ODObjs.o_2011_REAL64, NULL},
    {0x2012, 0x01, ODT_VAR, &ODObjs.o_2012_INTEGER40, NULL},
    {0x2013, 0x01, ODT_VAR, &ODObjs.o_2013_INTEGER48, NULL},
    {0x2014, 0x01, ODT_VAR, &ODObjs.o_2014_INTEGER56, NULL},
    {0x2015, 0x01, ODT_VAR, &ODObjs.o_2015_INTEGER64, NULL},
    {0x2016, 0x01, ODT_VAR, &ODObjs.o_2016_UNSIGNED24, NULL},
    {0x2018, 0x01, ODT_VAR, &ODObjs.o_2018_UNSIGNED40, NULL},
    {0x2019, 0x01, ODT_VAR, &ODObjs.o_2019_UNSIGNED48, NULL},
    {0x201A, 0x01, ODT_VAR, &ODObjs.o_201A_UNSIGNED56, NULL},
    {0x201B, 0x01, ODT_VAR, &ODObjs.o_201B_UNSIGNED64, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
